### ISSUE TITLE
overlay simulated diffraction patterns using wppf

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1002]
Use wppf to overlay simulated powder diffraction pattern instead just lines. The overlay menu can have a check box to turn this feature on/off. The parameter list needs to be simpler than the full Rietveld model, so there's some work which needs to be done there.

**Comment by joelvbernier** [comment]
@saransh13 -- can we get this done by September 30?

**Comment by saransh13** [comment]
Yeah I'll work on this next week. I think it's pretty doable.
