### ISSUE TITLE
Use view data for brightness and contrast histogram

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1003]
Currently, the raw data (with no intensity corrections) is used in the brightness and contrast histogram. This histogram is subsequently used for the automatic adjustments via the "Auto" button.

Instead of the raw data, we should use whatever data the user has in the view (Cartesian or Polar), and with the intensity corrections applied. This way, the auto button will be much more useful for these cases.

**Comment by joelvbernier** [comment]
@psavery -- is this still something we need to fix?

**Comment by psavery** [comment]
Yes it is
