### ISSUE TITLE
Add ability to save SNIP background

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1029]
Here are some functionalities we need for the SNIP background:
- [x] Add an export (HDF5, like `PolarView` export) option to SNIP viewer
- [x] Automatically add SNIP background as a dataset in existing polar export (if enabled)
- [x] Independent colormap editor in SNIP viewer (incl. B&C)

**Comment by psavery** [comment]
The SNIP background is actually already exported as a dataset in the existing polar export. It has the key "snip_background". I'll check that option.

Also, there is some colormap editing capabilities to the SNIP viewer currently through the matplotlib button "Edit axis, curve and image parameters". But we can add a brightness and contrast editor to it as well.
