### ISSUE TITLE
Need powder line intensities added to reflection table

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1042]
for sorting reflections for powder diffraction, we should add an I_p value column to the reflection table in addition to |F|^2, calculated in the standard way (@saransh13 -- this should probably be made to be an output property of `PlaneData`).

In essence, it involves multiplying the |F|^2 by the multiplicity and a Lorentz factor, but it can vary significantly from |F|^2.

**Comment by psavery** [comment]
Okay, if @saransh13 makes it an output of `PlaneData`, I can add it to the table.
