### ISSUE TITLE
Add log-log-root scale option

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1060]
I have found that scaling images by log(log(sqrt(PSL + 1) + 1) +1) is very helpful for visually inspecting powder XRD data. This is the same scaling that SNIP uses. Is it possible to add that option (or replace log altogether?).

![image](https://user-images.githubusercontent.com/59886900/137365127-e74c3410-567e-485b-9979-348317922502.png)

**Comment by joelvbernier** [comment]
@psavery -- I think we also need to revisit whether we  actually scale the image data instead of the colormap as well.  ImageJ makes a scaled copy of the image under "math" operations, which is what I think we want...
