### ISSUE TITLE
"Limit Active" toggle is modifying reflections table, not just exclusions

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1072]
This seems like counter-intuitive behavior to me.  Did this get changed recently?  In the past, I thought the table was strictly displaying _all_ reflections generated to the specified `dmin`, but now toggling "Limit Active" is modifying the table rows.  It would seem clearer perhaps to have that toggle just modify exclusions via logical or with whatever ones might be selected by the user in the table.  Thoughts?

**Comment by psavery** [comment]
I have done this in #1075
