### ISSUE TITLE
Need mask viewer in "Configure Panel Buffer" widget

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1081]
A simple "show" button in the buffer config widget would be very useful.

**Comment by joelvbernier** [comment]
@bnmajor What do you think about this?

**Comment by bnmajor** [comment]
@joelvbernier Are you interested in displaying the raw data? Or some sort of canvas displaying the masked region?

**Comment by psavery** [comment]
Here is some sample code that can be called for numpy panel buffers that likely needs a little improvement (such as cleaning up the dialog)
```
    def show_panel_buffer(self):
        detector_config = HexrdConfig().detector(self.detector)
        buffer = detector_config['buffer']['value']

        fig, ax = plt.subplots()
        fig.canvas.manager.set_window_title('HEXRD')
        ax.set_title('Panel Buffer')

        ax.imshow(buffer)
        fig.canvas.draw_idle()
        fig.show()
```
