### ISSUE TITLE
Delete points not working in Laue auto pick wizard 

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1086]
Performing auto picking of Laue points and trying to delete points not working as expected.

https://user-images.githubusercontent.com/15834451/138978702-7a1c36be-1579-401b-a253-f60bc71e0ab4.mov

**Comment by joelvbernier** [comment]
It still plots all expected spots, but I think we could do better w.r.t. plotting the measured spots because they are either hard to see, or don't get shown all together anymore (where as the "current" spot could be highlighted in some way _e.g._ by changing color).

**Comment by joelvbernier** [comment]
@saransh13 -- the ideal is that this table would always show the predicted positions, and would have non-nan values if any spots were autofit or otherwise picked.

**Comment by saransh13** [comment]
Got it. Closing the issue.

**Comment by joelvbernier** [comment]
I agree it can get busy -- we can decide if we want to change the behavior.  For now, this table is 1:1 tied to the overlay
