### ISSUE TITLE
Pole figure (PF), inverse pole figure (IPF) color map and orientation distribution function (ODF) maps based on FF-HEDM data

### ISSUE THREAD

**Issue by minety** [HEXRD/hexrdgui#1096]
Hi Joel,

I'm using MTEX (MATLAB) right now for these types of texture analyses. But it would be very helpful to have it in python especially when working together with packages in hexrd. 

Thanks a lot,
Tian

**Comment by minety** [comment]
I found that there is a texture.py in the hexrd folder which is related to IPF maps, could you show me an example of plotting IPF color with grains.out as input?
Thanks,

@joelvbernier

**Comment by joelvbernier** [comment]
@minety -- If you just want to make discrete PF/IPF from a list of grains, that is straightforward.  Here is an example from a `grains.out` result from ff-HEDM (although you could do it from the spots tables as well...):
<img width="1112" alt="Screen Shot 2022-01-12 at 3 22 20 PM" src="https://user-images.githubusercontent.com/1154130/149238781-3283f2d7-0c06-4349-b83f-72c34a235233.png">

This example is in the attached zip archive and requires the [latest hexrd](https://github.com/HEXRD/hexrd/commit/d5b404eef2aa9781202d62cbfa804f74d935be29).

As far as more MTEX-like capabilities are concerned, we have started a [new repo](https://github.com/hexrd/odfpf), a Python port of the old Cornell OdfPf package.  Stay tuned on that one.
[hedm_pf_ipf_example.zip](https://github.com/HEXRD/hexrdgui/files/7858609/hedm_pf_ipf_example.zip)
