### ISSUE TITLE
MacOS QPushButton alignment in QTreeView

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#1114]
For some reason on the mac the styling is different than on other platforms and the `QPushButton` added in the tree view for the panel buffer is cut off:
![Screen Shot 2022-01-06 at 12 41 56 PM](https://user-images.githubusercontent.com/51238406/148792550-0a060a29-78cb-433f-ab0d-a9342a0644d2.png)

When comparing the mac to linux there seems to be some sort of margin set on the button or padding set on the tree row/around the item delegate (although we don't see this issue with the checkbox):
![linux_margin](https://user-images.githubusercontent.com/51238406/148792860-4c20563f-ea47-40d7-b458-c054120e10df.png)
![mac_margin](https://user-images.githubusercontent.com/51238406/148792862-f8de2eeb-cc6d-4d29-a011-da97e17201e8.png)

After looking around for users with similar issues and attempting to adjust the style every way I could think of there were three solutions that I came up with, all of which have trade-offs:
1. Setting the padding to zero pixels in the button style sheet. This does adjust the text but not the button border for some reason:
  
    ![mac_adjusted_padding](https://user-images.githubusercontent.com/51238406/148794019-0649e8e2-95b0-4943-a2d0-02c3f712576f.png)

2. Setting the padding to zero and setting the border in the style sheet as well. This redraws the border in the correct position but loses the mac styling (setting the style sheet on an item overrides whatever base os styling is initially applied):
  
    ![adjusted_border_mac'](https://user-images.githubusercontent.com/51238406/148794713-f4b8af56-6b8f-42bc-95a9-786fc8aa2b48.png)

3. There is an option to set a universal style that is platform independent. This fixes the button styling issue, but applies the Linux styling across all platforms, which means Windows and Mac lose their nicer, os-consistent styling (This screenshot is on the mac):
  
    ![fusion_styling](https://user-images.githubusercontent.com/51238406/148794084-87e35133-eb92-400b-ab51-436e0cab291c.png)

**Comment by bnmajor** [comment]
@joelvbernier Do have a preference on any of these solutions?

@psavery @cjh1 If either of you have found issues like this before and have any suggestions or see something I'm missing please let me know. I keep feeling like I'm overlooking something obvious but it may be that there is just no ideal solution here...

**Comment by psavery** [comment]
I'm hoping to take a closer look at this later today

**Comment by joelvbernier** [comment]
Ranked choice: 3, 2, 1

**Comment by bnmajor** [comment]
@psavery Yes, I did try that but never updated my screenshots here, sorry:
![styled_mac_button](https://user-images.githubusercontent.com/51238406/148828155-aade8361-9808-4b5b-ac42-17b1c953fb54.png)

So the mac styling is technically still not there but it certainly doesn't look as bad. @joelvbernier Does this change your opinion at all? Or should we still stick with option 3?

**Comment by joelvbernier** [comment]
There might be a few other places to apply this fix...

**Comment by bnmajor** [comment]
@joelvbernier If you come across some more let me know and I can add them onto the PR that I created. Otherwise we can always just add new fixes as the need arises.

**Comment by psavery** [comment]
By the way, it looks to me like the original Mac ones don't have much of a border, whereas ours has more of a border? But it doesn't matter too much.
