### ISSUE TITLE
Graphics canvas resize on startup

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1135]
I noticed that when the GUI fires up that the image canvas is getting clipped -- like it is initially coming in with the wrong size.  If I toggle views, it resizes properly so I can see the axes.  Is there a way to force resizing?
![image](https://user-images.githubusercontent.com/1154130/150582775-d520994a-93c6-43c6-ba5a-3ac20e0495ca.png)

**Comment by psavery** [comment]
@bnmajor A note on this: the first render is being called [here](https://github.com/HEXRD/hexrdgui/blob/5eb7a6f07ee4eefca925e53f48403db867edf690/hexrd/ui/main_window.py#L762-L764).
