### ISSUE TITLE
Do not create new thread pool every time

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#1145]
Right now a thread pool is created every time the [begin_processing](https://github.com/HEXRD/hexrdgui/blob/897b550352c86cd9413d7c9783fa12c8ef6ba1cc/hexrd/ui/image_load_manager.py#L141) is called. Instead we could do `self.thread_pool = QThreadPool()` in the `__init__`  method. We may only need one thread pool that can be reused for the entire application.

@psavery Please feel free to edit or update if needed

**Comment by psavery** [comment]
@bnmajor Actually, I was thinking that throughout the entire program, everywhere we use `QThreadPool`, we should start using [`QThreadPool.globalInstance()`](https://doc.qt.io/qt-6/qthreadpool.html#globalInstance) instead. The thing is, we don't actually need multiple thread pools, and in some cases multiple thread pools can be harmful (by causing us to accidentally use too many threads at once). It's better to use a single thread pool for our whole program.

Using that `globalInstance()` everywhere should be a nice improvement.

**Comment by bnmajor** [comment]
@psavery Sounds good to me!
