### ISSUE TITLE
Loading state does not show masks in mask manager

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#1164]
When a state is saved with masks and then loaded later no masks are listed in the mask manager

**Comment by bnmajor** [comment]
@joelvbernier I can see in the file that you shared with me that the masks are not being displayed in the mask manager. However I have still been unable to reproduce the problem. It looks like the mask data that is being loaded is incomplete so it seems the bug is actually in saving the masks sometimes. Can you share more information about what masks you are applying (hand drawn, polygon, powder, laue, threshold) and what view you're in? And I assume there were no errors or exceptions thrown when you saved the state?

**Comment by psavery** [comment]
@bnmajor Is this still an issue?

**Comment by bnmajor** [comment]
Nope, masks are successfully saved to and loaded from state!
