### ISSUE TITLE
Stack importer detector keys not being updated upon loading a new state file

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1181]
I was working in a session with detectors `Cspad_1, Cspad_2, ...`.  I loaded a different session with a single detector `GE2`.  When I open the stack importer, the old detector keys remain, and even if I import the desired imageseries with the "simple" importer, these key values will not change, leading to an exception when trying to load.  Seems like a missing signal indicating the instrument has changed.
<img width="1597" alt="Screen Shot 2022-04-04 at 8 30 17 PM" src="https://user-images.githubusercontent.com/1154130/161673662-25e009d6-b417-4f3c-b2f8-2158f7f335e7.png">

**Comment by psavery** [comment]
@bnmajor Maybe this should be listening to the [`detectors_changed` signal](https://github.com/HEXRD/hexrdgui/blob/a892c5ae2fe2232db840c43537765cc17558184a/hexrd/ui/hexrd_config.py#L96)?

**Comment by joelvbernier** [comment]
Also doesn't update upon editing of a detector name (_e.g._, in the form view).  Causes it to fail ans it is not properly finding detector names.
