### ISSUE TITLE
Materials setting are not persistent in state save

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1186]
At the minimum, the following parameters are not persistent under state save:

1. dmin
2. exlcusions

I know that the `Material` class is probably somewhat to blame, but this should be remedied ASAP.

**Comment by psavery** [comment]
@joelvbernier I was able to reproduce and fix the dmin issue via hexrd/hexrd#428.

However, I can't reproduce the exclusions issue. It looks to me that the exclusions are being saved and loaded back in correctly.

**Comment by joelvbernier** [comment]
I think some were getting clipped since the number of generated reflections was potentially different.

**Comment by psavery** [comment]
Okay, hopefully that then is also fixed by hexrd/hexrd#428.
