### ISSUE TITLE
Add option to save polar view lineout to csv

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1188]
Several users have expressed the desire for an option to export the lineout in the polar view to csv.  We could probably add the option to save either the lineout _or_ the 2-d polarview (as displayed) in the option.  Anything to add @darrencpagan?

**Comment by joelvbernier** [comment]
I think we will want 2 text-based options:

1. Save the lineout to txt
  - [ ] spec header
  - [ ] add GUI export menu item option
2. Save polar image to Maud esg format
  - [ ] formalize @joelvbernier's function
  - [ ] add GUI exoprt menu option

**Comment by psavery** [comment]
Do we have a function for exporting to Maud ESG format?

**Comment by joelvbernier** [comment]
I do, and I should add that!
