### ISSUE TITLE
Rotation series overlay eta periods not being updated with eta ranges in polar view

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1191]
Another instance of cyclic angle periods not being updated consistently.  Observe on master:
![image](https://user-images.githubusercontent.com/1154130/163488226-91463210-e26d-491f-bde3-e7b6a897ce4c.png)

**Comment by psavery** [comment]
Funny, there's been [a FIXME comment](https://github.com/HEXRD/hexrdgui/blob/18f5ba4a6b062be94ff10e68993b24f4a54c04c6/hexrd/ui/overlays/rotation_series_overlay.py#L44) for a while in the rotation series overlay class that this needs to be fixed.

Should be fixed by #1194.

**Comment by joelvbernier** [comment]
Great!
