### ISSUE TITLE
Do not load all materials on start-up

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1197]
We should change the behavior to only load in one default material, maybe CeO2. This will significantly speed up start-up, as the computations when we first generate the list of materials is expensive.

Then, we can perhaps add something like a button called "Import from Defaults" in the material list editor:

![image](https://user-images.githubusercontent.com/9558430/164130945-00cdeff7-4324-45ca-8a56-263c185e2c04.png)

That will allow the user to select one of the default materials in the HDF5 file and load it into the GUI.

This way, hexrdgui will only start with one material by default, but the user will still retain the abillity to import all of the previous materials through that button.

**Comment by joelvbernier** [comment]
Endorse an Import from defaults option in the add menu.
