### ISSUE TITLE
Omega period and ranges not initially updating from ImageSeries

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1204]
@psavery -- In the rotation series overlays, the omega period ranges don't get updated from the image series via their respective checkboxes unless you toggle off/on.

**Comment by psavery** [comment]
Looks like it is working for me. Let me know if you did something different, or are seeing something different.

https://user-images.githubusercontent.com/9558430/165835157-777e6574-6431-4a73-b5fe-2f771df6f646.mp4

**Comment by psavery** [comment]
Or does the issue occur from using a different path to import the images, such as the image stack dialog?
