### ISSUE TITLE
TypeError on launching GUI on Windows

### ISSUE THREAD

**Issue by TimothyJHLong** [HEXRD/hexrdgui#1222]
When launching the GUI on Windows, I'm receiving the following error:

>  File [conda env path]\lib\site-packages\matplotlib\backends\backend_qt.py:659 in \_\_init\_\_
>    QtWidgets.QToolBar.\_\_init\_\_(self, parent)
>
> TypeError: arguments did not match any overloaded call:
>  QToolBar(str, parent: QWidget = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'
>  QToolBar(parent: QWidget = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'

The full error traceback is:
> Traceback (most recent call last):
> 
>  File ...\git\hexrdgui\hexrd\ui\main_window.py:809 in update_all
>    self.ui.image_tab_widget.load_images()
>
> File ...\git\hexrdgui\hexrd\ui\image_tab_widget.py:120 in load_images
>   self.load_images_untabbed()
>
>  File ...\git\hexrdgui\hexrd\ui\image_tab_widget.py:102 in load_images_untabbed
>    self.allocate_toolbars()
>
>  File ...\git\hexrdgui\hexrd\ui\image_tab_widget.py:158 in allocate_toolbars
>    tb = NavigationToolbar(self.image_canvases[idx], parent, False)
>
>  File ...\git\hexrdgui\hexrd\ui\navigation_toolbar.py:30 in \_\_init\_\_
>    super().\_\_init\_\_(canvas, parent, coordinates)
>
>  File [conda env path]\lib\site-packages\matplotlib\backends\backend_qt.py:659 in \_\_init\_\_
>    QtWidgets.QToolBar.\_\_init\_\_(self, parent)

I'm running this on Windows 10 version 21H1, launching the GUI by running the script: "[conda env path]\Scripts\hexrdgui-script.py" using the IDE Spyder.  I've encountered this error in the current master version (as of 2022/May/18) and version 0.8.15.

The error seems to prevent the image plotting widget from appearing and occurs any time that widget would be updated, such as when loading a configuration file or changing the display mode (i.e. the Raw, Cartesian, Polar selection).

**Comment by TimothyJHLong** [comment]
I've been unable to launch the hexrdgui from the command line on Windows for quite some time now, possibly since the switch to Python 3, so v0.7 onwards.

The output of `conda list pyqt` is:
># Name                    Version         Build                       Channel
>pyqt                         5.12.3            py39hb0d2dfa_4    conda-forge
>pyqt5-sip                 4.19.18          pypi_0                    pypi
>pyqtchart                 5.12              pypi_0                     pypi
>pyqtwebengine       5.12.1            pypi_0                     pypi

Here's output of `conda list` as a text file:
[hexrd3gui conda list.txt](https://github.com/HEXRD/hexrdgui/files/8730392/hexrd3gui.conda.list.txt)

If you're unable to reproduce the issue on Windows I suspect it's a pyqt version issue on my end.

**Comment by psavery** [comment]
We are actually using `pyside2` instead of `pyqt` for the GUI. Some other dependencies may depend on `pyqt`.

I see that some of your packages have come from the defaults channel. Our official support is only for packages on the `conda-forge` channel. Although I am not sure if this would cause the issue.

Could you try running these commands in your base conda environment? This will create a new environment from scratch and try to run hexrdgui, and we can see what happens.

```bash
conda create hexrdgui -c conda-forge python=3.9
conda activate hexrdgui
conda install -c hexrd/label/hexrd-prerelease -c hexrd/label/hexrdgui-prerelease -c conda-forge hexrdgui
hexrdgui
```

Note that conda doesn't always automatically update packages on a fresh install (it uses cached ones if it can find them, and might not check to see if there's an update available online). So this may not use all of the latest packages, but we can give it a try first and see.

**Comment by joelvbernier** [comment]
@TimothyJHLong -- are you running in an Anaconda PowerShell on Windows?  I can confirm on Windows 10 and 11 that @psavery's instructions work.  GUI fires up.

**Comment by TimothyJHLong** [comment]
> @TimothyJHLong -- are you running in an Anaconda PowerShell on Windows? I can confirm on Windows 10 and 11 that @psavery's instructions work. GUI fires up.

I've been running through an Anaconda Prompt, which appears to be distinct from an Anaconda Powershell Prompt.  I tested running the "hexrdgui" command from an Anaconda Powershell Prompt, but it still didn't launch the gui.

Thank you for your help.  The issue is clearly something on my end.
