### ISSUE TITLE
xy file writer

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1232]
Include ability to export polar view line outs (azimuthal integration) as simple `.xy` text files. Can use `np.savetxt` for this with the extension `.xy`

**Comment by psavery** [comment]
I think I can do this at the same time as #1188

[Here](https://github.com/HEXRD/hexrdgui/blob/35f0fab8f32226e9a0bfec2496374b6a4e7fd4a1/hexrd/ui/calibration/polar_plot.py#L93-L137) is the current function in use. The difference with the `.xy` and `.csv` writers, though, will be that they will only write out the lineout (the other formats write out a bunch of other data, too, including the masks, snip background, extent, coordinates, and intensities).

**Comment by saransh13** [comment]
Ok, maybe the writer can pop up an option to select which data to write?
That could give flexibility in include everything or just the tth-intensity
values.

Just the tth-intensity in the .xy format is useful since that is an input
to a number of other analysis programs. Let me know if you think this makes
sense.
