### ISSUE TITLE
Image series import doesn't respect the max number of frames requested

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#1262]
@joelvbernier Will add test case.

**Comment by donald-e-boyce** [comment]
I made a test to check that the imageseries has the correct number of frames according to the parameters in the YAML file defining it. It does, as shown in the tests below. For a test code, I did not have an easy way to write multiframe image files, so I just used existing GE files from the ruby data. So this is not a great test to be automated, but it could be if we get a smaller set of multiframe images.  Here is the test code:  [test_image_files.py.txt](https://github.com/HEXRD/hexrdgui/files/9301011/test_image_files.py.txt).

Here are the results of the run. There are two image files, each with 242 frames, and we usually skip the first two frames. The tests exercise the parameters for skipping frames in the beginning, limiting frames per file, and max total frames.

```
---- test: -----
  number to skip: 0
  max frames per file: 0
  max frames total: 0

  length of imageseries: 484
---- test: -----
  number to skip: 0
  max frames per file: 0
  max frames total: 1000

  length of imageseries: 484
---- test: -----
  number to skip: 0
  max frames per file: 0
  max frames total: 100

  length of imageseries: 100
---- test: -----
  number to skip: 2
  max frames per file: 0
  max frames total: 0

  length of imageseries: 480
---- test: -----
  number to skip: 2
  max frames per file: 10
  max frames total: 0

  length of imageseries: 20
---- test: -----
  number to skip: 2
  max frames per file: 500
  max frames total: 0

  length of imageseries: 480

```
