### ISSUE TITLE
Need a passthrough for FWHM geuss in automatic peak fitting dialog

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1279]
Until we have a better way to estimate this (help appreciated!), we need a widget for the user to be able to specify this in degrees.  It can go with the other fitting options as a ScientificSpinBox.

I have found that it is just too critical a parameter to have a bad initial value.  Also very hard to have a good estimator the works across a wide range of cases, so will likely always need it.  This value must be passed in via the spectrum kwargs as `'fwhm_estimate`' (current default in the `SpectrumModel` is `None`).

**Comment by psavery** [comment]
@joelvbernier So will we have a checkbox for whether to pass `None` or the user-provided value? Or will we just require the user-provided value (no option for `None`)? Also, what should the default value in the widget be?

**Comment by joelvbernier** [comment]
yeah, I suppose a checkbox is best.  `None` as default will fall back to auto-guessing (which can always be improved.  A tooltip can say that an accurate estimate can greatly help fit noisy data.

**Comment by psavery** [comment]
This is now a part of #1275.
