### ISSUE TITLE
Store last loaded image paths somewhere for reference?

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1283]
A user at LLNL just brought this one up.  As far as I can see, only the imageseries import options "remember" the loaded image paths.  Would it be possible to store the loaded image paths from the LLNL Import Tool and File --> Open --> Images somewhere where the user can see them?  Maybe we can provide a pulldown menu in the Raw Image mode panel.

Would be nice to have that info in the state file as well.

**Comment by bnmajor** [comment]
Fixing the LLNL Import Tool to "remember" paths the way all of the other file selection tools do would be very simple and I can do that fix very quickly.

As for remembering recent selections it would be helpful to get a little clarification on exactly what you'd expect here and how it would behave... How many recent files should be remembered? Would this just mean that the import tools would have this drop-down menu option where the last n files are listed and the user could select one? How would this work in the case of multiple file selection? Depending on the needs of this feature request we may want to consider breaking this off into a new task for when we have additional funding.

**Comment by joelvbernier** [comment]
@bnmajor --

I think we only need to remember the most recently loaded image path(s) for now, regardless of how they were loaded (all the ways...).  This is useful for someone analyzing timeseries data so they can keep track of what they are currently looking in session.  We can stuff it in View --> current image path or something...

**Comment by bnmajor** [comment]
@joelvbernier

> I think we only need to remember the most recently loaded image path(s) for now, regardless of how they were loaded (all the ways...). This is useful for someone analyzing timeseries data so they can keep track of what they are currently looking in session. We can stuff it in View --> current image path or something...

Added this feature in #1288. This currently displays the full path but this can be truncated to whatever makes sense if that's too much.
![loaded_images](https://user-images.githubusercontent.com/51238406/191621278-55f4a393-b9e6-4896-b1df-8cc63ca70674.png)


> Would be nice to have that info in the state file as well.

Done in #1288 as well.

> As far as I can see, only the imageseries import options "remember" the loaded image paths. Would it be possible to store the loaded image paths from the LLNL Import Tool and File --> Open --> Images somewhere where the user can see them?

Just to be clear, is what is described above sufficient? I was thinking that this issue originally meant that the selected image directory was being forgotten but that is not the case. Is there some other way that the loaded image paths are being "forgotten" for LLNL?

**Comment by joelvbernier** [comment]
No, there was just no way to see what the loaded files were.

**Comment by bnmajor** [comment]
If you load in images through the Simple Image Series Dialog, LLNL Import Tool, or File>Open>Images whatever you load is remembered and listed in the menu.

**Comment by joelvbernier** [comment]
I think this was fixed in #1288
