### ISSUE TITLE
LLNL import tool is broken in master

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1285]
I just refreshed a python 3.10 dev environment of master in both `hexrd` and `hexrdgui` and I am getting the following exception when I try to use the LLNL Import Tool
```
Traceback (most recent call last):
  File "/Users/bernier2/Documents/GitHub/hexrdgui/hexrd/ui/llnl_import_tool_dialog.py", line 237, in load_images
    if not self.canvas.raw_axes[0].get_autoscale_on():
KeyError: 0
```
This is more critical to the 0.9.0 release than the image path browser @bnmajor -- can you take a look?

**Comment by joelvbernier** [comment]
So @bnmajor it looks like `LLNLImportToolDialog.raw_axes` has been changed from a list to a dict; should any reference to index 0 be converted to `[default]`?  Will that work for the default config *AND* current config (if the user selects that option)?

**Comment by joelvbernier** [comment]
Also, the LLNL Import tool should turn the direct beam mark off.

**Comment by joelvbernier** [comment]
@bnmajor -- the `InteractiveTemplate` class seems to have an old reference [here](https://github.com/HEXRD/hexrdgui/blob/5797c23eea8955ef226dc32c4c98d8d728086d82/hexrd/ui/interactive_template.py#L53) as well.

**Comment by bnmajor** [comment]
@joelvbernier Thanks! I've got a PR up fixing this now, grepping around I can't find any more instances of the raw axes so this should fix the last of them. The beam marker is also turned off now when using the LLNL import tool.
