### ISSUE TITLE
CLI find-orientations error: no omega metadata! (.npz file exported from hexrdgui and python scripts)

### ISSUE THREAD

**Issue by minety** [HEXRD/hexrdgui#1295]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/19909710/192356588-7609f5d1-f3d2-4d9e-95c6-fdad27375d17.png">

Hi,
I have no problem running find-orientations with GUI version.
Recently, we collected some new ff-hedm data from France-SOLEIL where the data format is in HDF5.
I used hexrdgui to export .npz for CLI version on HPC and got the error above, then I tried the following code to write the metadata myself.

```python
import numpy as np
from hexrd import imageseries
from hexrd.imageseries.omega import OmegaWedges

# Inputs
DarkFile = 'dark-75pct-1000f'
npzfile = '/Users/~/Desktop/~/npz/~_15_diff1bis_06_w_omega.npz'
fname = 'hexrd_hdf5_to_npz.yml'
mypath = '/Users/~/Desktop/~/npz'

# Raw image series: directly from imagefiles
imgs = imageseries.open(fname, 'image-files')
print("number of frames: ", len(imgs),
      "\ndtype: ", imgs.dtype,
      "\nshape: ", imgs.shape)

# Input of omega meta data
nf = 3600  #720
omw = OmegaWedges(nf)
omw.addwedge(0, nf*0.01, nf)  # 0.01
imgs.metadata['omega'] = omw.omegas

# Make dark image from first 100 frames
pct = 75
nf_to_use = 1000
dark = imageseries.stats.percentile(imgs, pct, nf_to_use)
np.save(DarkFile, dark)

# Now, apply the processing options
ProcessedIS = imageseries.process.ProcessedImageSeries
ops = [('dark', dark), ('flip', 'h')]
pimgs = ProcessedIS(imgs, ops)

# Save the processed imageseries in HDF5 format
print("writing npz file (may take a while): %s" % npzfile)
imageseries.write(pimgs, npzfile, 'frame-cache', path=mypath, threshold=100, cache_file=npzfile)
```

The hexrd_hdf5_to_npz.yml file is as follows:
```yaml
image-files:
  directory: /Users/~/Desktop/~
  files: ~15_diff1bis_06.hdf5

options:
  empty-frames: 0
  max-frames: 3600

meta:
  panel: ge3
  ostart: 0
  ostop: 360
```
I have checked the .npz file I exported with the above script. The metadata contains omega arrays. But the CLI find-orientation is still not working.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/19909710/192357962-9850ee2a-4ed0-40a4-beb8-f0bf6c472c5c.png">

Could you please give me some suggestions?

Thanks,
Tian

@joelvbernier

**Comment by joelvbernier** [comment]
Tian -- can you send me a google drive (or Box, or Dropbox, etc..) link to the npz in question?

**Comment by joelvbernier** [comment]
Ah -- one thing that seems wrong with your input is your hard-coded delta omega
```
# Input of omega meta data
nf = 3600  #720
omw = OmegaWedges(nf)
omw.addwedge(0, nf*0.01, nf)  # 0.01
imgs.metadata['omega'] = omw.omegas
```
I think you mean 0.1°, not 0.01°, right?  I am assuming your stopping omega is 360, not 36...

You should probaby calculate the delta as `delta_ome = (ostop - ostart)/nf`

Also, what is with all the `'~'` in your path spec?  They all get exampnded to your home directory, so all but the last seem redundant?

**Comment by minety** [comment]
Joel

The dropbox link for my npz and other related yaml files is as follows:
https://www.dropbox.com/sh/x28v0nb4gepywc0/AABCrF9P3JWU9fjbOp4SAL-da?dl=0

The 360 degrees instead of 36 degrees is a good point, I modified it. The "~" in my path is to avoid showing other person's name.

The direct open HDF5 with imageseries.open is great. I don't have to change my raw data path which saves a lot of time.

I just tried find-orientations (CLI) with the new npz file attached, still having the no omega metadata problem.

The yaml file, detector file and material file are also attached in the dropbox folder.

Thanks a lot,
Tian

**Comment by joelvbernier** [comment]
I made a slight modification to the HDF5 imageseries adapter in https://github.com/HEXRD/hexrd/pull/478 that allows for proper handling of single-frame HDF5 images (previously it was only intended to work with 3-d datasets.  Probably doesn't affect your most common use case, but now you know ;-).  Of course, you can still shove whatever you'd like into the `ImageSeries.metadata` after loading your raw as well.
