### ISSUE TITLE
Overlay badness in LLNL Import Tool

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#1302]
@bnmajor I just noticed this one.  For some reason, if you apply "Transform Image" in the LLNL import tool, some strange things happen
1. The overlay is redrawn differently (see extra line in the boundary; are the nan coordinates that separate the outer contour from the hole removed?)
2. If you attempt to use the mouse to do any rotations, the overlay disappears.
3. Rotation by keys works as expected.

This is in the >=0.9.0 release all platforms.  If you can get to this one it would be much appreciated.

![llnl_import_error](https://user-images.githubusercontent.com/1154130/197116527-2bf5a70a-3589-4803-9d94-806bbce01cbd.gif)

**Comment by joelvbernier** [comment]
Same issue as #1300

**Comment by joelvbernier** [comment]
@bnmajor -- new issue uncovered:

Irrespective of whether or not "Add Transform" is used, I noticed a re-initialization error if you cancel the "Position Detector Outline" workflow and re-draw to start again.  Probably a simple fix to make sure the signal upon cancellation triggers re-initialization to default detector values.

![more_LLNL_Imort_bugs](https://user-images.githubusercontent.com/1154130/198363521-9daa20bf-c10b-4714-914b-47398d28baa0.gif)

I can probably fix if you point me in the right direction...

**Comment by psavery** [comment]
@bnmajor I think we changed some things so this should no longer be an issue, is that right?

**Comment by bnmajor** [comment]
@psavery Yes, this is no longer an issue - closing.
