### ISSUE TITLE
Simulated transparent pattern in overlay

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1319]
Add a feature to add a transparent simulated powder diffraction pattern in the azimuthally averaged lineout. Something that looks like the image below.

The powder simulator is already implemented in the `Material` class. It needs to be integrated and an option added in the overlay button. This overlay will also need to have a peak width parameter which changes how broad the shaded peaks are.

Putting it here so we can keep track of this, but this issue is only a medium priority.

![Screen Shot 2023-01-09 at 4 21 49 PM](https://user-images.githubusercontent.com/15834451/211434380-9649a010-a2b8-457e-90f6-89932f8541a4.png)

**Comment by psavery** [comment]
Also add an option to save the lineout image.

**Comment by psavery** [comment]
The function we will call is [here](https://github.com/HEXRD/hexrd/blob/c6f5364d1480168a76696e459e05e1e6321129de/hexrd/material.py#L373).
