### ISSUE TITLE
Automatically build and upload osx-arm64 conda packages

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1338]
I don't know how much work this would be. It looks like GitHub Actions will host osx-arm64 runners later this year, which might be the easiest way to support this.

It may also be possible to cross-compile them. Conda may provide some support for this, but I'm not sure.

For now, we have manually created and uploaded the osx-arm64 conda package for version 0.9.5.

Cross ref: #1336

**Comment by rachelelim** [comment]
It works now. The environment with just hexrd gave this error, but it went away when i told it to update scipy
![image](https://user-images.githubusercontent.com/21162319/220448097-72ce093b-016a-4d0e-87bb-a4091f23f8e3.png)

**Comment by psavery** [comment]
@rachelelim Awesome! I'm glad it works now. And I put a mention of the issue above in the corresponding [hexrd issue](https://github.com/HEXRD/hexrd/issues/499).

**Comment by psavery** [comment]
> I don't know how much work this would be. It looks like GitHub Actions will host osx-arm64 runners later this year, which might be the easiest way to support this.

Even though GitHub actions supports M1 runners now, you have to pay for them. So we are going to cross-compile instead.
