### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1344]
Since hexrdgui is a GUI application, I am thinking we can take some inspiration from Tomviz for this.

For instance, the docs can be primarily instructions, images, and tutorials. See [here](https://tomviz.readthedocs.io/en/latest/visualization/#contour) for an example from Tomviz.

These can be markdown files (similar to [Tomviz as well](https://github.com/OpenChemistry/tomvizdocs/tree/master/docs)) for easy editing.

We can also add `Help` buttons in dialogs throughout the program, that open a web browser to the relevant docs for that dialog. Here is an example from Tomviz. For the Tilt Axis Alignment dialog, there is a `Help` button in the bottom left corner:

![image](https://user-images.githubusercontent.com/9558430/221037891-146d7322-11a4-46ef-b173-56cae458252b.png)

And this button takes you to [this page](https://tomviz.readthedocs.io/en/latest/alignment/#tilt-axis-alignment).

Maybe these docs can be located at `hexrdgui.readthedocs.io`, whereas API docs for hexrd can continue to be located at `hexrd.readthedocs.io`.

Thoughts? @donald-e-boyce @kenygren @shadepa @keara-soloway @rolfverberg @bnmajor

**Comment by bnmajor** [comment]
+1
I personally really like the Tomviz docs and often use them for inspiration when setting up docs on other projects. Also I think that no matter how we approach the docs, `Help` buttons are a must-have.

**Comment by psavery** [comment]
Re-reading through our kickoff notes, I see that Word and PDF were also mentioned as possible formats for the docs. Some of the benefits of using Word are that most people are more familiar with it compared to Markdown, and it's easier to create nice formatting in Word.

But I think one of the biggest benefits of using Markdown is having the `Help` buttons scattered throughout the application that can take you directly to a section in the docs on the web that is relevant for what you are looking at in the application. I'm not sure how easy this would be to do with Word or PDF docs.

We also get some nice benefits from using web-based documentation like sidebars for navigation (see the Tomviz example), a nice search engine, etc.

However, there are tools (like `pandoc`) that can be used to automatically convert from Word documents to Markdown. If someone wanted to write up some documentation in Word (including images), they can send it to me, and I can use pandoc to convert it to a Markdown file. Maybe that is a good solution.

**Comment by psavery** [comment]
An initial implementation of the documentation is now located here: https://hexrdgui.readthedocs.io/en/latest/

It's mostly a skeleton framework.

The repository that hosts those docs is [here](https://github.com/hexrd/hexrdgui-docs). A separate repository was chosen because we will likely have a lot of images, and it is better to not have those in the hexrdgui history (or else the `.git` folder may become very large).

Instructions for contributing to the docs can be found [here](https://hexrdgui.readthedocs.io/en/latest/contributing/).

An example "Help" button that opens a URL to the relevant docs page is in PR #1356.

Any issues with the docs should now be opened [in the docs repo](https://github.com/HEXRD/hexrdgui-docs).
