### ISSUE TITLE
(on mac) menus do not work when GUI first appears

### ISSUE THREAD

**Issue by donald-e-boyce** [HEXRD/hexrdgui#1351]
On MacOS 10.15.7, when I run the GUI and the initial window comes up, none of the menus respond, not even the apple menu on far left. I can do things inside the GUI, such as open windows, change slider values and text values, etc., but the menus still do not work. However, if I click outside the GUI to another window, then return to the GUI, all the menus work.

**Comment by psavery** [comment]
Hmm, this is not good. We will look into it.

**Comment by psavery** [comment]
Don reported that this is fixed by the upgrade to PySide6 (#1476).
