### ISSUE TITLE
add detector panel templates

### ISSUE THREAD

**Issue by donald-e-boyce** [HEXRD/hexrdgui#1352]
It would be nice to be able to insert standard detector sections in the instrument YAML file. In particular, it would be useful to have sections for dexela, manta and GE.  I am thinking of having the options to delete an existing panel or to add a new panel (with choice of type) to the dectectors section of the instrument YAML. We can provide basic templates.

A slight extension for the dexelas would be to transform a single panel dexela to four subpanels; there is a script for that.

On a related note, I tried the LLNL import too just to see what it did. What I am proposing above is simpler actually. And even though I canceled the import, it completely changed my instrument config. I don't think that is a problem, though, because anyone who is actually using the import tool probably has that kind of data.

**Comment by psavery** [comment]
@donald-e-boyce This sounds great!

**Comment by donald-e-boyce** [comment]
Here are some templates for the dexelas. CHESS is using model 2923; see [Dexela Specs](https://resources.perkinelmer.com/lab-solutions/resources/docs/prd_cmos_std_pub_109_rev_1.pdf). 

I zeroed out the translation and tilts, but we may want to make the default y-translation something like -1000 (1 meter), since the negative sign can throw people off and also to make it clear the y-axis is the beam direction for hexrd. According to the spec page, the detector has "14 bit digital output", so that would make the saturation value 16,383, but values in the hexrd examples were either 15,800 or 15,000. I left it as 15,800. 

Also, the script to convert single panel to four subpanels is in the: [hexrd-examples repo](https://github.com/HEXRD/examples/blob/master/NIST_ruby/multiruby_dexelas/include/chunk_dexela.py).

[dexela-2923-detector.yml.txt](https://github.com/HEXRD/hexrdgui/files/10936261/dexela-2923-detector.yml.txt)
[dexela-2923-detector-subpanel.yml.txt](https://github.com/HEXRD/hexrdgui/files/10936262/dexela-2923-detector-subpanel.yml.txt)

**Comment by psavery** [comment]
Hey Don! Thanks for the info and the examples. I am thinking about places to put this in the GUI.

If you go to the `Instrument` settings and click on the `Form View`, there is a section there for editing detectors. See image attached:

![image](https://user-images.githubusercontent.com/9558430/224191994-59fc1b94-d729-4d55-b284-d1cada3f5a80.png)

You can see there is a `+` button to add a detector and a `-` button to remove a detector.

Right now, if you press the `+` button, it just makes a deep copy of the currently selected detector and adds it. Maybe instead, if the user presses the `+` button, a pop-up can appear that asks the user to either select from a list of detector templates (such as the dexelas), or make a deep copy of the current detector?

We can also re-design this UI if you think there is a more intuitive way to present it in the form view.

For the tree view, we might also be able to add some more advanced detector editing. For example, if the user right-clicks on a detector, we could add "Add Detector" and "Remove Detector" to these context menu items:

![example](https://user-images.githubusercontent.com/9558430/224192614-f370e227-a56f-4eca-bfb4-1914d38fd3a8.png)

And then if the user clicks "Add Detector", it could pop up the same dialog that asks the user to either select a template or make a deep copy of the detector they right-clicked.

What are your thoughts?

And about converting a single panel into sub-panels: is this something that might be useful for a variety of detectors (where we may want to make a general option to "split detector into subpanels" or something like that), or is this likely only specific for dexelas? In either case, let me think of some good places to add UI options for doing this (and let me know if you have any thoughts).

**Comment by donald-e-boyce** [comment]
Thanks. I didn't realize that you could copy the detector sections in the form view. I saw the + and - but didn't think anything of it. That's a nice feature.  

I like your suggestion to have the + bring up a menu of detector templates with the option to duplicate the current one.  One variation on that might be to add a "duplicate" button to deep copy the current section,  and then have the + button bring up a menu of templates to insert. 

I don't know what the best way would be. Maybe it would be good to poll a larger group of users.

**Comment by bnmajor** [comment]
@psavery @donald-e-boyce Maybe this feature would also benefit from text instead of symbols? I'm not sure if something like `Create Detector`/`Remove Detector` or `Copy Detector`/`Add Detector`/`Remove Detector` would be too cluttered in the form view but it may make the options more obvious.

**Comment by psavery** [comment]
@donald-e-boyce I just remembered this issue. We should look into it at some point

The APS MPE folks also mentioned that they would really like having detector panel templates as well.

**Comment by psavery** [comment]
We should ship HEXRD with a set of pre-defined detectors, and also allow the users to add their own pre-defined detectors.

**Comment by psavery** [comment]
Fixed by: #1644
