### ISSUE TITLE
Add VISAR view in stereographic projection

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1358]
Add an option for the VISAR view in the stereographic projection view. When the box is checked, then the `polar` and `azimuthal` angles both need to be both `90`. Once this box is checked off or once the user exits this view to any other view, then these angles need to be set back to the original value.

The image below is a mock up of what it should look like.

![Picture1](https://user-images.githubusercontent.com/15834451/226444871-9183df5a-5178-435a-a9dc-798d253a0f58.png)

**Comment by psavery** [comment]
This was fixed in #1482. Now, it displays the VISAR view by default (and there is currently not an option to switch to a non-VISAR view).
