### ISSUE TITLE
Automatically read TARDIS hdf and automatically flip images.

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1363]
TARDIS hdf files store the data in a similar way, ie, XXX/DATA/DATA. It would save clicks if we could just have that read automatically. 

I attached a compressed python method that I use in other code that may be a good starting place. Not all of the if statements are necessary for TARDIS.

[load_nif_im_from_h5.py.zip](https://github.com/HEXRD/hexrdgui/files/11083683/load_nif_im_from_h5.py.zip)

**Comment by saransh13** [comment]
I believe the right flips are 
`IMAGE PLATE 2`: `flip around horizontal`
`IMAGE PLATE 3`: `flip around vertical`
`IMAGE PLATE 4`: `flip around vertical`
The default transforms can only be applied during the `TARDIS import tool` and stay `None` during `PXRDIP`. Although there's also a set recipe for those plates and can be included.

**Comment by bnmajor** [comment]
@akrygier @saransh13 We actually are already doing this for `PXRDIP` I believe, so no stretch to add it to `TARDIS` as well!
