### ISSUE TITLE
round off displayed values in gui

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1365]
The colormap limits and 2theta range text boxes currently include a lot of decimal points (more than 10). Can this be rounded off to 1-2 decimal points?

**Comment by psavery** [comment]
This sounds good. I think probably the best solution is for us to just do some rounding for when these are automatically generated (such as [here](https://github.com/HEXRD/hexrdgui/blob/a21da7f8e00ba1bb120b40c617b2536fb67671e2/hexrd/ui/color_map_editor.py#L162-L175) and [here](https://github.com/HEXRD/hexrdgui/blob/a21da7f8e00ba1bb120b40c617b2536fb67671e2/hexrd/ui/brightness_contrast_editor.py#L186-L192)).

The `ScientificDoubleSpinBox` widgets throughout the program are set up to not display trailing zeros, so rounding the numbers themselves will make it display fewer digits.

**Comment by akrygier** [comment]
Yes, I agree with that.
