### ISSUE TITLE
change how image plates are displayed in "Raw" Image mode tab

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1366]
Currently, the TARDIS image plates are plotted such that most of the available window is not used. Can this be improved? Maybe with tabs or smarter subplot arrangement?

**Comment by bnmajor** [comment]
@akrygier There is an option to view the plots in a tabbed view at the moment - if you look at the `Image Mode` panel on the right side there is a `Tabbed View` box that can be toggled if you'd like to try that out for now!

![tabbed_view](https://user-images.githubusercontent.com/51238406/228238435-39cd0c1b-0a5b-4168-ac82-457f947f1dd6.png)

**Comment by akrygier** [comment]
Ahh, nice. I did not know that was there. 

I wonder if people think this should be default? @saransh13 maybe we can discuss at next TARDIS meeting?
