### ISSUE TITLE
Display (toggle) outlines of masked region

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1373]
We commonly want to clarify that masking has occurred. One way to do this is to draw outlines around the masked regions.

**Comment by saransh13** [comment]
@akrygier another option similar to the IGOR code is to draw outlines around the mask but show the intensities in the 2D dwarped image. But those intensities are not used in computing the azimuthal lineouts. This could also be made as an extra option.

**Comment by psavery** [comment]
@akrygier Note also there is a `View Masks` button in the mask manager dialog, but it only shows them in the raw view (and it doesn't show the data either - just `0` for masked and `1` for not masked. 
![example](https://user-images.githubusercontent.com/9558430/228322976-ccbd192d-7e74-4595-9233-91751d2fba10.png)

**Comment by akrygier** [comment]
Ahh, ok, thanks I did not know about that.  I think it's most important to be able to display in the polar and stereograph views since this is how it is commonly presented at meetings, etc.

@saransh13 suggestion is good, too.
