### ISSUE TITLE
Draw the detector outlines in TARDIS import by default

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1374]
It's an extra click to do this, and I do it every time.

**Comment by saransh13** [comment]
Agreed, will save an extra click.

**Comment by bnmajor** [comment]
Sounds good!

**Comment by akrygier** [comment]
While you're at it, you might consider making the outline and the hole feature separate plots so they don't connect as they do here:

![image](https://user-images.githubusercontent.com/59886900/228294782-243009e2-3f78-459d-ab1f-356f6ee758c4.png)

**Comment by bnmajor** [comment]
@akrygier Are you on the latest version? This was an issue that was cleaned up in the past so I just need to know if this is an older version or if this bug has returned.

**Comment by akrygier** [comment]
Welllll, I thought I was on the latest, but it seems I am several behind (0.9.0 hexrdgui, 0.9.1 hexrd). Sorry about that!

**Comment by bnmajor** [comment]
No problem! If you do see that issue pop up again please open an issue and we'll clean that up. Definitely shouldn't have that line there!
