### ISSUE TITLE
Use grain centroid for rotation series overlay bounding box

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1383]

**Comment by joelvbernier** [comment]
I guess I didn't realize that the centroid wasn't being used currently? It's just a matter of passing it to the simulator.  Ditto for strain.

**Comment by psavery** [comment]
Hmm, if they are the same as the crystal parameters in the GUI, then I think indeed they are already being used:

![image](https://user-images.githubusercontent.com/9558430/230675753-43c79844-725c-447a-983b-9a27472f2bff.png)

The problem might be that we may need to ensure these parameters are updated after something (like HEDM calibration).

**Comment by psavery** [comment]
@joelvbernier It looks like when we modify the grain positions, the `valid_angs` that come out of the `instr.simulate_rotation_series()` do not change, although the `valid_xys` do.

I guess this is because the angles are coming directly out of `xrdutil._filter_hkls_eta_ome()` [here](https://github.com/HEXRD/hexrd/blob/cd08e3f1ea6ec02eecf16af002aba35666a90882/hexrd/instrument.py#L3407-L3410), and that doesn't include any info about the grain positions, whereas the `valid_xys` are coming out of the `xrdutil._project_on_detector_plane()` [here](https://github.com/HEXRD/hexrd/blob/cd08e3f1ea6ec02eecf16af002aba35666a90882/hexrd/instrument.py#L3413-L3419), which does include info about the grain positions.

Is this expected behavior? Do we need to modify those `valid_angs` so that they take into account the grain positions? Maybe that would be by setting them again via `panel.cart_to_angles()` from the xys we get.

**Comment by psavery** [comment]
I'm going to wait for confirmation from @kenygren before closing this.

**Comment by psavery** [comment]
@kenygren confirmed that this was fixed. Closing
