### ISSUE TITLE
LLNL Import Tool Improvements

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1420]
- [x] Default to "Load Configuration" with "Default" checked (since that appears to be the most commonly used setting)
- [x] Skip showing the image load dialog that asks about the transform. This was mainly for pairing images with detectors. It is not needed since you are still able to transform the image after loading (via the `Add Transform` button).
- [x] Disable changing the image mode while the LLNL import tool is active. Currently, if you change the image mode, it breaks the application.
- [x] After saving a TARDIS detector boundary, when the current detector changes (and the user is no longer to make any edits to the current template), clear the selected image and the canvas. Alternatively, if we want to allow the user to fix their template after saving it (which may especially happen for image plate 3, where some extra cropping is done), we may need to add a way for them to modify it without loading the image again.
- [x] Consider making right-click rotate while left-click translates. We may need to keep the buttons, however, to determine what to do for key press events.
- [x] Add text in `Edit Detector Outline` specific for each detector that explains why the bounding box options are or are not grayed out.

**Comment by bnmajor** [comment]
@psavery In regards to the option to right/left click for rotate/translate, what about shift+click instead? So shift+click or shift+arrow would rotate and click/arrows alone would translate?
