### ISSUE TITLE
regenerate the polar view if radius of cylindrical detector is changed. 

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1447]
Changing the `CylindricalDetector.radius` property has no effect on the polar view. Once the radius is changed, the polar view needs to be regenerated for the cylindrical detector. The planar detector are not going to be affected, so they can be ignored for efficiency.

**Comment by psavery** [comment]
I found the source of this issue to be a comparison issue in hexrd. This is fixed in [this commit](https://github.com/HEXRD/hexrd/commit/f2a4b213a7eba10667cd94e6e946d859b7077895) (it's in the `calibration-new` branch, which will hopefully be merged soon).
