### ISSUE TITLE
Display/record image file name

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1460]
It would be very useful to have a record of the filenames of the images accessible either in the Instrument panel (id) and/or displayed somewhere else.

Much of the data looks similar and I am frequently forgetting which shot I am analyzing, etc.

Maybe the save state name can default to the same name but with .h5 extension (or similar since it doesn't work for NIF obviously...)

**Comment by saransh13** [comment]
I was going to request the same feature. I'm starting to encounter this problem too.

**Comment by bnmajor** [comment]
There is an option under `Save>View>Loaded Images`, is this what you are looking for? If so we can certainly move it if it would be more intuitive somewhere else!

![loaded_images](https://github.com/HEXRD/hexrdgui/assets/51238406/ae435b51-35e4-4144-89cc-259a6e1778cb)

**Comment by akrygier** [comment]
ahh ok I did not know about that!

I do think moving it would be worthwhile. For example, Dioptas I think puts in the title bar (where it says "HEXRD" currently) so you can always see it. Not sure how you manage multiple loads though like for TARDIS....

**Comment by bnmajor** [comment]
Yes, we can have instances of multiple images per detector with multiple detectors and that would get.... messy to say the least haha. Maybe instead of having to search through menus (or even in addition to), there could be a file icon somewhere that provides a tooltip on hover with get all this info?

**Comment by akrygier** [comment]
that sounds like a good solution
