### ISSUE TITLE
Undo calibration

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1461]
It would be nice to be able to undo a calibration if the result is worse. This would be useful to be able to apply to all panels as well as per panel.

**Comment by akrygier** [comment]
Or undo changes in case you accidentally type in a wrong number and can't recover the correct one. (I have done this when trying to figure out which panel was which in PXRDIP data in polar view for example).

**Comment by psavery** [comment]
> Or undo changes in case you accidentally type in a wrong number and can't recover the correct one. (I have done this when trying to figure out which panel was which in PXRDIP data in polar view for example).

Under the `Edit` menu, there is a `Reset Instrument Config` option. This should reset your instrument config to whatever it was when you loaded it in (or generated it via the LLNL import tool, I believe - although we should verify). Maybe that will help?

> It would be nice to be able to undo a calibration if the result is worse. This would be useful to be able to apply to all panels as well as per panel.

Yes definitely. We are designing the structureless calibration workflow better with this in mind. It would be good to transfer some of our design back to the other calibration workflows.

**Comment by psavery** [comment]
FYI: I believe this should now be available as of #1686! We have been generalizing calibration workflows to match the structureless calibration, and there is an "Undo" button option as a part of that.
