### ISSUE TITLE
How do I make a new configuration?

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1464]
SACLA, DCS, MEC, EuXFEL, etc.

**Comment by psavery** [comment]
Hi @akrygier! There are a couple of ways you could do it. You could try doing it directly through the GUI. In the instrument config [form view](https://hexrdgui.readthedocs.io/en/latest/configuration/instrument/#form-view), there is a `+` and `-` for adding/removing detectors. You can then change the detector dimensions, pixel sizes, and other options there. In the [slider view](https://hexrdgui.readthedocs.io/en/latest/configuration/instrument/#slider-view), you can move the newly added detectors around to be in approximately the position you want them to be in. When you have set it up how you want it, you should save out the instrument config via `File->Save->Configuration` so you can load it again in the future (note that in the command line, you can run `hexrdgui ./path/to/instrument_config_file.hexrd` to load that instrument config file on startup).

Alternatively, you could take a pre-existing instrument config yaml file and modify it to match your new setup. For example, here is a [TARDIS example](https://github.com/HEXRD/hexrd/blob/master/hexrd/resources/tardis_reference_config.yml). Just add/remove detectors in there and modify their parameters.

**Comment by psavery** [comment]
@akrygier FYI, if you try to use the form view to do this, you should upgrade to the latest prerelease, because we just fixed a few bugs with building new instruments via this method a couple of days ago.

**Comment by akrygier** [comment]
Ah, thank you, that is very helpful!

**Comment by psavery** [comment]
Closing, let me know if you have further issues!
