### ISSUE TITLE
Image series slider doesn't keep sliding

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1490]
If you load in an image series, and you try to move the image series slider, it updates the frame value a single time, but the value does not update anymore, even though you continue to hold left click and move your mouse.

Can we fix the image series slider?

**Comment by bnmajor** [comment]
@psavery Do you have an example? Or am I maybe misunderstanding the issue? It seems to be working for me:

![slider](https://github.com/HEXRD/hexrdgui/assets/51238406/b7496f0b-8266-4ff1-93f5-e8c102b381f2)

**Comment by psavery** [comment]
Actually, it looks like this is only an issue in #1489. Closing (I will raise it there).
