### ISSUE TITLE
Change 2th range during composite calibration point picking

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1497]
Just had an issue pop up while picking points for a calibration in the "Composite (Laue and Powder)" tool.

While picking points, I changed the viewable 2th range in the "Image mode" window. (I was accidentally zoomed in).

When I increased the range, several things broke. First, in the main window (polar view), the box showing the ROI disappeared. Second, the ROI that is displayed in the point picking tool also disappeared. Then, when I clicked ok the calibration ran, but the main image was completely white (again in polar view).

**Comment by psavery** [comment]
Yeah, we should disable the navigation toolbar and the image mode during point picking, unless we decide to support them.

**Comment by akrygier** [comment]
I think what I was doing is not that common so disabling makes sense.

It might be useful to warn that you are zoomed in.
