### ISSUE TITLE
Masks made in polar view are applied flipped up-down in stereograph

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1499]
Here are screen shots. The clear evidence is the straight-through beam (bottom part of northern panel); the corresponding mask is on the bottom panel.

![image](https://github.com/HEXRD/hexrdgui/assets/59886900/681eb457-3847-4cde-9a0c-b9734fedd5a6)

![image](https://github.com/HEXRD/hexrdgui/assets/59886900/84aab79f-9021-4a3f-88c5-45b62ac6da4e)

**Comment by psavery** [comment]
@akrygier I think we have found the issue and will have a fix soon
