### ISSUE TITLE
Threshold mask

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1528]
Currently we have functionality to view pixels over a certain value. We should add functionality to mask pixels based on threshold values.

The user can specify the min and max and any pixels (in the raw view) outside that range would be made a `nan`. The use case right now is images recorded on the Rigaku at LLNL. There are a lot of dead pixels on the detector which have values ~`~1E10` and `+1E10`. Could also be useful for masking Laue spots since they are way brighter than powder spots.

**Comment by bnmajor** [comment]
@saransh13 Right now we have the ability to add a single threshold mask for less than, equal to or greater than. It sounds like we just need to expand this to be able to add one or more threshold masks?
![thresholding](https://github.com/HEXRD/hexrdgui/assets/51238406/b74f2ace-693a-48a2-8dd4-8ebb60f01139)

**Comment by saransh13** [comment]
I think its not a great location for this. After talking with Patrick, we think moving it to `Edit->Masks` and add the ability to set it via a range might be a better option. What do you think?

**Comment by bnmajor** [comment]
That makes sense to me! I believe that this was one of the first masking options added and consequently it does not follow the same pattern all other masking options do... Makes much more sense to bring that in-line with everything else and expand the functionality.

**Comment by psavery** [comment]
Just as a reminder here: the way we handle threshold masks internally is different compared to other kinds of masks.

For other kinds of masks, we store the border of the mask in raw coordinates (like a polygon border/rectangle border). Those masks are treated as masked regions. But since threshold masks are on a pixel-by-pixel basis, we simply store a mask array similar to numpy masked arrays (where the mask array is a boolean array of the same shape as the main array).

Right now, the GUI is set up in a way so that we can only have a single threshold mask at any given time. That might be okay for now.

**Comment by bnmajor** [comment]
@saransh13 If users are able to enter multiple conditions (e.g. greater than 30, less than 4) would it make sense to logical_and the masks together? Have the user select and/or/xor? And if users can input multiple conditions is there a need for multiple threshold masks? Or would a single, combined mask be all that is needed?

**Comment by saransh13** [comment]
I think a single dialog for the threshold mask is sufficient. Unless the threshold is applied to each detector separately, I don't see a reason why multiple threshold masks would be useful. 
Using `np.logical_and` for the high and low conditions is the right way to go. By default the min and max values could be set to `-np.inf` and `np.inf`. Does this answer your question?

**Comment by bnmajor** [comment]
> I think a single dialog for the threshold mask is sufficient. Unless the threshold is applied to each detector separately, I don't see a reason why multiple threshold masks would be useful. Using `np.logical_and` for the high and low conditions is the right way to go. By default the min and max values could be set to `-np.inf` and `np.inf`. Does this answer your question?

Yup, thanks!
