### ISSUE TITLE
Mask with nans in raw view

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#1555]
We should mask with NaN values [instead of 0](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/hexrd_config.py#L892) in the raw view to keep it consistent with the other views.

**Comment by bnmajor** [comment]
@psavery Is there a reason that we don't currently use NaNs? Or any reason not to?

**Comment by psavery** [comment]
I don't immediately know of a reason. We can change it if needed!
