### ISSUE TITLE
Ability to add a constant background to the azimuthal overlay

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1563]
Sometimes the baseline of the azimuthal integration is above zero and using the azimuthal overlay doesn't look very nice. Can we add an option to add a constant offset to the simulated values so the entire plot shifts up (or down if the offset is negative)?

**Comment by bnmajor** [comment]
@saransh13 My thinking is that this option would be remembered in a state file but not between sessions, is that correct?

**Comment by saransh13** [comment]
Yes, that’s sounds correct.
