### ISSUE TITLE
Calibration point picker issue 2

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1567]
When I want to cycle through the active reflection/detector click in the "Composite" calibration mode, sometimes I double click twice or accidentally double click, which causes the picker to go past the reflection/detector I would like. Is there a way to go backwards? If not can that be added?

**Comment by psavery** [comment]
If you right-click, it moves on to the next reflection/detector, and there is currently not a way to go back to the previous reflection/detector. This is something we should add!

**Comment by saransh13** [comment]
Yes, agreed. The process is tedious and prone to mistakes.
