### ISSUE TITLE
Toggle image plate boundary lines in polar and strereographic projections

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1568]
Yellow/brown lines in image:

<img width="754" alt="image" src="https://github.com/HEXRD/hexrdgui/assets/59886900/ad5536a8-c91f-47fd-98a0-feb21f05b88c">

**Comment by psavery** [comment]
Hi Andy! Actually, there is a toggle for this. In the menu bar at the top of the application, click "View"->"Show Detector Borders". That should toggle it on or off. It is located there because it is applied to all views.

**Comment by psavery** [comment]
I think this is resolved - feel free to reopen if not.
