### ISSUE TITLE
Add a set of pre-configured instruments that can be loaded

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#1586]
We should add somewhere in HEXRDGUI the option to load pre-configured instruments (such as "Dual Dexelas").

We can ship HEXRD with a set of these pre-configured instruments, and allow the user to save their own pre-configured instruments to this list. So the users may need a list editor (look at the [materials list editor](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/material_list_editor.py) for inspiration).

**Comment by bnmajor** [comment]
I think the only place this really makes sense is in the file menu somewhere... Any opinions on this just being a new option in the `Open` menu?
![menu_idea](https://github.com/HEXRD/hexrdgui/assets/51238406/de280830-d2d6-4a49-b593-40330f235096)

**Comment by psavery** [comment]
Can you make an additional drop-down menu for "Configuration"? We can have two options: "File" and "Preconfigured".

And actually, Kelly and I discussed it, and we want to change "Configuration" in the menu item to be "Instrument" instead. This is for both "Open"->"Configuration" and "Save"->"Configuration" (both will be "Instrument"). Could you do that as a part of the PR also?

**Comment by bnmajor** [comment]
Sounds good!
![preconifg_instrument_menu](https://github.com/HEXRD/hexrdgui/assets/51238406/6f33ae3f-3735-461d-9c8c-3be41901b735)

**Comment by bnmajor** [comment]
Should we keep `Preconfigured` and offer the same simple dialog that the detector templates provide? Or should we dynamically update this menu with the available preconfigured instrument files (like the recents menu)?

**Comment by psavery** [comment]
I think we can do the same kind of thing that the detector templates do.
