### ISSUE TITLE
Error window bigger than screen, can't be closed

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1595]
I was doing a powder/laue calibration, using the automatic peak finder.  It failed due to too narrow 2 theta range (I think). When it failed an error window came up that I cannot close or ignore.

![image](https://github.com/HEXRD/hexrdgui/assets/59886900/35b436f2-630f-42fd-9ab0-78ce48ceb378)

**Comment by akrygier** [comment]
This is the larger than normal image plate, if that matters...

**Comment by saransh13** [comment]
I found the same problem. Hit `return` or `Enter` to close the window if you encounter this again. We'll work on a fix in the meantime.

**Comment by psavery** [comment]
I think the easiest solution is to only put the final line of the error message in the message box, but keep the whole error message in the messages widget and terminal. I will do that.
