### ISSUE TITLE
Change label for line out

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1598]
Change `Azimuthal Integration` to `Azimuthal average`

<img width="744" alt="Screenshot 2023-10-24 at 10 44 21 AM" src="https://github.com/HEXRD/hexrdgui/assets/15834451/eb8823fe-e3c7-40b2-930f-068b77eba699">

**Comment by psavery** [comment]
So the y value is actually `Azimuthal Average`?

**Comment by saransh13** [comment]
Yes, I think so. We divided by the number of non-NaN pixels in the azimuth,
correct?

**Comment by psavery** [comment]
Yes that's right! See [here](https://github.com/HEXRD/hexrdgui/blob/05b53ce9d132b6d08c1141f7f75cc7ccca830fed/hexrdgui/image_canvas.py#L1126). I'll fix the label.
