### ISSUE TITLE
Issue with powder calibration/PXRDIP

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1635]
I ran a composite calibration and the position values are displaying as non-physical. I don't know if it's related, but the angles are also not refining.

(none of the refinements are active in the screenshot, but they were active when I ran the calibration)

![image](https://github.com/HEXRD/hexrdgui/assets/59886900/7a1ec3bf-d7c6-4ce8-883f-782b4c66224b)

**Comment by psavery** [comment]
@saransh13 maybe you can take a look at this?

**Comment by saransh13** [comment]
Do you mind sharing the state file? The angles look pretty out of whack for a "normal" PXRDIP setup.

**Comment by saransh13** [comment]
@akrygier is this still an issue?

**Comment by saransh13** [comment]
@akrygier I'm guessing something went wrong in the refinement and there is no underlying bug. Closing this for now, but feel free to reopen if this problem persists.
