### ISSUE TITLE
Framecache Mutliprocessor Writing Issue

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrdgui#1652]
I do not think the multiprocessor mapping function in imageseries framecache writing option is properly waiting for all processes to finish the operation that generates the sparse matrices from the data.

We are trying to write frame caches from raw-image data with 3600 frames, however the output sparse matrices only have three frames. When I modified the code to run sequentially on a single processor, everything was able to work. I looked online and there is conflicting information regarding the implementation of the thread executors as to whether it waits for all processes to finish.

**Comment by darrencpagan** [comment]
I am closing this because this is more appropriate for hexrd rather than hexrdgui.

**Comment by psavery** [comment]
I was actually in the process of asking that :slightly_smiling_face:
