### ISSUE TITLE
HEXRD GUI unable to recognize multiple frames in .ge5 FF-HEDM file collected at the APS; what setting to change?

### ISSUE THREAD

**Issue by StopkaKris** [HEXRD/hexrdgui#1661]
Hello,

I am using HEXRD GUI to visualize far-field high energy x-ray diffraction microscopy (FF-HEDM) data collected at the Advanced Photon Source (APS) in 2022. The data was collected using a single GE detector with the .ge5 extension. Whenever I load in the dark file and image stack (that contains 1440 frames), I only see the option to view this as a single frame (please see screenshot below, "Total Frames" = 1).

![HEXRD_screenshot](https://github.com/HEXRD/hexrdgui/assets/74416866/d2fd50d3-1a92-4c0f-8512-38342fdfed04)
This is the version I have installed:
![HEXRD_version](https://github.com/HEXRD/hexrdgui/assets/74416866/22dd070e-f9ed-464a-9fa3-235d5a072319)

Here is a screenshot of the view at the APS beamline end station, showing a version where I can step through the frames.

![HEXRD_screenshot_at_APS](https://github.com/HEXRD/hexrdgui/assets/74416866/ff5b8166-7c04-4a6e-ba61-269049b1c077)

What do I need to change to view the .ge5 files, such that the GUI does not assume there is only a single frame? Thank you in advance for your help.

Best regards,
Krzysztof Stopka

**Comment by psavery** [comment]
Hi @StopkaKris! Thanks for posting this issue!

We use [fabio](https://github.com/silx-kit/fabio) for loading image files such as `ge`. We also use it to determine the number of frames in the file. I wonder if it might be an issue with fabio reading `ge5` files?

If you are able to share the data with me (or any dataset where the issue occurs), I would be able to identify the issue very quickly (including whether it is an issue with HEXRDGUI or fabio)! My email is patrick.avery@kitware.com

**Comment by psavery** [comment]
Here is one thing we could also try. Can you try loading the file with fabio and see if it identifies the number of frames correctly?

```python
import fabio

# FIX THIS
filename = 'FILE_NAME'

img = fabio.open(filename)
print(img.nframes)
```

**Comment by StopkaKris** [comment]
Hi Patrick,

Thank you for the quick response! Indeed, fabio only detects a single image using the code you shared above. I can send the file but it is several GB in size, so I'm not sure what would be the most efficient way to send it.

Best regards,
Krzysztof Stopka

**Comment by psavery** [comment]
Hmm. Maybe we should post an issue on fabio's github page about ge5 files, then?

**Comment by StopkaKris** [comment]
Perhaps... but there must be a way to modify something about HEXRD to be able to read these files, since it is possible at the APS without any modifications to the .ge5 files (that I know of). Maybe it means loading in a certain version of fabio for HEXRD? I will ping other prominent users of HEXRD and the APS to see if they have a "quick fix" for this.

**Comment by psavery** [comment]
@StopkaKris I will also ask around.

**Comment by donald-e-boyce** [comment]
You might try the "raw-image" format. That is for users with custom formats, but I found an example using GE to test it.  The format takes a YAML file describing the data format.  For the GE, here it is. Change the filename of course.

```
#
# YAML example for raw image
#
# For scalar definition:
#   "type": i -> int, f -> float, d -> double, b -> bool
#    "bytes" and "signed" are only for int types
#    "bytes": 1, 2, 4, or 8
#    "signed": true | false
#    "endian": use sys.byteorder to determine value for local system
#
filename: RUBY_4537.ge
shape: 2048 2048
skip: 8192
scalar:
  type: i
  bytes: 2
  signed: false
  endian: little
```

Then you can load it in hexrd like this. I'm not sure whether hexrdGUI reads raw-image format, but you threshold and make a frame cache if need be.

```
"""Test raw image reader"""
import sys

import numpy as np

from hexrd import imageseries
# from hexrd.imageseries import save
# from hexrd.imageseries import stats
# from hexrd.imageseries.process import ProcessedImageSeries as Process


fname = "ge.yaml"

ims = imageseries.open(fname, "raw-image")


def print_info(ims):

    print(
        "Imageseries info:\n",
        "dtype: ", ims.dtype, "\n",
        "length: ", len(ims), "\n",
        "shape: ", ims.shape, "\n",
    )


def main(dframes, thresh):
    print_info(ims)


if __name__ == "__main__":
    main()
```

**Comment by psavery** [comment]
Hmm... yeah if you used a raw format, you could perform sparsing to make a frame cache and then load that into the GUI.

**Comment by StopkaKris** [comment]
Thank you for the advice! I will look into a wrapper to make this fix as versatile as possible. As another note, I dug up another FF-HEDM file collected at the APS a few years ago with the ".ge3" extension instead of the ".ge5" extension. The GUI correctly identified the number of frames in the .ge3 file, however, the spots that were visualized looked strange. So regardless, some type of universal wrapper to be able to point at APS .ge files will be useful.

I'll be sure to post an update when appropriate.

**Comment by psavery** [comment]
Sounds good. We've been completely relying on [fabio](https://github.com/silx-kit/fabio) for this, since they usually handle these types of file formats. I'm sure they would be interested in either fixing the ge format or supporting new formats.

Here is that alternative I was mentioning earlier, for converting to a frame-cache first. This will also sparsify your data, in case you know a good noise threshold and you want to significantly reduce its size.

Your yaml file (you need to know all details about your data, including its type and how many bytes to skip at the beginning). This is `raw_yaml.yml`.

```yaml
filename : 'file.ge5'
scalar :
    type : 'i'
    bytes : 4
    endian : 'little'
    signed : True

shape : '1679 1475'

skip : 8192
```

A python script to create the frame cache:

```python
import numpy as np

from hexrd import imageseries
from hexrd.imageseries.omega import OmegaImageSeries

filename = 'raw_yaml.yml'
nframes = 1440
threshold = 100
omegas1 = np.linspace(0, 359.9, nframes)
omegas2 = np.linspace(0.1, 360, nframes)
omegas = np.vstack((omegas1, omegas2)).T

ims = imageseries.open(filename, format="raw-image")

ims.metadata.update({'omega': omegas})

oims = OmegaImageSeries(ims)

imageseries.write(oims, "dummy", 'frame-cache',
                  style="npz",
                  threshold=threshold,
                  cache_file='frame_cache.npz')
```

You'd have to do this once for each detector. Then you can load the `.npz` files into HEXRDGUI.

**Comment by psavery** [comment]
To follow up here, the ge5 is apparently an `edf` format, and `fabio` does have an [edf reader](https://github.com/silx-kit/fabio/blob/main/src/fabio/edfimage.py).

`fabio` is actually identifying this as an EDF file and reading it. However, the format is set up a little differently than fabio expects (`fabio` expects a header before every frame, but this file only contains a single header at the beginning). This results in `fabio` only reading in a single frame. And that is why we are not interpreting this as an imageseries. 

I'm in [some discussion](https://github.com/silx-kit/fabio/issues/553) about this. Hopefully we can figure out a way to resolve this.

**Comment by psavery** [comment]
I believe this is fixed now... feel free to reopen otherwise.
