### ISSUE TITLE
Masking boundaries not always correct

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#1681]
Hand-drawn (polygon) masks are occasionally connected when they should not be. When distortion is applied some masks are duplicated/triplicated or just have points connected incorrectly. Masking intensity values appears correct though so the issue appears to be limited to how we are drawing the polygons.

**Comment by saransh13** [comment]
#1693 should have fixed most of it. Closing for now, but feel free to reopen if there are any more issues.
