### ISSUE TITLE
Eiger Mask Propagated Incorrectly to Polar view

### ISSUE THREAD

**Issue by kenygren** [HEXRD/hexrdgui#1684]
<img width="634" alt="Screenshot 2024-04-03 at 5 09 23 PM" src="https://github.com/HEXRD/hexrdgui/assets/40276151/58776868-4f53-47fc-89eb-5c92ce695bd2">
The blue image is the eiger mask - you can see that the edges of the pixel are high intensity still and something about the mask is being applied incorrectly.

**Comment by psavery** [comment]
@kenygren I actually already have a PR up to fix this. It's #1675

Let me see if we can go ahead and get that merged...

**Comment by kenygren** [comment]
Ahh - I tried to skim to see but missed it - apologies

Kelly Elizabeth Nygren, PhD
Cornell High Energy Synchrotron Source
***@***.***
________________________________

**Comment by psavery** [comment]
It's okay! I just merged the PR, and it should be fixed soon!
