### ISSUE TITLE
Intensities not syncing after B&C adjustment

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#1690]
Steps:
1. Started the structureless calibration in logs-log-sqrt intensity scaling
2. Tried to edit points in two-click mode
3. Intensity in the zoom-in box was using scaling None instead of the log-log-sqrt

Example image below

![Screenshot 2024-04-18 at 11 28 03 AM](https://github.com/HEXRD/hexrdgui/assets/15834451/318dd72b-0705-4fcb-a9ac-8ebbabcf58a7)

**Comment by psavery** [comment]
This should be fixed in #1693
