### ISSUE TITLE
Feature Request: Save a grains.out from the indexing step before fit-grains

### ISSUE THREAD

**Issue by gustafsonsven** [HEXRD/hexrdgui#1716]
Hi all,

This one is a feature request.  Would it be possible to have an option to save an unfit grains.out from the indexing step before going into fitting?  The CLI drops an accepted orientations file (I think?  Maybe it now drops a grains.out) - perhaps it should also drop a grains.out.  

Thoughts?

Thanks - Sven

**Comment by psavery** [comment]
I think if you run `hexrd find-orientations` in the CLI, it does drop an unfit grains.out file.

Maybe we should add a button to save the grains table in the "Indexing Results Dialog" or in the "Fit Grain Options" dialog? Or both?

**Comment by gustafsonsven** [comment]
I agree - saving a unfit grains.out and grains.npz is ideal.  I think a button in the "Indexing Results Dialog" would be ideal.  I don't see a strong reason to not add it to the "Fit Grains Options" dialog besides clutter on that page.
