### ISSUE TITLE
Add constraints to Composite Calibration

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1739]
The constraints on the structureless calibration are helpful. It would be great to add those to the Composite calibration tool as well. I have data where there is only 1 line visible and it is finding some very obviously incorrect solutions.

**Comment by psavery** [comment]
@akrygier We do have constraints on the composite calibration. Can you make sure you are using the latest hexrdgui?

**Comment by psavery** [comment]
Resolved!
