### ISSUE TITLE
Undo calibration after composition calibration

### ISSUE THREAD

**Issue by akrygier** [HEXRD/hexrdgui#1740]
Can we also add the "undo" option to the Composite calibration tool?

**Comment by akrygier** [comment]
hmmm it seems I was using 1.0. Sorry for the confusion!

However, after updating, I am getting an error "Exception: Invalid engineering constraint: PXRDIP" when I try to do any calibrations...

**Comment by psavery** [comment]
Hmm, is that on the latest release?

I did just try a pxrdip structureless calibration on the prerelease, and it worked.

Are you installing from conda, or using a DMG/ZIP? If you are installing from conda, you might want to try installing the prerelease.

Let me send you an email and we can try to debug the issue...

**Comment by akrygier** [comment]
I used conda update -c hexrd -c conda-forge hexrd hexrdgui

**Comment by akrygier** [comment]
![image](https://github.com/user-attachments/assets/0eb280cc-1cab-463c-86ba-f01f468db8e7)

**Comment by psavery** [comment]
Try the prerelease:

```
conda update -c hexrd/label/prerelease -c conda-forge hexrd hexrdgui
```

**Comment by psavery** [comment]
Resolved!
