### ISSUE TITLE
Add dock icon

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#188]
This is probably not urgent, but it might be nice to add a dock icon at some point. The current one on Ubuntu looks like this.

![Screenshot from 2019-10-18 10-35-08](https://user-images.githubusercontent.com/9558430/67103492-3ac53500-f193-11e9-814a-998bb3be5163.png)

**Comment by psavery** [comment]
This might be nice to have for the packaging. I think we could add most kinds of image files, including `.png` or `.ico`.

**Comment by joelvbernier** [comment]
I'll try to come up with something flashy -- must be square, I assume?

**Comment by joelvbernier** [comment]
Try this:

![hexrd](https://user-images.githubusercontent.com/1154130/75061719-22915980-5496-11ea-8e67-f52cddcf4150.png)

**Comment by psavery** [comment]
@joelvbernier Cool :slightly_smiling_face: 

I'll give it a try.

**Comment by joelvbernier** [comment]
Original artwork credit to @donald-e-boyce 

You will close this out once done @psavery ?

**Comment by psavery** [comment]
@joelvbernier Yep! Will do.

**Comment by psavery** [comment]
So, I found that the `.ico` format seemed to work better for the icon. I hope it's cross-platform.

I converted it to `.ico` with imagemagick via `convert -resize 256X256 hexrd.png hexrd.ico`.
