### ISSUE TITLE
Load data interface doesn't allow for different detector-specific options

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrdgui#223]
In general the image transforms and dark mode options for each detector can be different.  The current interface doesn't allow for this.

**Comment by joelvbernier** [comment]
PS -- I submitted this logged in as Darren.

**Comment by cryos** [comment]
Is there a real example we can work on where there are different detectors? It will complicate the code, and we will have to look at where we made these assumptions but I am sure we can work to generalize things.

**Comment by cryos** [comment]
This is working now.
