### ISSUE TITLE
Use plane data exclusions for ring selections

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#237]
Have the ring selections in the materials panel use and be synced up with the plane data exclusions. This makes it so that ring selection also affects the rings used in calibration.

**Comment by psavery** [comment]
To do: make sure the tth ranges get set on the material's plane data.

**Comment by psavery** [comment]
@joelvbernier @cryos 
So, I just realized from the code, that the plane data's `tThWidth` does get set, but all of the materials' `tThWidth`'s are forced to be the same, and they are set based upon what is in the "Show Ranges" spinbox (0.125 degrees by default).

This also means that the loaded materials' tthwidth do not get preserved, but get forced to be 0.125 degrees.

Maybe we want each material to have it's own `tThWidth`, and use that spin box to set the `tThWidth` for each material, rather than forcing all materials to have the same?

**Comment by psavery** [comment]
I allowed each material to have it's own `tThWidth` in #262. I think this should fix any issues we were facing.

**Comment by joelvbernier** [comment]
There is also the minor issue in the GUI that the number is not ±, but the full width.  We should update the formatting in the spin controller (or have it display half the tThWidth value with the ±).

When instantiating an material object, the tThWidth is set to None; perhaps having a default value of ±0.125° is reasonable.

**Comment by psavery** [comment]
@joelvbernier  I modified this in #262, which is now merged.

Here's what it looks like now: 
![Screenshot from 2020-02-21 15-44-19](https://user-images.githubusercontent.com/9558430/75070367-0e168680-54c1-11ea-8ca0-1efe6a5677b3.png)

So I removed the ± and renamed it to "width".
