### ISSUE TITLE
Add progress updates to some of the progress bars

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#239]
I am not sure which ones we should target. Maybe @joelvbernier or @cryos can specify?

Here is a probable strategy that we can follow for doing this:
1. Pass in a progress function to the [call in AsyncWorker](https://github.com/HEXRD/hexrdgui/blob/c53dc0d19819f156edc609eb6356b70e4a052442/hexrd/ui/async_worker.py#L71). This function will take an integer between 0 and 100, which indicates the progress.
2. Accept the progress function as an argument in the functions that get called asynchronously, such as [this one](https://github.com/HEXRD/hexrdgui/blob/c53dc0d19819f156edc609eb6356b70e4a052442/hexrd/ui/calibration/powder_calibration.py#L267). And call the function with progress updates.
3. Hook up the [AsyncWorker.progress](https://github.com/HEXRD/hexrdgui/blob/c53dc0d19819f156edc609eb6356b70e4a052442/hexrd/ui/async_worker.py#L32) signal to the Qt progress bar somewhere around [here](https://github.com/HEXRD/hexrdgui/blob/c53dc0d19819f156edc609eb6356b70e4a052442/hexrd/ui/main_window.py#L468) using [QProgressBar.setValue()](https://doc.qt.io/qt-5/qprogressbar.html#value-prop).

I think this should work. Might need to change a couple of things in the `AsyncWorker` class. I think [this section](https://github.com/HEXRD/hexrdgui/blob/c53dc0d19819f156edc609eb6356b70e4a052442/hexrd/ui/async_worker.py#L59-L61) might not be right.

**Comment by cryos** [comment]
Our main goal is to have updates for the aggregation functions - they can take five minutes on a typical data set. We thought the async worker could call a function that does perhaps 1/50th of the work, returns, we update the progress bar, and then call to do 2/50 until complete.

**Comment by cryos** [comment]
To be clear, the plan is for @donald-e-boyce to add some entry points where we can call them multiple times, and have a predictable path for updates to the user interface. We think maximum will be the most useful, and then we will look at adding support for the others. We just want to update the progress bar, and were not thinking about providing a view of partial data, i.e. 20% done max etc.

**Comment by donald-e-boyce** [comment]
I'll finish that soon.

**Comment by donald-e-boyce** [comment]
I put in the changes for the median function. That should give you
something to try out. Meanwhile, I'll set up the chunking for other
functions, such as average, max and percentile.
