### ISSUE TITLE
Export polar image data to HDF5 file

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#241]
Add an option to export the numpy array data of the polar images to an HDF5 file. We can also write out the axis values (intensity and 2-theta) to the file.

**Comment by joelvbernier** [comment]
all of these attributes are hanging off of the PolarView class.

**Comment by psavery** [comment]
@joelvbernier Actually, I just realized that "Export"->"Polar Plot" exports the polar image data as npz, with all of these keys:
```
tth_coordinates
eta_coordinates
intensities
extent
```

Do we want to modify this menu item to export HDF5 instead of npz? Or, make it so that this menu item can export to both NPZ and HDF5? Or just leave the NPZ exporter and skip the HDF5 export?

**Comment by joelvbernier** [comment]
Maybe add the HDF5 output as an option -- for generality's sake?

I have a little recursive function for unwrapping a dict (of dicts) to HDF5 if that is useful to you.

**Comment by psavery** [comment]
@joelvbernier Yeah I think adding an HDF5 option sounds good. 

I think that one option we might be able to do is to have one menu item "Export->Polar Plot", but if the user names the file with a ".h5" extension, write it out as HDF5, and for a ".npz" extension, write it out as npz.
