### ISSUE TITLE
Keep un-aggregated images in memory

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#243]
Currently, the un-aggregated images appear to be over-written by the aggregated images. Keep the un-aggregated images in memory so they can be viewed and/or saved.

**Comment by bnmajor** [comment]
#257 attempts to solve this issue by remembering the un-aggregated images and checking for them before saving. This currently only handles saving, but could be applied to viewing the images as well. Aggregation can sometimes take quite a while, so if toggling between aggregation states is a possible use case this could save time.

**Comment by bnmajor** [comment]
Fixed in #257
