### ISSUE TITLE
Fix overlays that extend outside the borders

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#245]
If the overlays extend beyond the borders of the image, they end up looking like this:

![overlays](https://user-images.githubusercontent.com/9558430/73689361-13d83380-469c-11ea-8196-c64efe34534c.png)

They need to not flatten on the edges.

**Comment by cryos** [comment]
@joelvbernier was planning to use NaNs to cause a break in the lines where they hit the edges

**Comment by psavery** [comment]
Yeah, that makes sense.

**Comment by joelvbernier** [comment]
I'll try to get to the draw_rings command today

**Comment by joelvbernier** [comment]
Bump on this -- looks like we have a path forward on this in general, and the related issue #309. Awaiting the PR merging my overlay classes, which should be live today after our call.
