### ISSUE TITLE
auto-compute initial polarview pixel sized based on instrument config

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#252]
Given the large variation in detector resolutions we deal with, I'd like to use the current instrument config to auto generate starting values for the polarview pixel sizes (tth, eta).  The code snippet below calculates the min, median, and max angular pixel sizes over the whole instrument.  For lack of anything better to try first, let's use the median as the 'default' starting resolution.  We can probably do something similar for the cartesian mode as well.  This would prevents it from rendering at an unreasonably high resolution by default.

```
    # next find the median angular resolution on the instrument
    # to use for interpolation
    ang_px_all = []
    for k, v in instr.detectors.items():
        X, Y = np.meshgrid(v.col_pixel_vec, v.row_pixel_vec)
        ang_px_all.append(
            v.angularPixelSize(np.vstack([X.flatten(), Y.flatten()]).T)
        )
    ang_px_all = np.vstack(ang_px_all)
    min_px = np.degrees(np.min(ang_px_all, axis=0))
    med_px = np.degrees(np.median(ang_px_all, axis=0))
    max_px = np.degrees(np.max(ang_px_all, axis=0))
    pv_pixel_size = med_px
```

**Comment by psavery** [comment]
This sounds good. However, I should note that it looks like this code takes ~13 seconds to run on my desktop with our GE example (see image below). 

And for reference: our default (tth, eta) resolutions are (0.05, 0.2) degrees. This function produces (tth, eta) resolutions of (0.004, 0.028) degrees for the example below.

![image](https://user-images.githubusercontent.com/9558430/74277095-eb2beb80-4ce4-11ea-9223-d877282e3eb7.png)

**Comment by joelvbernier** [comment]
Hmmm...  good point.  Maybe we should 10x median?  Or some scaling of the max pixel size...  But yes, I agree that is too slow.  Not sure if there are many ways to speed the calc up internally -- could multiprocess it over the list of multiple detectors if it isn't already.

**Comment by psavery** [comment]
Yeah, it's currently doing it all in one thread. Multiprocessing might be an option.

Also, I wonder if a random sampling might work?

**Comment by joelvbernier** [comment]
Patrick, how about we set the defaults to 100x the median?  That way it will render fast for the initial view.  If it looks too chunky, then maybe we relax to 10.  That should be generally applicable.

**Comment by donald-e-boyce** [comment]
I'm starting to think average might be a better choice than median for
estimating the background. I noticed that the median image for the frame
cache (multiruby) that Patrick sent me is zero identically, while average
is not. It appears that what few peaks there are only show up on a handful
of frames, so the median would be zero. That data is probably already
thresholded. I think we should look more deeply into the question of how
best to estimate the  background.

**Comment by joelvbernier** [comment]
@donald-e-boyce this is for pixel size, not intensity.  On that note, @psavery we can also look for the max and do a scaling from there to "reasonable" numbers rather than the median.

**Comment by cjh1** [comment]
@psavery Are the initial changes for this pushed in a PR?
