### ISSUE TITLE
Edit angles and edit ims are actions with no connections

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#254]
I just noticed that, in the main window, there are a couple of actions (`action_edit_ims` and `action_edit_angles`), that are being enabled/disabled in certain parts of the code ([here](https://github.com/HEXRD/hexrdgui/blob/ac4c9331e45008e184bfe08a4ee44c6dd6bf627a/hexrd/ui/main_window.py#L225-L226), for instance), but it looks like they aren't connected to anything.

Were these features removed, and the actions accidentally left over? If so, we might should remove the actions.

**Comment by bnmajor** [comment]
Yes, these actions are from old, now removed features. #255 removes this dead code.

**Comment by psavery** [comment]
Fixed by #255
