### ISSUE TITLE
Perform transformations on raw images

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#264]
Often at least one detector will need to be rotated when loading raw images, allow for transformations on load.

**Comment by bnmajor** [comment]
It was mentioned in the meeting last week that it should be possible to transform raw images as well as an `ImageSeries`. This should all be possible through the load panel, as I believe that the intention was to eventually altogether remove the `File > Open > Images` menu option (although this may very well have changed).

@joelvbernier I am currently able to load `.tiff` files with the panel, and therefore perform transformations on them that way. Were you looking for this as an additional feature because you want to keep loading raw images separate from the load panel? Or are you looking for different functionality in the panel when loading raw images?

**Comment by bnmajor** [comment]
As discussed in #283 and fixed in #286, we will continue to use both menu and load panel loading options, so this feature is still needed.

**Comment by cjh1** [comment]
@bnmajor Is this now fixed? If so can we close this?

**Comment by bnmajor** [comment]
Yes, I believe #290 solved this
