### ISSUE TITLE
Loss of focus when editing detector name in form view

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#285]
You only seem to be able to type a single character and then the field loses focus. This makes editing difficult.

**Comment by cjh1** [comment]
In fact is also seems that when you add a new detector a edit the name is applied the update to the wrong detector.

**Comment by cjh1** [comment]
We should try to fix this before the next release.

**Comment by psavery** [comment]
I think an easy fix for this would be to turn off keyboard tracking for that line edit. We probably don't want the detectors re-loading anyways, until the user finishes typing.

**Comment by psavery** [comment]
Or, rather, it should update when the `editingFinished` signal gets emitted. I will try to add this.

**Comment by psavery** [comment]
But yeah, I see that other problem too. Will try to fix that also.
