### ISSUE TITLE
Azimuthal integration axes not auto-zooming in 0.7.1

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#295]
I just noticed this on a fresh build from master on Mac OS (will update for Linux).  The azimuthal integration axes are getting `ylim = (0, 1)` and not auto zooming.  The result is that you can't see the line plot.
![Screen Shot 2020-03-19 at 4 29 54 PM](https://user-images.githubusercontent.com/1154130/77123988-df77c700-69fe-11ea-9fbc-eeac8bb8f59e.png)

**Comment by psavery** [comment]
Strange - it seems to be autoscaling for me on Linux. I can take a look at Mac later.

**Comment by psavery** [comment]
I was able to reproduce this issue on Mac.

**Comment by joelvbernier** [comment]
Whelp -- I am running 0.7.1 package on Ubuntu (python 3.7.6, matplotlib 3.2.0, example data from [here](https://github.com/HEXRD/examples/tree/master/NIST_ruby/multiruby_dexelas)), this issue still persists (see below).  No exception thrown to stdout.

![hexrdgui_bug_azimuthal_sum](https://user-images.githubusercontent.com/1154130/77838969-ac83b080-712d-11ea-8b6b-419e0133772a.png)

**Comment by joelvbernier** [comment]
**_Update_**: so the [single GE case](https://github.com/HEXRD/examples/tree/master/NIST_ruby/single_GE) seems to work, but the [dual dexela case](https://github.com/HEXRD/examples/tree/master/NIST_ruby/multiruby_dexelas) from above not so much...  same session open.  There appears to be just _no_ lineout in the latter.

![Screenshot from 2020-03-28 20-01-04](https://user-images.githubusercontent.com/1154130/77839121-ed2ff980-712e-11ea-977b-99f87866501c.png)

**Comment by psavery** [comment]
@joelvbernier I, also, was able to reproduce this problem with the Linux package for v0.7.1 for that dataset (and I was able to reproduce the problem on the Mac as well).

This should be fixed in master, though (#304). I just tried out the fix locally and it does indeed appear to solve the problem.

But because that PR was merged after v0.7.1 was tagged, it is unfortunately not part of v0.7.1...

**Comment by joelvbernier** [comment]
_Another update_: If I start the 0.7.1 GUI on Linux and load the dual dexela case first, I get no azimuthal integration plot (empty axes, as shown above).  No exceptions echoed back to stdout.  If I load the single GE case, it works.  Then if I reload the dual dexela case, voila, it works.  Strange.

**Comment by joelvbernier** [comment]
Yeah, looks like this is no longer an issue in master, so I'll close it again.  Thanks!
