### ISSUE TITLE
Dock icon not appearing for v0.7.1 and Mac OS

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#296]
It was there, now it is gone.

**Comment by psavery** [comment]
On the mac that I tried, it looks like there is no icon for the `.app` file - so there is no icon when you drag it into your applications, and no icon when you click on it to open it.

But then, when I started the program, the icon appears to be in the dock.

**Comment by cjh1** [comment]
Now that we have an icon, we can also use it for the package icon.

**Comment by joelvbernier** [comment]
This one seems closed?  @psavery @cjh1

**Comment by cjh1** [comment]
Yes, its in the latest package.
