### ISSUE TITLE
Make table on materials tab popout from panel

### ISSUE THREAD

**Issue by cryos** [HEXRD/hexrdgui#300]
The table needs more space, doesn't need to be there all the time,
![image](https://user-images.githubusercontent.com/42214/77200141-617bf480-6ac0-11ea-823a-6ab1efdb3674.png)
Make that something in a dialog and we can open the dialog on demand.

**Comment by psavery** [comment]
Should this always be in a dialog? Or should there be an option to move it back and forth between the dialog and the panel?

**Comment by joelvbernier** [comment]
I'd say a dialog is a good default -- not familiar with other options.  Are you suggesting a dialog that is dockable inside the panel if desired?

**Comment by psavery** [comment]
Although I'm not 100% sure, I think we could make it into something like a dock widget. And you can add buttons to show/hide dock widgets.

But I can just do the dialog for now since it will be easier.
