### ISSUE TITLE
Auto-select cartesian view params based on loaded instrument config

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#305]
Feature request -- auto select the `Distance` and `Pixel Size` based on the average values of the `translation` (the last component, labeled `2`), and the `2*pixels:size` across the detectors.

**Comment by psavery** [comment]
@joelvbernier Should we remove the options to set these in the image mode widget, or just reset their values via the calculation every time the cartesian tab is selected?
![Screenshot from 2020-04-10 10-17-13](https://user-images.githubusercontent.com/9558430/78997387-7aeaec00-7b14-11ea-9afe-b17ebe8cea70.png)

**Comment by joelvbernier** [comment]
I think we should keep the interactors -- only auto-populate on load/reload of instrument config.  If the user wants a nice high-res figure (read: slow rendering), they can choose to do that.  I think a good rule of thumb is to use the average detector distance at 3x the native (or largest) pixel size.  We can adjust as necessary.

**Comment by psavery** [comment]
This is fixed in #338
