### ISSUE TITLE
Single Crystal Calibration

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#31]
We need to receive a single crystal example first, but we will need to make the calibrations work for single crystal data as well.

For single crystal data, the overlays will be dots instead of rings.

**Comment by cjh1** [comment]
@joelvbernier Did you manage to get us an example?

**Comment by psavery** [comment]
An example dataset that we can use for testing the Laue spots was uploaded to our shared google drive, in "examples/simulated_laue".

**Comment by joelvbernier** [comment]
I will add an example this weekend.

**Comment by cjh1** [comment]
@joelvbernier Any progress on an example?

**Comment by psavery** [comment]
I think this has been fixed for a while, starting with #394.
