### ISSUE TITLE
Ensure precision stays the same when switching tabs

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#315]
We should make sure that the precision does not change when you switch "Instrument Calibration" tabs. The widgets should not set values on the config unless they are modified by the user.

**Comment by psavery** [comment]
I have so far been unable to reproduce this, and I wonder if it was fixed by a PR already (such as #308).

The different views have different precisions on display. Here is the order from most precise to least precise:

1. Tree View
2. Form View
3. Slider View

When I modify the last digits of numbers in the tree view (which allows for about 10 digits of precision), and switch to the other tabs and back, the tree view digits are unaffected, unless the number is modified in one of the other views.

If anyone is able to reproduce this problem, it might be helpful to have the exact steps listed on this issue.

**Comment by joelvbernier** [comment]
I'll rebuild and take a look.

**Comment by psavery** [comment]
@joelvbernier Were you able to cause this issue? If not, we can close this issue unless it pops up again.
