### ISSUE TITLE
Use new overlay classes for creating overlays

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#320]
I think I have been making some good progress on this so far. I have added ranges and range indices (to check for merged ranges) as output to the powder overlay class, and Cartesian and Polar are working so far with some re-centering (and the Cartesian is receiving a fake single-detector instrument).

However, I'm not sure what's going on with the overlays for the raw view. They are appearing in a different corner, facing the wrong way, and are smaller than they should be.

![image](https://user-images.githubusercontent.com/9558430/83891162-c1c31f80-a71a-11ea-9958-f60f2de3968a.png)

I'm actively working on this to figure it out.

By the way, for the re-centering, the output from the polar version gave a 0° - 360° range for η. I just needed to convert this to a -180° to 180° range, which is what we had been using before.

For the Cartesian version, the output appears to be centered on (0, 0), whereas our Cartesian view has had (0, 0) in the upper left corner. Re-centering the output fixes this.

One last thing we might want to consider changing in the powder overlay class is that it currently outputs the overlays in a single list with nan-delimiters, like this:
```
[1, 2, NaN, 3, 4]
```

We might consider at some point changing it to this (where each overlay is in its own list):
```
[[1, 2], [3, 4]]
```

We are currently using the first case and creating a single matplotlib Line2D object for all of the overlays. It might make more sense to have a Line2D object for each overlay instead. But there may also be some performance advantages to the first method.

**Comment by joelvbernier** [comment]
Looks like we need to conver from (x, y) cartesian to pixel coordinates.  The detectors each have a `Planardetector.cartToPixel()` method that takes in vstacked (x, y) pairs and outputs vstack (i, j) -- row, col -- pairs.  So depends if we want to display the raw images with cartesian axes or pixel-based.  If the latter, we need to convert the overlay arrays.
