### ISSUE TITLE
conda build spec

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#330]
Are the build instructions in the README up to date?

**Comment by cjh1** [comment]
@psavery has a PR that is making some updates: #324. However, I think he then ran into the issue the hexrd now forces using 3.8, so we also push #325, however I believe he ran into an issue with this that we need to look at.

**Comment by psavery** [comment]
@joelvbernier When you install it with conda, try to install it via `conda install -c cjh1 -c anaconda -c conda-forge hexrdgui`, so that numpy will be installed from anaconda, and it will use mkl instead of libopenblas.

**Comment by psavery** [comment]
This should be up-to-date now. Let us know if there are any more issues.

**Comment by joelvbernier** [comment]
Build is stable so far!  👏👏👏
