### ISSUE TITLE
Proposal to remove "Show Live Updates" option

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#333]
There is an option under "View"->"Show Live Updates".

These days, I am pretty sure everyone who is working with hexrdgui wants this option to be checked. And, the behavior when it is not checked is not very intuitive, because some parts still have live updates anyways, while other parts don't.

For instance, any changes to detector settings always have live updates, whether the option is checked or not. The beam energy also always has live updates, whether the option is checked or not.

And, when "Show Live Updates" is not checked, the way that the user must update the canvas is by switching to another image tab and then switching back. I think leaving this option in, where some users might work with it accidentally being unchecked, will result in people submitting bug reports where the real problem is just that "Show Live Updates" is not checked.

~~I believe the original reason it was added was to allow the user to type to modify settings, and not have it update with every keystroke. However, we now have keyboard tracking disabled for most widgets, so this is no longer an issue.~~

UPDATE: above, it looks like the option was actually originally added because the previous behavior was to NOT update at all. It was added as an option so that the previous behavior to not update could be preserved, if desired. But I think that the old behavior isn't really used anymore.

For all of these reasons, I think it is best for us to always have "Show Live Updates" turned on, and remove the option.

Any thoughts or objections, @joelvbernier ?

**Comment by joelvbernier** [comment]
I was actually going to suggest that we leave it, but have it default to `True`.  Either that or remove it completely.  I agree with the initial thoughts behind the option, but yeah, I am always checking it on when using the GUI after realizing the canvas isn't updating.  One case I can imagine disabling it would be if you were going to set up parameters to render the image canvas that will take a while, say for generating a figure for a publication.  You can disable, set your parameters without it rendering for each box change, then set to live again to trigger the render.

**Comment by psavery** [comment]
Okay, we can keep it.

I actually set it up to be enabled by default in #215. But it looks like it isn't being enabled by default anymore. Not sure what happened.

I think we can also make enabling it to cause a re-render. That way, the user doesn't have to switch tabs to force a re-render.

**Comment by psavery** [comment]
I see the problem. `True == 'true'` is returning `False` right [here](https://github.com/HEXRD/hexrdgui/blob/1c56362c8d32146d0a73bb83f250894eed1d5898/hexrd/ui/hexrd_config.py#L187).

A fix is on the way...
