### ISSUE TITLE
Easier way to get Cartesian image in `mm` units?

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#337]
Currently, the [image that gets generated](https://github.com/HEXRD/hexrdgui/blob/2290f7d100afddf6f4a7d74725eb2468aabd65a0/hexrd/ui/image_canvas.py#L346) for the Cartesian viewer is, I believe, in pixel units. We [rescale the output image](https://github.com/HEXRD/hexrdgui/blob/2290f7d100afddf6f4a7d74725eb2468aabd65a0/hexrd/ui/image_canvas.py#L364-L370) to be in millimeter units after the image has been created, so that millimeter units are displayed on the image axes.

![image](https://user-images.githubusercontent.com/9558430/84663899-c7272380-aeeb-11ea-8e73-cb651fe0fa91.png)

Both the detector borders and the Cartesian overlays are currently output in pixel units as well, and we have to rescale them to be in millimeter units as well. The detector borders are rescaled [here](https://github.com/HEXRD/hexrdgui/blob/2290f7d100afddf6f4a7d74725eb2468aabd65a0/hexrd/ui/image_canvas.py#L245), and the overlays are rescaled [here](https://github.com/HEXRD/hexrdgui/blob/2290f7d100afddf6f4a7d74725eb2468aabd65a0/hexrd/ui/image_canvas.py#L256).

Is there an easy way for us to generate all of these in millimeter units, so we do not have to rescale them all?

**Comment by cjh1** [comment]
@joelvbernier This is the situation I was talking about on the call, any pointers?

**Comment by psavery** [comment]
By the way, the code for creating the individual detector images that are then summed together is [here](https://github.com/HEXRD/hexrdgui/blob/2290f7d100afddf6f4a7d74725eb2468aabd65a0/hexrd/ui/calibration/cartesian_plot.py#L187-L219).

**Comment by joelvbernier** [comment]
The dimensions for the extents you want are properties on detectors attached to the "fake" instrument object.  Specifically, the fist and last entries of the [row/col edge vectors](https://github.com/HEXRD/hexrdgui/blob/2290f7d100afddf6f4a7d74725eb2468aabd65a0/hexrd/ui/calibration/cartesian_plot.py#L202), which are in mm, can be used to define the extents in the plot.

**Comment by psavery** [comment]
Yeah, we have actually been setting the extents [here](https://github.com/HEXRD/hexrdgui/blob/f6c124a455be94f27b2773607d946eaf2b6cd17b/hexrd/ui/image_canvas.py#L365-L367), using the [panel size](https://github.com/HEXRD/hexrdgui/blob/f6c124a455be94f27b2773607d946eaf2b6cd17b/hexrd/ui/calibration/display_plane.py#L17-L44) that gets [passed into the fake instrument's detector](https://github.com/HEXRD/hexrdgui/blob/f6c124a455be94f27b2773607d946eaf2b6cd17b/hexrd/ui/calibration/display_plane.py#L46-L59) when it is created.

So, for the GE example, for instance, our extents are:
```
x: 0 564.301
y: 571.995 0
```

Before modifying the extents, we store the old extents, and then use them to [rescale points](https://github.com/HEXRD/hexrdgui/blob/f6c124a455be94f27b2773607d946eaf2b6cd17b/hexrd/ui/image_canvas.py#L260-L278) for the overlays and the detector borders.

The extents I'd get from the row/col edge vectors are similar, but centered on 0:
```
x: -282.0 282.0
y: 285.75 -285.75
```

I wonder if it might be easier if we used these extents instead, and then we could maybe
keep the detector borders and overlays in Cartesian units so they don't need to be
rescaled?

But it might also be nice to have the origin in the top left corner, as we have it. Not sure
which is better.

**Comment by joelvbernier** [comment]
Ah, this is a consequence of my cartesian frame, which has ij coords with the origin at the top left, like you'd expect, but the cartesian frame has the origin in the center of the panel (local detector coords).  That ain't changing ;-)

**Comment by psavery** [comment]
Okay! Well, let us know if you'd like us to change our coordinate system to have 0 in the center as well for the Cartesian view.

**Comment by joelvbernier** [comment]
If you are using the extents coming from the panel dimensions, the yes, (0,0) is the center of the rectangle.  Same goes for the individual detector raw views if we choose to plot those in millimeters.
