### ISSUE TITLE
Upstream fabio changes

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#340]
@joelvbernier I just raised this to remind us. If we can use upstream fabio it will simplify our install ( we  can remove the cjh1 channel ...)

**Comment by joelvbernier** [comment]
I will submit a pull request with a sheepish explanation of the bastardized GE file format right now...

**Comment by joelvbernier** [comment]
[PR](https://github.com/silx-kit/fabio/pull/395) submitted to the silx-kit fork, which I believe serves as the canonical fabio repo now.

**Comment by cjh1** [comment]
@joelvbernier Looking at the PR it looks like it pulls in a set of other commits (not made by your), do you need to rebase on master?

**Comment by joelvbernier** [comment]
Those were all me (at the beamline computer) and I did rebase.  They were always poking aroung in the same 2 files.

**Comment by cjh1** [comment]
@joelvbernier OK, I see two identities :smile:

**Comment by joelvbernier** [comment]
After a few fixes, should be able to get this merged in.

**Comment by cjh1** [comment]
Looks like the PR has been  merged :boom:

**Comment by cjh1** [comment]
We just need to wait for it to get into a release ....

**Comment by psavery** [comment]
We are now using a new release of fabio with the fixes as of hexrd/hexrd#161. We removed our locally built fabio from the conda forge channel as well.
