### ISSUE TITLE
Use Astropy Convolution Module

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#354]
For dark background subtraction, we want to look into using the [astropy convolution module](https://github.com/astropy/astropy/tree/master/astropy/convolution).

We don't want to depend on all of astropy, since it is so big. But we will see if there is a way we can copy and use their convolution module.

They use a [3-clause BSD license](https://docs.astropy.org/en/stable/license.html), so we shouldn't have any problems using their code.

**Comment by cjh1** [comment]
@joelvbernier Do you have the changes you made locally to use astropy? I what to know how we should be invoking it?

**Comment by psavery** [comment]
@cjh1 [Here](https://github.com/HEXRD/hexrd/blob/aaf883dcb2ec8bf694f1bc222576200439431e3b/hexrd/imageutil.py#L4-L8) is a place where it's being used in hexrd, by the way.

**Comment by cjh1** [comment]
@psavery Thanks, @joelvbernier That is all I need, I will see what we can do ...

**Comment by cjh1** [comment]
This was done in https://github.com/HEXRD/hexrd/pull/37
