### ISSUE TITLE
Apply mask to polar causing IndexError

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#361]
I noticed that if changing resolution in the polar view, the mask throws and IndexError (makes sense)

```
IndexError: boolean index did not match indexed array along dimension 0; dimension is 360 but the corresponding boolean dimension is 180
```

I think we will need a manager for mask elements, and for a change of polar view parameters should either

1. save the mask points in angular coordinates and reapply, or 
2. clobber existing masks

we would also want the ability to add to a mask "layer" successively.

**Comment by cjh1** [comment]
@johnkit You need to change the pixel size to recreate this ....

**Comment by johnkit** [comment]
@cjh1 I pushed branch https://github.com/johnkit/hexrdgui/tree/resize-polar-masks with a somewhat brute-force change, but there's a threading problem that can cause an intermittent seg fault. If I'm doing something foolish in the code, I can't find it. Would appreciate if you would try the branch. Fyi it is littered with debug messages and some mods to try to detect the cause - the first commit has the functional change.

**Comment by johnkit** [comment]
Patrick has given me some history on problems we have seen combining macOS, python, pyside, threading, and libopenblas; and indeed the seg fault I observe occurs in libopenblas off the main thread. I will try the conda env on macOS to see if the issue is reproduced there.

**Comment by cjh1** [comment]
Yes, I was unable recreate the crash ....

**Comment by johnkit** [comment]
Mostly FYI, I pushed the original commit for this to https://github.com/johnkit/hexrdgui/tree/orig-resize-polar-masks, without all the debug messages and fix attempts.

**Comment by johnkit** [comment]
News flash. After Google led me to [this thread on the Julia repo](https://github.com/JuliaLang/julia/issues/3369), I tried running hexrdgui with `OPENBLAS_NUM_THREADS=1` and have not crashed since. I will proceed with PR shortly.

**Comment by johnkit** [comment]
Added UI_ETA_MIN_DEGREES and UI_ETA_MAX_DEGREES to constants.py
