### ISSUE TITLE
Add progress bars for indexing steps

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#370]
Several indexing steps are ran in #363

However, there are no progress bars, and the GUI just freezes when the steps are running.

Some steps of interest are:

- [x] [Eta omega map generation](https://github.com/HEXRD/hexrdgui/blob/3c86306eee628b8743299f3c87057cad913a4edc/hexrd/ui/indexing/run.py#L53)
- [x] [Orientation fiber generation](https://github.com/HEXRD/hexrdgui/blob/3c86306eee628b8743299f3c87057cad913a4edc/hexrd/ui/indexing/run.py#L81)
- [x] [The indexing](https://github.com/HEXRD/hexrdgui/blob/3c86306eee628b8743299f3c87057cad913a4edc/hexrd/ui/indexing/run.py#L85)

It might be good to have at least an indeterminate progress bar, and maybe some text info.

The [Async Worker](https://github.com/HEXRD/hexrdgui/blob/3c86306eee628b8743299f3c87057cad913a4edc/hexrd/ui/async_worker.py#L36) will probably be used. An example can be seen [here](https://github.com/HEXRD/hexrdgui/blob/3c86306eee628b8743299f3c87057cad913a4edc/hexrd/ui/main_window.py#L530-L543).

![indeterminate_progress_bar](https://user-images.githubusercontent.com/9558430/86296500-e948c300-bbc6-11ea-9761-b2e6cff8577d.gif)

**Comment by cjh1** [comment]
May be capture logger output ...

**Comment by cjh1** [comment]
@johnkit This is now in master?

**Comment by psavery** [comment]
Looks like all of these are in master now, except for logger output.

**Comment by johnkit** [comment]
Correct. the progress dialogs are displayed but the logging is not connected.

**Comment by cjh1** [comment]
Let close this for now as the basics are now in place.
