### ISSUE TITLE
Revamp claibration classes

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#371]
Main points of improvement are

- [x] Move all the calibration classes to hexrd repo
- [x] Generalize the API to allow for assembling multi-component calibration problems
- [x] intermediate visualizations, mainly to verify "measured" input to the calibration problem.

**Comment by psavery** [comment]
I have some updates coming within the next couple of days to the calibration classes. Mainly, generalizing the overlay generation so they will work for overlay types other than powder.

Will have that up soon.

**Comment by psavery** [comment]
This is mainly fixed, except that our Laue Calibrator is [currently located in hexrdgui](https://github.com/HEXRD/hexrdgui/blob/b30a6dfeae78022c00d3b3973a6ed91b352b3bdf/hexrd/ui/calibration/pick_based_calibration.py#L84).

**Comment by psavery** [comment]
The last of the calibrator classes are being moved to HEXRD! See #1572. This closes this issue.
