### ISSUE TITLE
Add manager for line picked calibration

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#382]
This means to add a table of picked points to the calibration line picker dialog, where the user can see, edit, and remove points. When modified, it should update the points that are drawn in the canvas.

**Comment by bnmajor** [comment]
There are a couple of GUI options to address for the manager for picked points - 

The manager could be located in the line edit dialog:
![line_edit_in_dialog](https://user-images.githubusercontent.com/51238406/90541183-3d484080-e150-11ea-8d12-5c80464e9fc9.png)

Or in a separate dialog the way the mask manager is:
![mask-manager](https://user-images.githubusercontent.com/51238406/90541246-50f3a700-e150-11ea-97b9-60cb6b88a593.png)


Another concern is the actual editing of the points which could be done inline in the table or in pop-out dialog:
![edit-points-inline](https://user-images.githubusercontent.com/51238406/90541459-aa5bd600-e150-11ea-837f-bc075d248ed2.png)
![edit-points-dialog](https://user-images.githubusercontent.com/51238406/90541465-ad56c680-e150-11ea-8685-eb94fff90346.png)


Inline would be the obvious approach, my concern is that it may just be a bit cluttered that way and a dialog would be easier to read, but I don't want to add in unnecessary steps either.

@joelvbernier any opinions or concerns with on this?

**Comment by bnmajor** [comment]
Another thought - if the plan is to stop using the line picker dialog for masking by hand the concept of a separate dialog (like the mask manager) could be re-used to edit points for the hand drawn masks as well as the line picked calibration, whereas keeping the table in the line picker dialog would limit editing to calibration lines only. This may not be a real concern for masking though, just thought I'd bring it up

**Comment by psavery** [comment]
This was added some time ago. I'm not sure about the PR. But the user can click a button to edit their picks (which allows them to see and modify them).
