### ISSUE TITLE
Add mask manager component

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#385]
Should allow:

- Adding
- Removing
- Turning on and off

**Comment by psavery** [comment]
This might be related to #380

**Comment by cjh1** [comment]
We will need to take into account the masks being added by #407

**Comment by cjh1** [comment]
@bnmajor Is going to look at this once we have IO work done.

**Comment by joelvbernier** [comment]
got it.

**Comment by cjh1** [comment]
I think once we have most of the templating functionality we will better understand the requirements for the manager component.

**Comment by bnmajor** [comment]
Added in #446
