### ISSUE TITLE
Input calibration crystal stretch values

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#387]
Currently, in the overlay manager added in #373, the user inputs stretch values as inverse stretch values into the calibration crystal parameters:
![image](https://user-images.githubusercontent.com/9558430/86951027-f9a8f280-c11e-11ea-9b18-52b6baf10db6.png)

As noted in #92 ([this comment](https://github.com/HEXRD/hexrdgui/issues/92#issuecomment-584807140)), it would be better to have the user input stretch values instead, and then we will compute the inverse stretch values from those.

**Comment by psavery** [comment]
Note that for the `Calibration Crystal` section, the 12 spin boxes are set/get as a list of 12 numbers (this is what gets passed directly to hexrd). The getter/setter for this are [here](https://github.com/HEXRD/hexrdgui/blob/5d7484027daa416cd41214b65d4984d1afb2e483/hexrd/ui/overlay_editor.py#L142-L161).

We can put more code in there alongside the euler angle convention conversion code, that essentially converts from `inverse stretch` to `stretch` in the setter, and converts from `stretch` to `inverse stretch` in the getter. This way, the `stretch` values are only displayed in the GUI, but the actual values that are stored and provided to hexrd are the `inverse stretch` values.

**Comment by joelvbernier** [comment]
Lets go one further:  Let's lay the stretch out in matrix form, where the 6 values make up the diagonal and upper triangle of the symmetric matrix (3 x 3).  The components 0-5 map to: 
```
[0]    [5]    [4]
[5]    [1]    [3]
[4]    [3]    [2]
```
Then we can internally take the inverse (and the off diagonal components get a scaling of √2 as well).

**Comment by psavery** [comment]
So, the stretch matrix off-diagonal components get a scaling of √2, and then it gets inverted. Is that right? Or is the scaling after the inversion?

**Comment by joelvbernier** [comment]
inversion, then scaling.  You can use the following utility from hexrd to take the unscaled V components to the scaled inv(V) that the code needs in the grain parameters:
```
from hexrd import matrixutil

vinv_vecs = matrixutil.symmToVecMV(np.linalg.inv(v_matx), scale=True)
```
where `v_matx` is symmetric, (3, 3) and `vinv_vecs` are the 6 values that go into the grain parameter list for the Laue simulation.

**Comment by joelvbernier** [comment]
for your own edification, here is a description of the 6-vector basis we use for representing 3x3 symmetric martrices (and explains the √2).  Dug this up from the wayback machine :-)

[MVNotes.pdf](https://github.com/HEXRD/hexrdgui/files/4935175/MVNotes.pdf)
