### ISSUE TITLE
Slider widgets for Laue overlay options

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#389]
In the overlay manager added in #373, there are widgets for editing Laue overlay options.

![image](https://user-images.githubusercontent.com/9558430/86964324-dd638080-c133-11ea-84da-666f411601b5.png)

We should look into adding slider widgets to them to make them more interactive. The slider widgets may operate in a similar way that the detector slider widgets do, in the slider view:
![image](https://user-images.githubusercontent.com/9558430/86964556-40551780-c134-11ea-806e-33a315fbf25d.png)

The UI for the Laue overlays is part of the [OverlayEditor](https://github.com/HEXRD/hexrdgui/blob/794792a0e7c11c5b3caf3f85e1449a521532b365/hexrd/ui/overlay_editor.py#L12) and the [CalibrationCrystalEditor](https://github.com/HEXRD/hexrdgui/blob/794792a0e7c11c5b3caf3f85e1449a521532b365/hexrd/ui/calibration_crystal_editor.py#L12).

We should make sure that the overlay manager doesn't become too big with the addition of these widgets. The user most likely wants to see the image canvas while they are interacting with the overlay manager.

**Comment by psavery** [comment]
Also note that as we work on this, we may also need to look into speeding up some of the Laue spot generation code, to make this as interactive as possible.

**Comment by joelvbernier** [comment]
We are going to push some updates to the material, which might help.  But yes, I am sure there is room for optimization in the simulator.

**Comment by psavery** [comment]
Should we add sliders for the stretch matrix values as well? Or only for the orientation, position, and min and max energies?

**Comment by johnkit** [comment]
@joelvbernier   Here is a strawman/mockup for revising the crystal calibration widget to include "form" and "slider" tabs. (The "form" tab is essentially the current widget.) To conserve vertical space, the slider tab has a dropdown box to select between position and orientation.

![mockup-calcrystal-form2](https://user-images.githubusercontent.com/5559383/90061393-1606f480-dcb4-11ea-84fb-7d1dfe951dbc.png) 
![mockup-calcrystal-slider2](https://user-images.githubusercontent.com/5559383/90061401-1a331200-dcb4-11ea-801f-bf40c5de77a8.png)

**Comment by cjh1** [comment]
@johnkit This look great. My one question for @joelvbernier is do you want to be able adjust the orientation and position at the same time. In which case we might want the duplicate the sliders, so they are accessible without using the drop down.

**Comment by joelvbernier** [comment]
On that, not sure why it is slower in this case — was fine in the python 2...

**Comment by cjh1** [comment]
@joelvbernier Any thoughts of the layout? 3 sliders and combo vs 6 sliders?

**Comment by cjh1** [comment]
Fixed by #498
