### ISSUE TITLE
Add Laue overlay widths for raw and cartesian views

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#395]
Laue overlay widths are added to the polar view in #394 

The polar view is probably the easiest for this, because the widths result in rectangles. The Cartesian and raw views might be a little trickier, since two of the edges will likely be curved, if I'm imagining it correctly.

The code for creating the polar ranges is [here](https://github.com/HEXRD/hexrdgui/blob/03bfd7f26feacc8768ffc859864972f49e137c72/hexrd/ui/overlays/laue_diffraction.py#L110-L127). Similar code will need to be added for the raw and Cartesian views. Once the ranges data is added to the overlay data, they then get plotted [here](https://github.com/HEXRD/hexrdgui/blob/03bfd7f26feacc8768ffc859864972f49e137c72/hexrd/ui/image_canvas.py#L219-L222).

Laue overlay widths to do:
- [x] Cartesian
- [x] Raw

**Comment by joelvbernier** [comment]
For the cartesian versions of the angular, here is an code snippet:

```
refl_patches = dict.fromkeys(instr.detectors)
for ip_key, ip in instr.detectors.items():
    patches = xrdutil.make_reflection_patches(
        ip.config_dict(chi=instr.chi, tvec=instr.tvec, beam_vector=instr.beam_vector),
        valid_angs[ip_key], ip.angularPixelSize(valid_xy[ip_key]),
        rmat_c=xfcapi.makeRotMatOfExpMap(expmap_c),
        tth_tol=tth_tol, eta_tol=eta_tol,
        npdiv=npdiv, quiet=True)
    refl_patches[ip_key] = patches
    ii = np.vstack([[patches[i][-1][0][0, 0],
                     patches[i][-1][0][0, -1],
                     patches[i][-1][0][-1, -1],
                     patches[i][-1][0][-1, 0],
                     patches[i][-1][0][0, 0]] for i in range(len(patches))])
    jj = np.vstack([[patches[i][-1][1][0, 0],
                     patches[i][-1][1][0, -1],
                     patches[i][-1][1][-1, -1],
                     patches[i][-1][1][-1, 0],
                     patches[i][-1][1][0, 0]] for i in range(len(patches))])
    fig2, ax2 = plt.subplots(1, 1, figsize=None)
    cmap = cm.bone_r
    cmap.set_under('b')
    sclimg = log_scale_img(log_scale_img(img_dict[ip_key]))
    vmin = np.percentile(sclimg, 5)
    vmax = np.percentile(sclimg, 99)
    # sclimg = equalize_adapthist(img_dict[ip_key], clip_limit=0.001)
    ax2.imshow(sclimg,
               cmap=cmap,
               vmin=vmin,
               vmax=vmax,
               interpolation='none')
    for pp in zip(jj, ii):
        ax2.plot(pp[0], pp[1], 'c-', lw=3)
    #ax2.axis('equal')
    ax2.set_xlim(0, sclimg.shape[1])
    ax2.set_ylim(0, sclimg.shape[0])
    ax2.set_title("patches for '%s'" % ip_key)
```

and the resulting plot:

<img width="1349" alt="Screen Shot 2020-07-09 at 3 36 36 PM" src="https://user-images.githubusercontent.com/1154130/87097410-02222b80-c1fa-11ea-8af8-590c9188b3f7.png">
