### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#409]
```
/home/cjh/work/source/hexrd/hexrd/instrument.py:2395: RuntimeWarning: divide by zero encountered in true_divide
  u = np.dot(nvec_map_lab.T, tvec_map_lab) \
/home/cjh/work/source/hexrd/hexrd/instrument.py:2399: RuntimeWarning: invalid value encountered in multiply
  pts_map_lab = np.tile(u, (3, 1)) * pts_lab
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/calibration/cartesian_plot.py", line 18, in cartesian_viewer
    return InstrumentViewer()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/calibration/cartesian_plot.py", line 48, in __init__
    self.make_dpanel()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/calibration/cartesian_plot.py", line 53, in make_dpanel
    self.dpanel = self.dplane.display_panel(self.dpanel_sizes,
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/calibration/display_plane.py", line 51, in display_panel
    ncols_map = int(del_x/mps)
ValueError: cannot convert float NaN to integer
```

To reproduce:

1. Start up HEXRD ( two detectors )
2. Switch to Cartesian view.

**Comment by joelvbernier** [comment]
What instrument are you using, and which commit did this appear in?  There have been no changes to the underlying hexrd code.

**Comment by cjh1** [comment]
@joelvbernier Not sure when it appeared. It may well be a problem in hexrdgui, haven't looked that deeply, just wanted to record it as an issue.

**Comment by psavery** [comment]
It looks like the NaNs first show up in [this line](https://github.com/HEXRD/hexrdgui/blob/5d7484027daa416cd41214b65d4984d1afb2e483/hexrd/ui/calibration/display_plane.py#L31).

**Comment by joelvbernier** [comment]
Are you using an instrument with parallel detectors?  That code has not been altered in quite a while.

On July 14, 2020 at 2:02 PM, Patrick Avery <notifications@github.com> wrote:






It looks like the NaNs first show up in this line.

**Comment by joelvbernier** [comment]
You get NaNs if the ray you are trying to map can't intersect the specified plane.

On July 14, 2020 at 2:02 PM, Patrick Avery <notifications@github.com> wrote:






It looks like the NaNs first show up in this line.

**Comment by psavery** [comment]
It's our default instrument config (full of default values) that we've had for a long time. It only really shows up if you start the program for the first time.

We can probably just change our default instrument config, if that's the easiest thing to do. Here it is.

```
beam:
  energy: 55.6180
  vector: {azimuth: 90.0, polar_angle: 90.0}
detectors:
  ge1:
    distortion:
      function_name: None
      parameters: [0.0, 0.0, 0.0,
        2.0, 2.0, 2.0]
    pixels:
      columns: 2048
      rows: 2048
      size: [1.0, 1.0]
    saturation_level: 14000.0
    transform:
      translation: [0.0, 0.0, 0.0]
      tilt: [0.0, 0.0, 0.0]
  ge2:
    distortion:
      function_name: None
      parameters: [0.0, 0.0, 0.0,
        2.0, 2.0, 2.0]
    pixels:
      columns: 2048
      rows: 2048
      size: [1.0, 1.0]
    saturation_level: 14000.0
    transform:
      translation: [0.0, 0.0, 0.0]
      tilt: [0.0, 0.0, 0.0]
oscillation_stage:
  chi: 0.0
  translation: [0.0, 0.0, 0.0]
```

**Comment by joelvbernier** [comment]
it is the translation value of all zeros; which puts the origin on the detector plane.  make t_z, say -100.

On July 14, 2020 at 2:36 PM, Patrick Avery <notifications@github.com> wrote:






It's our default instrument config (full of default values) that we've had for a long time. It only really shows up if you start the program for the first time.

We can probably just change our default instrument config, if that's the easiest thing to do. Here it is.

beam:
  energy: 55.6180
  vector: {azimuth: 90.0, polar_angle: 90.0}
detectors:
  ge1:
    distortion:
      function_name: None
      parameters: [0.0, 0.0, 0.0,
        2.0, 2.0, 2.0]
    pixels:
      columns: 2048
      rows: 2048
      size: [1.0, 1.0]
    saturation_level: 14000.0
    transform:
      translation: [0.0, 0.0, 0.0]
      tilt: [0.0, 0.0, 0.0]
  ge2:
    distortion:
      function_name: None
      parameters: [0.0, 0.0, 0.0,
        2.0, 2.0, 2.0]
    pixels:
      columns: 2048
      rows: 2048
      size: [1.0, 1.0]
    saturation_level: 14000.0
    transform:
      translation: [0.0, 0.0, 0.0]
      tilt: [0.0, 0.0, 0.0]
oscillation_stage:
  chi: 0.0
  translation: [0.0, 0.0, 0.0]

**Comment by joelvbernier** [comment]
Actually, just make it 1 detector (do we need multiple in the default?), call it 'detector_1', and make 
translation: [0.0, 0.0, -1000.0]


That would represent a "generic" transmission instrument for synchrotron XRD.


-Joel

On July 14, 2020 at 2:36 PM, Patrick Avery <notifications@github.com> wrote:






It's our default instrument config (full of default values) that we've had for a long time. It only really shows up if you start the program for the first time.

We can probably just change our default instrument config, if that's the easiest thing to do. Here it is.

beam:
  energy: 55.6180
  vector: {azimuth: 90.0, polar_angle: 90.0}
detectors:
  ge1:
    distortion:
      function_name: None
      parameters: [0.0, 0.0, 0.0,
        2.0, 2.0, 2.0]
    pixels:
      columns: 2048
      rows: 2048
      size: [1.0, 1.0]
    saturation_level: 14000.0
    transform:
      translation: [0.0, 0.0, 0.0]
      tilt: [0.0, 0.0, 0.0]
  ge2:
    distortion:
      function_name: None
      parameters: [0.0, 0.0, 0.0,
        2.0, 2.0, 2.0]
    pixels:
      columns: 2048
      rows: 2048
      size: [1.0, 1.0]
    saturation_level: 14000.0
    transform:
      translation: [0.0, 0.0, 0.0]
      tilt: [0.0, 0.0, 0.0]
oscillation_stage:
  chi: 0.0
  translation: [0.0, 0.0, 0.0]

**Comment by psavery** [comment]
Sounds good, #413 fixes this.
