### ISSUE TITLE
Load data options become inactive after file read

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#424]
am trying to load a single image for which I have a standalone dark image (same GE format).  I select "file" for the dark mode and select the filename, but when I read the image, it toggles to None and the buttons become inactive.  see below.
<img width="1712" alt="Screen Shot 2020-07-19 at 10 41 55 AM" src="https://user-images.githubusercontent.com/1154130/87882128-e1549580-c9b2-11ea-9f5a-2636fcf8638a.png">
Loading single frames is not what this dialog is really meant for, but still, this is not the correct behavior.

**Comment by joelvbernier** [comment]
@bnmajor a screen cap to illustrate the issue.



![load_data_dark_file_bug_480p](https://user-images.githubusercontent.com/1154130/87967909-6fdd1b80-ca74-11ea-987b-52256717c569.gif)

**Comment by bnmajor** [comment]
@joelvbernier This was set to be this way in #292 when aggregation was prevented for single frame images. There is no record or issue explaining why dark subtraction was also disabled, so as far as I can tell there is no good reason for it. #431 reverses this, but can be adjusted or limited if there are cases where all dark subtraction options should not be available.

**Comment by bnmajor** [comment]
For now the only dark subtraction option that will be enabled when a single image is loaded is the file option. Additional (or all other) options can be added in in future PRs if needed.

**Comment by joelvbernier** [comment]
This still seems broken, now I get an image with identically 0 everywhere for the same dark subtraction example (files can be found in the shared Google Drive under sample_images, 4553 is image, 4555 is dark)

![dark_subtr_from_file_broken_trim](https://user-images.githubusercontent.com/1154130/88713179-c0392680-d0cf-11ea-913a-b3745c6c43e1.gif)

For ref, here are what the source images and the background subtracted look like:

![Screenshot 2020-07-28 12 43 21](https://user-images.githubusercontent.com/1154130/88713376-11491a80-d0d0-11ea-84e1-6553346ac8f4.png)

**Comment by bnmajor** [comment]
@joelvbernier There was a bug with dark subtraction when using a file but this should have been fixed in #439. Changes have been merged into master. If there are any further issues we can re-open this again.

**Comment by joelvbernier** [comment]
WIll test right now, thanks.
