### ISSUE TITLE
Strange overlay behavior

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#426]
Preface: this is on Mac OS 10.15.5

A few things: 

1. The overlays don't disappear on "hide all"; you have to toggle the checkbox.  There is also a logical disconnent with the global checkbox on the materials panel -- I would think that we would have that checkbox toggle the visibility for all overlays, while the manager allows the user to toggle individual overlay visibility.  See below:
![overlay_hide_bug_480p](https://user-images.githubusercontent.com/1154130/87968952-15dd5580-ca76-11ea-8178-966f85cdacf5.gif)
2. The overlays do not update in the raw view:
![overlay_update_raw_bug_480p](https://user-images.githubusercontent.com/1154130/87969011-30afca00-ca76-11ea-98a4-4bb981020874.gif)

**Comment by joelvbernier** [comment]
Addendum: the overlays also disapper in the cartesian view if you change any of the generating parameters.

**Comment by cjh1** [comment]
I am pretty sure this is related to #160

**Comment by joelvbernier** [comment]
@cjh1, who has inhereted this in @psavery's absence?

**Comment by cjh1** [comment]
@johnkit Has been looking at this and we have a work around, however, I am pretty sure the underlying cause is #160, we can push the work around.

**Comment by cjh1** [comment]
Regarding #160 I am trying to get @psavery change upstreamed so that we can at least request they build with the latest Mac SDK. However, I think we are probably going to have to end up build our own python and pushing it to our HEXRD org.

**Comment by joelvbernier** [comment]
Additional issue: setting orientation via the spin boxes is broken?  Looks like `self.params` is getting set to `None` in `calibration_crystal_editor.py`
```
Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/calibration_crystal_editor.py", line 52, in value_changed
    self.params[:3] = self.orientation
TypeError: 'NoneType' object does not support item assignment
```

**Comment by cjh1** [comment]
@joelvbernier I will take a look at the spin box issue. We continue to push upstream to get the more general Qt Mac issues resolved.

**Comment by joelvbernier** [comment]
I have virtual box with ubuntu on my mac, so I can test those two platforms.  Windows soon...

**Comment by cjh1** [comment]
@joelvbernier I just fix the spinbox issue in #443

**Comment by cjh1** [comment]
I am also going to upload a version of python we have built that you can try out on your mac.

**Comment by psavery** [comment]
This is now being tracked in #505
