### ISSUE TITLE
Double matplotlib toolbar?

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#430]
May very well be a Mac-specific issue, but switching between view modes a second toolbar appeared and won't go away 😂
![Screenshot 2020-07-21 13 35 54](https://user-images.githubusercontent.com/1154130/88104474-5365df80-cb57-11ea-91b3-3dfce903a5a6.png)

**Comment by bnmajor** [comment]
This may indeed be Mac-specific and related to #160, I was unable to reproduce on Ubuntu

**Comment by joelvbernier** [comment]
oh mac...  I haven't been able to reliably reproduce, so we'll close for now.
