### ISSUE TITLE
Add mask to elliptical, rectangular regions

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#432]
In addition to the hand-drawn component already merged in, can we add a tool to specify generic elliptical and rectangular areas?  Hopefully you have code to steal from other projects...  I am stealing my inspiration from ImageJ:
![ImageJ_rect_ellp_selectors](https://user-images.githubusercontent.com/1154130/88346319-e8560d80-ccfc-11ea-9ba8-e47068eaacbe.gif)
Somewhat lower priority than other issues, but I wanted to put it up there.

**Comment by cjh1** [comment]
@joelvbernier as a side note the animated gifs are really useful thanks.

**Comment by joelvbernier** [comment]
Bumping this up in priority as we have a detector case where we need to be able to generate a drawn mask in the raw view (see interpanel stripes below) using a series of rectangular regions (can't be done with intensity thresh in this case).  Also need to be able to export as we discussed today.
![Screen Shot 2020-08-18 at 3 20 23 PM](https://user-images.githubusercontent.com/1154130/90571465-a3d85900-e166-11ea-85be-1d7429634f98.png)

**Comment by cjh1** [comment]
@joelvbernier This is in @bnmajor 's queue

**Comment by psavery** [comment]
I believe this was fixed by #481. Feel free to open it back up if I'm wrong.
