### ISSUE TITLE
Key error in instrument config

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#434]
The `panel_buffer` key in the detector blocks should be simply `buffer`.

**Comment by cjh1** [comment]
I think this is a issue with hexrd? There is not reference to `panel_buffer` in the hexrdgui repo.

**Comment by joelvbernier** [comment]
I think the panel's config dump had it wrong.  The init method for the instrument should recognize "buffer" keyword, but we still need to address the case of saving a 2-d mask-like buffers (can't stuff them in the YAML).

**Comment by joelvbernier** [comment]
This will be closed with a pending PR in hexrd.
