### ISSUE TITLE
Need to update instrument config writer to handle 2-d array-like buffers

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#442]
Thought there was already an issue for this one; no matter, we currently have no acceptable way of saving the yaml style instrument config for panels that have a 2-d arrays for the `panel_buffer` property (_e.g._, irregular shapes like the TARDIS example).  The best fix would be to add a trigger to save/load from an auto-named .npy files.  The imageseries 'image-files' adapter does something similar for the omega angle arrays.  @donald-e-boyce , you want a crack at this?

**Comment by cjh1** [comment]
@donald-e-boyce If you don't have time or interest, I can take this on.

**Comment by donald-e-boyce** [comment]
I'll suggest you take a look at imageseries/load/metadata.py.

https://github.com/HEXRD/hexrd/blob/master/hexrd/imageseries/load/metadata.py

The idea was that more than one format might use yaml for metadata, so I
set up a standard reader.  It looks like the original approach was to use
the keyword "++np.array" to indicate an np array was to be read. I made it
more general by having a keyword that starts with "! " trigger an action
that depends on the next word (command). So far, the only command is
"load-numpy-array".

Anyway, I'm not following exactly what is needed here, but that may be a
useful module.

**Comment by cjh1** [comment]
@joelvbernier We do have a issue for this, its here HEXRD/hexrd#28

**Comment by joelvbernier** [comment]
@cjh1 yes, we can close this issue and lieu of that -- one note, however.  Once we set up the masks in the GUI, we will in theory want to set the panel_buffer attribute on the detectors.  We will nee to do some interpolation for mask regions defined in the angle space.

**Comment by cjh1** [comment]
This is now resolved
