### ISSUE TITLE
Laue ranges in raw and Cartesian views do not update with position change

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#448]
Although the ranges appear to be correct when the position of the crystal is (0, 0, 0), if the position is modified, the spots move, but the ranges don't.

![position_issue](https://user-images.githubusercontent.com/9558430/89939992-d6bea200-dbe6-11ea-8546-ab64c6ffe934.png)

The [current strategy](https://github.com/HEXRD/hexrdgui/blob/8dd2b4aad7c2763b4ea02991401e17abaaa14e2e/hexrd/ui/overlays/laue_diffraction.py#L121-L165) of computing the range bounding box corners in angles based off the angular spots, then converting from angles to Cartesian, may not be working for non-origin positions.

**Comment by joelvbernier** [comment]
Can't the ranges be done on the fly from the simulation data itself?  Simply expanding the simulation to the box vertices?

**Comment by psavery** [comment]
I think that's what we're doing, but the widths are in angles and need to be converted to Cartesian coordinates.

This issue gets fixed by #451 and HEXRD/hexrd#66

**Comment by joelvbernier** [comment]
merged.
