### ISSUE TITLE
fit grains: Allow the user to switch between strain and stress

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#458]

**Comment by joelvbernier** [comment]
@cjh1 -- I _think_ the best way to do this involves utilizing @saransh13's new material class, as there will be attributes there for material properties (_i.e._, elastic moduli).  He has rebased off of master, and it making some edits, then we should be ready to merge...  at any rate, let's hold off until that is ready.

**Comment by cjh1** [comment]
@joelvbernier Sounds like a good plan, we will wait for that to me merged.

**Comment by psavery** [comment]
#653 will be utilized to do this.

**Comment by psavery** [comment]
@saransh13 Is this the equation we will use to compute the stresses from the strains?
![Screenshot from 2020-11-09 15-47-12](https://user-images.githubusercontent.com/9558430/98600329-0000d400-22a3-11eb-81e8-d8984d937e13.png)

Where `σ` is stress, `ϵ` is strain, and `c` is the compliance tensor?

**Comment by psavery** [comment]
@saransh13 Actually, this one looks simpler:
![Screenshot from 2020-11-09 15-53-43](https://user-images.githubusercontent.com/9558430/98600861-d5fbe180-22a3-11eb-9869-d70ec0e1f273.png)
![Screenshot from 2020-11-09 15-54-02](https://user-images.githubusercontent.com/9558430/98600870-d7c5a500-22a3-11eb-9868-5da5ada495c9.png)

Taken from [here](https://serc.carleton.edu/NAGTWorkshops/mineralogy/mineral_physics/tensors.html#Elasticity)

**Comment by psavery** [comment]
@saransh13 here is how I am currently computing the stress. Please let me know if it is wrong in any way.
```python
stress = np.einsum('ij,j->i', compliance, strain)
```

**Comment by saransh13** [comment]
@psavery The second one is easier for computation. Your method is correct, but a simpler method would just be `np.dot(compliance, strain_vec)`. Note that strain needs to be specified as a vector in the formula I supplied. If you have strain as a 3x3 matrix, then you can obtain the vector by 

`strain_vec = [strain[0,0], strain[1,1], strain[2,2], 2*strain[1,2], 2*strain[0,2], 2*strain[0,1]]`

**Comment by psavery** [comment]
I've been using the attached columns from the fit grains output.
![Screenshot from 2020-11-09 19-18-18](https://user-images.githubusercontent.com/9558430/98617085-d99f6080-22c3-11eb-911a-0b0518caec17.png)

It looks like the indices match the `strain_vec`. I'm not sure if the last three are scaled by the factor of 2, though.
