### ISSUE TITLE
fit grains: Add axes labels

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#459]

**Comment by psavery** [comment]
The axes labels are being added [here](https://github.com/HEXRD/hexrdgui/pull/642/files#diff-55f8cc0141b97b8367966fbf34c8a3aee4467e81b5439487338f8831a4ab9eb9R113-R115), but they are being removed when the axis gets cleared [here](https://github.com/HEXRD/hexrdgui/pull/642/files#diff-55f8cc0141b97b8367966fbf34c8a3aee4467e81b5439487338f8831a4ab9eb9R67). I'm not sure if the axes clearing is necessary for when the "colorby" changes?

If it is necessary, we'll need to set the labels again afterward.
