### ISSUE TITLE
Look into adding stereographic projection

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#465]
@joelvbernier Is going to provide example code.

**Comment by saransh13** [comment]
Provided example code to @psavery

**Comment by saransh13** [comment]
The following input needs to be added to the view:
1. size of stereographic projection image in pixels (integer value)
2. check box to subtract background. This is the keyword argument passed to the function `stereo_projection_of_polar_view`. If background subtraction is not performed, then the raw images are directly used.

**Comment by psavery** [comment]
To follow up on this, we ended up just making the stereo view a projection directly from the polar view. So that means that any changes the user makes to the polar view (background subtraction, masking, etc.) will be present in the stereo view as well. We also added a label that indicates this.
