### ISSUE TITLE
Deactivate enter key capture for dialogs

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#472]
Many of the separate dialogs (_e.g._, the overlay manager, the picker widow, ...) have a button in focus by default that captures the enter key.  Can we disable this behavior in all cases?  I know it is not necessary, but I invariably hit enter after inputing text into widgets (habit...).

**Comment by johnkit** [comment]
FYI for buttons internal to the dialogs, we can disable the autoDefault property. For buttons in the QButtonBox widget, we'll add an event filter to ignore `<Enter>` keys because QButtonBox overrides the button autoDefault property.

**Comment by joelvbernier** [comment]
Thanks guys.
