### ISSUE TITLE
Enhancements to hand-drawn mask options

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#474]
After using this a bit, I am requesting the following enhancements:

- [x] remove the picker window; this is not needed for picking mask region points
- [x] it seems to want to reset a zoomed view in the canvas (at least polar); is this necessary?
- [ ] want to add the ability to draw masks in the raw view
- [ ] store all masked regions in **raw pixel coordinates**; that way the selections will update in a more intuitive way when changing instrument parameters.  Even if the instrument parameters are off, the regions will still map consistently to the offending features in the raw data.

**Comment by psavery** [comment]
For point 2, yes, it looks like the x-axis is being reset on the polar view when the user is zoomed in and any edits are made to the image. I'll look into why.

**Comment by joelvbernier** [comment]
@psavery I assume the picker window slows things down a bit; for such coarse point picking, we can default to picks on the raw canvas without the zoom window.  I also wanted to modify the behavior of the picker window itself.

**Comment by joelvbernier** [comment]
@psavery bumping this up in priority.  With regards to task 1, I still think just picking points on the image for the polygon masks is sufficient and likely faster (don't need the zoom).  There is also the desire to pick in the zoom window, as requested in #485 -- after playing with it more, this would be more intuitive for the users.

**Comment by bnmajor** [comment]
@joelvbernier In working with the masking in each view, masks created in raw view can be applied to polar view without any issues, but applying masks created in polar mode to raw mode has some issues if masks overlap detectors or points are selected outside of a panel (which seems to be exactly what you were explaining in #556). What behavior would you like to see for now? Should raw masks be applied to polar but not vice versa (until we come up with a way to handle the case of selecting invalid points), or should masks only be applied to the view they were created in to keep behavior consistent?

**Comment by cjh1** [comment]
@joelvbernier Can we get the answers to @bnmajor questions?

**Comment by psavery** [comment]
@bnmajor Is this ready to be closed?

**Comment by bnmajor** [comment]
I think this is related to #595 - I can look over that PR to make sure it's ready to merge, then this should be ready to close.

**Comment by bnmajor** [comment]
Actually, looks like issue #556 goes with #595. I think this can be closed
