### ISSUE TITLE
Polarview enhancements

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#476]
We'd like to add the ability to specify the min/max eta ranges.  Currently defaults to (-180, 180), but there are cases where we'd like to have the ability to shift the view and even limit the coverage range to < 360° (_e.g._, for instruments with limited coverage).  The hooks are there in polarview.py to set the ranges.  Just need a check that `eta_max - eta_min` is in (0, 2π).

**Comment by psavery** [comment]
This sounds good.

There are a few places in the code where -180 to 180 are hard-coded, like [here](https://github.com/HEXRD/hexrdgui/blob/292327b95247a683c289bba1682a2b46d7409731/hexrd/ui/calibration/polar_plot.py#L50), [here](https://github.com/HEXRD/hexrdgui/blob/292327b95247a683c289bba1682a2b46d7409731/hexrd/ui/constants.py#L32-L33), and [here](https://github.com/HEXRD/hexrdgui/blob/292327b95247a683c289bba1682a2b46d7409731/hexrd/ui/overlays/powder_diffraction.py#L40).

We'll just need to use something like `HexrdConfig().polar_res_eta_min` and max instead, similar to `HexrdConfig().polar_res_tth_min` and max. And we can add the eta options to the image mode widget.

**Comment by joelvbernier** [comment]
bumping the priority on this.

**Comment by psavery** [comment]
@johnkit Maybe do a grep of '180' on the source code to make sure we catch all the cases. We can replace them with something like `HexrdConfig().polar_res_eta_min`, and max.

**Comment by johnkit** [comment]
Notes:
* Adding eta range to the image mode widget increases height slightly from 138 to 152 pixels (even though spinbox vertical height is 20px).
* For now, I'll set the spinbox min/max to [-540, 540] so that you can offset a full 2pi on either end.

![image](https://user-images.githubusercontent.com/5559383/93512013-a9ee6080-f8f1-11ea-9596-bbdc1463b8a7.png)

**Comment by psavery** [comment]
We might want to use the unicode η similar to what is being done for 2θ.

And yeah, decreasing the size of the main canvas isn't that nice. But I think we can think of ways to reduce the image mode widget size later, if it isn't urgent now.

**Comment by psavery** [comment]
@joelvbernier Question. Are we going to require eta_max - eta_min to be 360? Is eta_max - eta_min going to be the eta_period? Or is it always going to be eta_min + 360?

**Comment by joelvbernier** [comment]
@psavery no; but eta period will always default to 360. + eta_min.

**Comment by joelvbernier** [comment]
@johnkit -- how about something like this for the form design?  Saves vertical space
![Screenshot from 2020-09-18 11-17-45](https://user-images.githubusercontent.com/1154130/93631664-d1e8cd00-f9a0-11ea-997a-0b0f91659894.png)
