### ISSUE TITLE
Add adapt to new material package in hexrd

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#482]
The following [PR](https://github.com/HEXRD/hexrd/pull/55) replaces the material module. Material information will be stored in a HDF5 format and will contain atomic information. The first stage will be to replace our existing [materials.hexrd](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/resources/materials/materials.hexrd) with the new HDF5 format, @joelvbernier  and @saransh13 are going to provide this file.

**Comment by joelvbernier** [comment]
@saransh13, perhaps we should hold off on deleting the sglite and existing (legacy) materials modules if there still there in order to maintain compatibility with cpickles materials spec for the near term.  We can mark them for deletion in the future.

**Comment by saransh13** [comment]
Yeah, that sounds like a good plan.

**Comment by psavery** [comment]
@joelvbernier @saransh13 Should I also try to migrate from using `hexrd.spacegroup` to `hexrd.symbols`? We are currently using `hexrd.spacegroup` to get the following:

1. Hall symbol
2. Hermann–Mauguin symbol
3. Laue group
4. Lattice type
5. Required params (ie., do we need just **a**, or **a** and **c**, etc.).

**Comment by saransh13** [comment]
I think we can just stick to `hexrd.spacegroup` for now. Can eventually be replaced by `hexrd.symbols` in the future. 
@joelvbernier ?

**Comment by saransh13** [comment]
@psavery the latest push should have the `material.dum_material` function.

**Comment by psavery** [comment]
Thanks @saransh13. I'll give it a try.
