### ISSUE TITLE
Add new "structure" tab to materials panel

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#483]
This will be used provide the atomic information. We are going to need some sort of periodic table widget, to be able to pick the elements. [this is one](http://www.silx.org/doc/silx/0.9.0/modules/gui/widgets/periodictable.html) possibility.

**Comment by psavery** [comment]
@joelvbernier I think we're going to try out [silx](http://www.silx.org/doc/silx/0.9.0/modules/gui/widgets/periodictable.html) (also linked above), because it doesn't add many dependencies, and it seems good so far.

**Comment by psavery** [comment]
@joelvbernier Do we want to be able to select multiple atoms in the periodic table for a site, or just one atom for a site? I see the example we have appears to allow multiple atoms in a single site, and then you specify a partial occupancy for each.

**Comment by psavery** [comment]
@saransh13 @joelvbernier Okay, I've got a fair amount of the GUI in place so far.

Here is a site editor:
![Screenshot from 2020-09-09 14-50-17](https://user-images.githubusercontent.com/9558430/92640818-d5e36380-f2ab-11ea-9e55-989cadc15c73.png)

And if you press "Select Atom Types", a periodic table appears where you can select all of the atom types (yellow means it is selected, but we can change that):
![image](https://user-images.githubusercontent.com/9558430/92640878-f0b5d800-f2ab-11ea-8655-b5e1b9dd4632.png)


I'm working now on a way to convert the atom info in the Material [here](https://github.com/HEXRD/hexrd/blob/740d86326da2b687936df7015235d0d127a07ffe/hexrd/material.py#L99-L100), to the symmetry sites in the GUI, and then back to the expanded atom info in the Material class. I think I can do this using the functions and matrices from [hexrd.symmetry](https://github.com/HEXRD/hexrd/blob/master/hexrd/symmetry.py). Let me know if you have any thoughts.

**Comment by psavery** [comment]
I think something like this works, for example, for expanding the sites:
```python
import numpy as np
from hexrd import symmetry

def expand_sites(spgnum, coords):
    return np.matmul(symmetry.GenerateSGSym(spgnum)[0], (*coords, 1))[:, :3]


expand_sites(8, (0.25, 0.25, 0.25))
# [[ 0.25  0.25  0.25]
#  [ 0.75  0.75  0.25]
#  [ 0.25 -0.25  0.25]
#  [ 0.75  0.25  0.25]]

expand_sites(62, (0.33, 0.25, 0.5))
# [[ 0.33  0.25  0.5 ]
#  [-0.33 -0.25 -0.5 ]
#  [ 0.17 -0.25  1.  ]
#  [-0.33  0.75 -0.5 ]
#  [ 0.83  0.25  0.  ]
#  [ 0.33  0.25  0.5 ]
#  [ 0.83  0.25  0.  ]
#  [ 0.17  0.75  1.  ]]

```

**Comment by psavery** [comment]
@saransh13 Or does the material class want the non-expanded version of the sites?

**Comment by psavery** [comment]
Actually, it looks to me from the cif reader that it takes the reduced version of the sites. Let me know if otherwise is true.

**Comment by saransh13** [comment]
@psavery  That looks great! 
We just need the reduced sites, the equivalent positions are calculated inside the unitcell class. 
We also input the thermal factor in U and convert it to B inside the class. The U factor is the standard when reporting the thermal factors.

**Comment by psavery** [comment]
Okay, sounds good.

I let the user choose between "B" or "U" (like Maud does). I'll make "U" the default instead of "B". It will automatically be converted to "U" for the material class.

**Comment by psavery** [comment]
@saransh13 One more question. Do we need the user to specify the total quantity? Or can I get rid of that?

**Comment by saransh13** [comment]
We can get rid of that. I'm not 100%, but I think thats the multiplicity of the atom site.

**Comment by psavery** [comment]
@saransh13 It looks like the Material class is [storing the thermal factor in the atom info as B](https://github.com/HEXRD/hexrd/blob/e028f7747f481462f663002b9fb844a11f667fca/hexrd/material.py#L94-L99), according to the comment above it. Is that correct?

**Comment by saransh13** [comment]
Okay, yeah old comment which I forgot to change. 
If you look at [435] (https://github.com/HEXRD/hexrd/blob/e028f7747f481462f663002b9fb844a11f667fca/hexrd/material.py#L435-L436) in `materials`, that has the correct relation between B and U

**Comment by psavery** [comment]
Okay, I will save them as `U` instead of `B`.

**Comment by joelvbernier** [comment]
Looks so good @psavery !

**Comment by saransh13** [comment]
@psavery latest push should fix the comment and also default values.

**Comment by psavery** [comment]
@saransh13 Oh okay. So there is one U for the whole material, then (not one U for each site)?

**Comment by saransh13** [comment]
Its one U for each site and atom. So two atoms on the same site with partial occupancies can have two different U values.
The default example just has one site with full ocuupancy, so a single U is required.
Sometimes U is defined as a 3x3 symmetric tensor (so 6 independent components) and there is support for this in the material class too.

**Comment by psavery** [comment]
Oh okay, I see. `Material._U` is an array.
