### ISSUE TITLE
Additional LLNL I/O Capabilities

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#488]
In the case of the `PXRDIP` instrument (and possibly others) we need the ability to:

- [x] Adjust the height and/or width of the boundary
- [x] Rotate the image one or more times after crop
- [x] Rotate `PXRDIP` boundary 90 degrees when template is added, then rotate cropped image back -90 degrees

1. In order to adjust panel and crop sizes I would suggest something like the following:
![set_h_w_llnl_io](https://user-images.githubusercontent.com/51238406/91242497-977b6f80-e715-11ea-8f41-53b328b382cb.png)
These values would be automatically populated by the extents of the panel (template) but could be changed to adjusted the size of the panel or the cropped region. Currently the panel size and shape comes from pre-defined templates, and the crop region is automatically calculated from the extents of the panel. If this approach is used:
     - Should the crop region be restricted to being no smaller than the extents of the panel?
     - Should the crop region extents and panel extents be locked together like they are currently? If not any additional space between the panel and cropped region would be masked out like is currently the case for `TARDIS`.

2. In order to allow additional transforms after cropping we could leave the transforms option enabled. Additional transforms could be performed on the cropped image and accepted with the `ok` option before loading/re-loading the next image.
![transform_llnl](https://user-images.githubusercontent.com/51238406/91243170-51bfa680-e717-11ea-92db-7bdb923f3df1.png)

@joelvbernier Let me know if I am understanding the additional needs that you explained correctly and if these options seem like they would work.

**Comment by joelvbernier** [comment]
The TARDIS and XRDT (coming...) panels are very close to the provided boundaries and the circumscribing box shouldn't require modification.  The PXRDIP and BBXRD, however can vary.  The nominal dimensions are maximal; if anything in those cases we'll have to make them smaller (for ref, been using a box specification in ImageJ like you are suggesting above on the fly).  The last piece of the puzzle will be to make sure that the applied rotation for the crop is properly accounted for in the generated detector parameters.  We'll default to instrinsic zxz Euler angles, and the rotation of the template is the parameter -tilt[2].

**Comment by bnmajor** [comment]
Added in #539

**Comment by joelvbernier** [comment]
Oooh, is this ready to merge?

**Comment by bnmajor** [comment]
@joelvbernier Yes, it's merged in and ready to be tested out!

**Comment by joelvbernier** [comment]
ah, I was fooled by the fact this was still an open issue.  Pulling master now...

**Comment by joelvbernier** [comment]
Uh oh -- my TARDIS images are coming in upside down now...  something is broken.  The look ok in the import panel, but then when it loads them, they appear upside down in the raw image view now.

**Comment by psavery** [comment]
@bnmajor Can this be closed now?

**Comment by bnmajor** [comment]
@psavery Yes, this is taken care of.
