### ISSUE TITLE
Add selector to specify different SNIP algorithms

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#491]
There are 2 snip implementations in the code currently, `hexrd.imageutil.fast_snip1d()` and `hexrd.imageutil.snip1d()`; I'd like to add a selector on the polar view tab to toggle between, defaulting to the fast version as it make interaction much smoother.  The non-fast version, however, gives better results, so once a configuration is roughed in I can envision switching.

**Comment by joelvbernier** [comment]
I'll add that we should add the option to run the `snip2d` as well; API can be the same.   I've found a need for it dealing with very high background data.

**Comment by cjh1** [comment]
@joelvbernier Is needed for the demo?
