### ISSUE TITLE
Colormap editor currently not suitable for float images with small intensities

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#511]
The QSpinBox widgets do not allow for adjusting the colormap appropriately for float images.  The fade corrected images in the NIF archive are of float type and I can't set the max appropriately low.  The simplest option would be to replace the widget with a DoubleSpinBox; we could alternatively rescale images, but that might be dicey.  Thoughts?

**Comment by psavery** [comment]
The [ScientificDoubleSpinBox](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/scientificspinbox.py) might be a good option here too. It is currently used in a few parts of the code, including the distortion parameters (see below). It doesn't display trailing zeros, and it allows for scientific notation. 

![Screenshot from 2020-09-11 06-30-10](https://user-images.githubusercontent.com/9558430/92913016-5d3ded80-f3f8-11ea-8277-2d074901fbb4.png)

**Comment by psavery** [comment]
@johnkit Here's one way you can promote the widgets to a scientific spinbox in Qt Designer, that I needed to do in another part of the code.

![promote_to_scientific_double_spin_box](https://user-images.githubusercontent.com/9558430/93328826-44637c80-f7ea-11ea-9c9a-af72a206bafc.gif)

**Comment by johnkit** [comment]
@psavery yes the ScientificDoubleSpinBox works great. Seems too easy.
