### ISSUE TITLE
Overlay fixes for offsets

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#516]
Working on a PR to apply corrections to the angular overlays in the polar view mode consistent with an input offset vector.  The Laue overlays were actually broken in this regard already (_i.e._, wrong behavior when changing the crystal translation).  The issue in the polar view comes from the fact that the polar rebinning is done from the lab reference frame.  If you have a material point in your sample that is **_not_** at the origin -- such as a powder lines coming from a layered sample or a laue pattern from a crystal not at the origin -- the (2θ, η) must be adjusted to reflect this origin offset.  I've written a new function in hexrd.xrdutil to address this.

There is a [draft PR on hexrd](https://github.com/HEXRD/hexrd/pull/102) that includes the new function, as well as the beginning of the new calibration package.  The fixes to the hexrdgui overlays (just powder and Laue for the time being) include:
- [x] fix laue overlay to adjust the angular output using the new `hexrd.xrdutil._convert_angles()` method
- [x] fix powder overlay
- [x] add a translation offset to the overlay manager for powder overlays
The associated PR is linked.

**Comment by psavery** [comment]
@joelvbernier I have a commit that adds the translation offset to the powder overlay editor, and it seems to work. Should I push it to #517?

**Comment by joelvbernier** [comment]
Yes please!  I am pushing a few more commits to #517 right now as well.

**Comment by cjh1** [comment]
@psavery do we still need to add the translation offset?

**Comment by psavery** [comment]
@cjh1 This was added in #527 and #541. Closing this PR.
