### ISSUE TITLE
Laue overlay manager input error

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#518]
The parameters for the tilt (which should be zx'z'' angles in my current test case) don't seeme to be properly cast to grain parameters.  I will make a set of simulated TARDIS images with known perturbations in that context.

**Comment by joelvbernier** [comment]
@psavery -- can you take a look?

**Comment by psavery** [comment]
I'll take a look!

**Comment by cjh1** [comment]
Thanks @psavery

**Comment by psavery** [comment]
@joelvbernier Looks like I had just accidentally left out radians/degrees conversions. Oh unit conversions...

**Comment by joelvbernier** [comment]
I figured that was exactly what it was — still making a pair of test images with know angles to try it out :-)

**Comment by psavery** [comment]
@joelvbernier Yeah, so, the crystal editor for the Laue was displaying radians, even though there was a degree symbol. I'm about to push a fix so it actually displays degrees.
