### ISSUE TITLE
macOS only: snip1d popup only displays once

### ISSUE THREAD

**Issue by johnkit** [HEXRD/hexrdgui#522]
In the polar image mode, the "Show snip1d" button generates and displays a popup window. On macOS, if you close that popup, clicking the "Show snip1d" button again does not re-display the window. Internally I have confirmed that the figure is generated and the matplotlib figure.show() function is called.

**Comment by psavery** [comment]
Possibly related: #204

**Comment by johnkit** [comment]
Yes same thing. Thanks for pointing that out, Patrick.
