### ISSUE TITLE
Add calibration with line pick for each overlay

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#524]
This will go through the overlays, one at a time, and have the user pick lines for each one. For Laue spots, we will need the user pick them in the correct order, so we may need to highlight the width for the overlay to be picked. We will also allow for skipping over certain Laue spots.

**Comment by psavery** [comment]
@joelvbernier Is this going to replace the current line picker in "Run"->"Calibration Line Picker", or will it be a new menu item?

**Comment by joelvbernier** [comment]
Yes; there will be a single workflow for calibration.  We will essentially build the problem by picking a list of material/overlay types.  Then we need to select the data points that will go into each.  We can probably include a toggle to the effect of "include in calibration" in the existing overlay manager.  To flag which materials will get used.

**Comment by psavery** [comment]
Maybe another option is that we could make it so if the overlay is visible, it gets included in the calibration? I can still add another checkbox for "include in calibration" if that is not preferred.

**Comment by psavery** [comment]
I went with "if the overlay is visible, then include it in the calibration", FYI.
