### ISSUE TITLE
When applying a transform to the image in the I/O widget, the colormap ranges get reset. This should be disabled.

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#528]

**Comment by bnmajor** [comment]
@joelvbernier This has been addressed for the case of the LLNL I/O workflow in #529, but this is an issue that would occur if the `Transform Detectors` option is used through the `Edit` menu. Should we disable the color map reset in that case as well?

**Comment by joelvbernier** [comment]
@cjh1 Yes -- since we are just mirroring/rotating the image, we want to preserve whatever cmap limits the user has input.
