### ISSUE TITLE
Redraw of polarview unnecessary in mask application?

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#535]
It seems that when we apply masks, it is actually redrawing the whole polarview.  This is unnecessary, and negatively impacts the UX as it takes a while.  Can't we cast the polar image as a masked array and simple update the mask with the logical and of the active mask layers?  This should play nice with the summing for the lineout.

**Comment by psavery** [comment]
Note that it is currently calling [MainWindow.update_all()](https://github.com/HEXRD/hexrdgui/blob/c968752f64beaebc44fe22cd8b7b2379de09d1ac/hexrd/ui/main_window.py#L773), generating the data, and [setting the data](https://github.com/HEXRD/hexrdgui/blob/c968752f64beaebc44fe22cd8b7b2379de09d1ac/hexrd/ui/image_canvas.py#L508) before re-drawing.

We might be able to skip the re-generation of data by connecting a new signal and slot, similar to what is being done [here](https://github.com/HEXRD/hexrdgui/commit/bd272bd48871369a4276f13597c8a4dbf6b05ffe#diff-21c4e9aa7bfeeb0387bff20dae53aa9eR332-R334) in bd272bd48871369a4276f13597c8a4dbf6b05ffe
