### ISSUE TITLE
Broken LLNL import

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#542]
...At least for TARDIS.  The commits merged in #539 broke the image orientation when finishing the import.  Observe:

from commit  a7bb576168604b46cd34315eff0edf7c3b4b64db I get this proper import of TARDIS data
![Screenshot from 2020-09-18 23-47-24](https://user-images.githubusercontent.com/1154130/93661161-7c490a80-fa0a-11ea-9114-abf0043d05e5.png)

from current master (commit 41c2b6e59b2ecedad7c0d502d8745124718ee7a5):
![Screenshot from 2020-09-18 23-55-39](https://user-images.githubusercontent.com/1154130/93661185-a39fd780-fa0a-11ea-96c7-bb14bf4c2954.png)

Looks like they are getting flipped upside-down.  If I look at the raw mode.  Hopefully a quick fix ;-)

**Comment by bnmajor** [comment]
@joelvbernier You were correct, seems like it was a silly mistake... Looks like it is coming in correctly now. Let me know if you see anything else that seems off
