### ISSUE TITLE
Disable canvas zoom before masking

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#552]

**Comment by psavery** [comment]
I think the toolbars can all be accessed via something like `[x['tb'] for x in ImageTabWidget.toolbars]`. The type of the toolbar is matplotlib's `NavigationToolbar2QT`, which inherits from `NavigationToolbar2`. I guess we'll need to figure out how to programmatically turn off zoom. Maybe we can have `HexrdConfig` emit a signal like `picker_started` and connect to it to turn off the zoom.
