### ISSUE TITLE
Allow log scale to be applied to intensities in the polar view 

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#557]

**Comment by joelvbernier** [comment]
The lineout in the lower axes, that is.

**Comment by psavery** [comment]
I think we'll need to just perform a log on the y-axis of the azimuthal data generated [here](https://github.com/HEXRD/hexrdgui/blob/b31832f4f2e3a6717ef7450c0304dfd46af5d4e2/hexrd/ui/image_canvas.py#L521) and [here](https://github.com/HEXRD/hexrdgui/blob/b31832f4f2e3a6717ef7450c0304dfd46af5d4e2/hexrd/ui/image_canvas.py#L601).

**Comment by cjh1** [comment]
Just log scale the y axes
