### ISSUE TITLE
Specify refinements for Laue overlays

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#561]
Add the ability to specify whether or not various Laue overlay options should be refined in the calibration.

**Comment by joelvbernier** [comment]
I'd like to see a table view of the parameters akin to the WPPF panel.

**Comment by joelvbernier** [comment]
Also...  we need to expose the lattice parameter(s) for the case of powder diffraction overlays.  @saransh13, probably best to go through PlaneData class as PlaneData.lparms is already symmetrically reduced.  There is also logic in the material panel to cast the proper parameters names to the reduced list associated with the lattice type, a, b, c, &alpha;, &beta;, &gamma;.

**Comment by joelvbernier** [comment]
Looks like [spacegroup](https://github.com/HEXRD/hexrdgui/blob/b31832f4f2e3a6717ef7450c0304dfd46af5d4e2/hexrd/ui/material_editor_widget.py#L124) knows how to parse the space group dependent number of reduced lattice parameters

**Comment by psavery** [comment]
@joelvbernier Do you mean we need refinements for the lattice parameters?

The lattice parameter values themselves are currently exposed on the materials panel.

![Screenshot from 2020-09-23 20-51-20](https://user-images.githubusercontent.com/9558430/94088490-9ace4d80-fdde-11ea-9c41-ce7b8f2f67c0.png)

**Comment by joelvbernier** [comment]
@psavery -- we need access to the lattice parameter only for the powder overlays.  It might be faster to just update the lattice parameter for the PlaneData object used to draw the overlays (and passed to the optimization) rather than modifying the material itself.  Not necessary for the Laue (Laue is insensitive to unit cell volume...)

**Comment by psavery** [comment]
Here's what the refinement editor looks like in the powder overlay editor in #568 

![image](https://user-images.githubusercontent.com/9558430/94337731-ce65cf00-ffba-11ea-9b56-ba1740407ed0.png)
