### ISSUE TITLE
Exception when clicking on translate button in load data panel

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#564]
Traceback (most recent call last):
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/import_data_panel.py", line 249, in setup_translate
    self.it.disconnect_rotate()
  File "/home/cjh/work/source/hexrdgui/hexrd/ui/interactive_template.py", line 251, in disconnect_rotate
    self.parent.mpl_disconnect(self.button_drag_cid)
AttributeError: 'InteractiveTemplate' object has no attribute 'button_drag_cid'

**Comment by joelvbernier** [comment]
Yep, seen this too.

**Comment by bnmajor** [comment]
@cjh1 @joelvbernier Do you know what steps you took before getting this error? I haven't been able to reproduce on my own so far.

**Comment by joelvbernier** [comment]
@bnmajor -- Here are the steps.  I get it if I load an image, then click the translate button (even though it appears to be already selected).   Translate will not work, unless I click the rotate button and then the translate button again.  I'm trying to do a screen capture on my janky linux laptop.  I'll update the comment with a vid if I get it working.

**Comment by bnmajor** [comment]
@joelvbernier Thanks, that's perfect, I can replicate it now. I've added a fix in #567
