### ISSUE TITLE
"Reset Range" in colormap widget not using log scale if checked

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#579]
Just noticed that the "reset range" button is not working as expected if log scaling is checked; I would anticipate it would reset the range based on the current image, but it appears to be tied to the as computed image with unscaled intensities.  Probably an easy fix.

**Comment by psavery** [comment]
Yeah, so it is actually using the underlying image data for the range. And the log scale in the color map editor doesn't currently affect the underlying data - it only affects the color map. This is the same reason also why it doesn't affect the azimuthal integral data at the bottom. [`matplotlib.colors.LogNorm`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.colors.LogNorm.html) is the class that is currently being used.

**Comment by cjh1** [comment]
Yes, as @psavery describes. We are not actually performing the log operation on the data, this is all handle by matplotlib. If are going to log the data, we should probably move the log control outside the colormap controls and display the scaled values.

**Comment by cjh1** [comment]
Related to #557
