### ISSUE TITLE
RuntimeWarning in overlays preventing rendering of powder overlays?

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#586]
I have an unremarkable material selected (BCC with 2.5Å lattice paramter) on a TARDIS instrument, and it wont draw.  THe following is echoed to the terminal:

```
/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_canvas.py:237: RuntimeWarning: Mean of empty slice
  x = np.nanmean(x)
```

This is a mac, so perhaps a Mac issue?

**Comment by psavery** [comment]
[This stackoverflow issue](https://stackoverflow.com/questions/29688168/mean-nanmean-and-warning-mean-of-empty-slice) seems to indicate that happened for them when it was done on a list of `NaN`s (no real values). Maybe the reason it isn't drawing anything is because they are all `NaN` values?

**Comment by joelvbernier** [comment]
shouldn't be -- or rather I can't see how they would be.  All real 2&theta; values in the materials table for the overlay.

**Comment by psavery** [comment]
I studied this error further, and I saw that "Mean of empty slice" literally means there's no data.

The problem is usually that there is a detector where all of the lines for a powder overlay are out of bounds, which sometimes happens. I'm going to close unless this issue arises again.
