### ISSUE TITLE
Autosize table to widget in Overlay Manager

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#587]
Need same fix as the image load dialog, where the table columns autosize to the embedded widget:
![Screen Shot 2020-09-25 at 9 11 22 AM](https://user-images.githubusercontent.com/1154130/94290567-3959cc00-ff0f-11ea-8e3a-ac1c4000c819.png)

**Comment by bnmajor** [comment]
@joelvbernier I wasn't actually able to reproduce this issue but either way #590 should fix the problem.
