### ISSUE TITLE
Overlays in raw mode not updating with change of instrument parameters

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#592]
Could be a Mac specific issue?  I am running in a clean env with our special python 3.8.4 on 10.15.7

**Comment by joelvbernier** [comment]
@saransh13 confirmed the same behavior on 10.14

**Comment by psavery** [comment]
This might be a mac-specific issue. I don't think I can reproduce it on Linux.

@saransh13 @joelvbernier If you are still experiencing it, can one of you send a detailed example and/or a gif of how to reproduce it?

**Comment by joelvbernier** [comment]
Happening on windows too.  Overlays do no update while in the raw view if you change any of the instrument parameter sliders.  Polar view updates, but raw only updates (_i.e._, the overlays) if you re-select the raw view tab after switching to polar or cartesian (where applicable) the switching back.

**Comment by saransh13** [comment]
![out](https://user-images.githubusercontent.com/15834451/94586709-67ece500-0236-11eb-9a32-7d868f6b84c3.gif)
