### ISSUE TITLE
No way to re-raise closed dockable widgets

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#599]
Just noticed this, at least on Windows: If I close any of the dockable widgets (colormap, image mode, or the tabbed configuration widget), there doesn't appear to be any way to reopen them without quitting/restarting the GUI.  Can we change this behavior?  Perhaps we can put visibility controls in the "view" menu item?

**Comment by psavery** [comment]
I think this is a problem for all platforms. We never added a way to bring them back if they are closed.

**Comment by cjh1** [comment]
@joelvbernier Is this vital for the demo, I don't think we will get to it.

**Comment by joelvbernier** [comment]
No -- I'll just mention that it is slated to get fixed in case.  An inconvenience, not an error.  Removing the demo tag.
