### ISSUE TITLE
In new Material gen, dmin coming from "limit active" checkbox, not mind-spacing spin box

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#601]
Was just generating a new material, and it has the default 1.0Å in the Min d-spacing spin box.  However, when I open the materials table, it shows reflections generated out to the 0.72Å Min d-spacing in the "Limit Active" controller.  Precedence issue?  If I update the space group info dmin spin control, it works -- just a matter of the initial value.

**Comment by psavery** [comment]
Yeah, that sounds like maybe the plane data wasn't updated to have a limit of 1.0Å. I haven't been able to reproduce it on a quick try. If you can give us exact steps, let us know.

**Comment by joelvbernier** [comment]
This is weird -- not reproducing.  Will keep my eyes on the lookout for it...   ¯\_(ツ)_/¯
