### ISSUE TITLE
Polar view not redrawing after changing instrument parameters in Instrument Tree or Form

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#607]
Just noticed this.  The overlays change, but the polar image doesn't get updated if you change instrument parameters in the Tree or Form views, just the Slider View.  Simple fix I am sure.

**Comment by psavery** [comment]
Which parameters were you changing? The beam vector? It looks like I can reproduce this issue for the beam vector...

**Comment by joelvbernier** [comment]
Any.

**Comment by psavery** [comment]
Yeah, I get the same experience here. Looks like if you have "Show Live Updates" enabled, everything causes an update for me except the beam vector.

**Comment by joelvbernier** [comment]
Why is that treated differently that the other parameters with regards to the update?

**Comment by psavery** [comment]
Not sure, I'll take a look

**Comment by psavery** [comment]
So, the raw view and the cartesian view don't need to be redrawn when the beam vector changes, but only the overlays need to be updated. We were accidentally extending that to the polar view as well for the form and tree views. #614 should now always update the polar view no matter where the beam vector gets changed.
