### ISSUE TITLE
Labels for masking options are swapped

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#618]
In the Edit &#8594; Masks menu, the labels for options "Apply Mask to Polar" and "Apply Polygon Mask" are a bit misleading.  The former is in fact the hand-drawn polygonal mask, and the latter is the mask by shape (ellipse or rectangle).

I suggest the following renames in the ui form:

- **Apply Mask to Polar &#8594; Apply Polygon to Polar**
- **Apply Polygon Mask &#8594; Apply Ellipse/Rectangle to Polar**

Sound good?

**Comment by bnmajor** [comment]
@joelvbernier Sounds good. `Apply Polygon Mask` is available in raw view as well though, would something like `Apply Ellipse/Rectangle Mask` be okay? Or should masking by polygon be toggled off in raw view for now?

**Comment by bnmajor** [comment]
#619 fixes this using `Apply Ellipse/Rectangle Mask` instead of `Apply Ellipse/Rectangle to Polar` but this can be tweaked if needed, very quick fix.
