### ISSUE TITLE
Use passed in hkls for calibrating powder overlays

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#633]
The PowderCalibrator currently [grabs the hkls from the plane data](https://github.com/HEXRD/hexrdgui/blob/40abd5f8cd6ebef9340e3eee9e66697b46aee6d2/hexrd/ui/calibration/pick_based_calibration.py#L269), rather than using the hkls that get passed (in the `hkls` key for each of the [picks that get passed in](https://github.com/HEXRD/hexrdgui/blob/40abd5f8cd6ebef9340e3eee9e66697b46aee6d2/hexrd/ui/calibration/pick_based_calibration.py#L438)).

This works fine as long as there aren't any powder overlays that have too small of a two theta so that it does not intersect with one of the detectors.

However, we will probably want to modify it to start using the hkls that get passed in, so that this edge case issue is avoided. See an [example of the LaueCalibrator using the passed in hkls](https://github.com/HEXRD/hexrdgui/blob/40abd5f8cd6ebef9340e3eee9e66697b46aee6d2/hexrd/ui/calibration/pick_based_calibration.py#L156). Just need to do something similar for powder.

**Comment by joelvbernier** [comment]
I'll make a PR for this today Patrick -- remind me, was the empty list fix merge for the powder so that there is always a 1:1 match between hkls and picks for a detector?

**Comment by psavery** [comment]
This was fixed by #638
