### ISSUE TITLE
WPPF refinement flags

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#639]
Looks like WPPF is refining phase lattice parameters even when I check the "vary" box off. You should check how the flags are being captured by the GUI, as well as the use inside WPPF.

**Comment by saransh13** [comment]
This works fine in the command line. I think its because the value of `vary` for each key from this table is not updated in the `LeBail.params[key].vary` . @psavery can you check? Check should correspond to `True` and unchecked should mean `False`.

**Comment by psavery** [comment]
Sounds good. From our discussion, it sounds like the GUI is not setting the initial value that is from hexrd.

**Comment by saransh13** [comment]
I tried, but couldn't figure out where it would be going wrong!
