### ISSUE TITLE
Look at optimizing fit_grain_FF_reduced ( this is in hexrd )

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#651]
Simple first step, remove the dump to file system:  https://github.com/HEXRD/hexrd/blob/2ee9f3bcb42ed4328b930dd68acf65da7e127125/hexrd/fitgrains.py#L155-L161

**Comment by psavery** [comment]
So, those lines of code actually *load* an overlap table from the file system.

I wonder if the overlap table is actually even being dumped to the filesystem now. That looks like the only place in the code where that file is being used.
```bash
$ grep -r 'overlap_table' ./*
./hexrd/fitgrains.py:                            det_key, 'overlap_table.npz'
```

I wonder if we should either:
1. Just remove the `overlap_table` block of code entirely.
2. Add a way to pass the overlap table as an argument to the function instead.

**Comment by joelvbernier** [comment]
The overlap table code stays -- it is a refined analysis step that hasn't quite made it's way into the standards workflow, but we should talk a bit more about this.

**Comment by joelvbernier** [comment]
@psavery -- we can certainly modify this to be passed as an arg.

**Comment by psavery** [comment]
We've been optimizing fit grains in a variety of other PRs and issues. Closing this one for now.
