### ISSUE TITLE
Add menu to run fit grains directly

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#652]

**Comment by psavery** [comment]
@joelvbernier So the grain fitting currently uses the following output from the indexing:

1. Eta omega maps (to generate `min_samples, mean_rpg`).
2. Completeness 
3. `qfib`

When we run fit grains without indexing, where do we get these different pieces of info from?

I see that completeness is in the grains.out file. Does qfib come from a file we are currently not writing out in the GUI, like `accepted_orientations*`? I'll get the user to select all the files they need to.

**Comment by joelvbernier** [comment]
A few things regarding grain fitting: this procedure (`hexrd fit-grains`) does **not** use the eta omega maps, completeness, or qfib, those are purely for the indexing step.  In general, what is required to fit a grain is are

- the orientation
- centroid
- strain
- imageseries.omega.OmegaImageSeries class
- PlaneData class

The CLI is set up to get this orientation from the `config` class, plus flags.  If the fitting has not been performed, or the `--clean` flag is issued, the `accepted_orientations_*.dat` file is used for the grain orientations along with trivial guesses for the centroids and strains (this is the default).  Alternatively, if a `fit_grains:estimate` exists, this information is obtained from the specified  `grains.out` file.

The process is two-step: first, `HEDMInstrument.pull_spots()` is executed to extract the _measured_ G-vector positions from the image stack (this is the data that goes into the `spot_XXXXXX.out` files),  Then a non-linear least-squares fit is performed between the simulated and measured positions.  The results are captured in the `grains.out` file.

There are additional options in the `fit_grains` block to control the data extraction/fitting process, namely specification of the angular tolerance windows to use in the imageseries around each simulated G-vector coordinate, and a "refit" tolerance `[m, n]`, which, if specified, performs the fitting again but excludes G-vectors whose measured and simulated coordinates differ by more than `m` pixels in `(x, y)` and `n` frames (_i.e._, an &omega; tolerance).  There is also a path for loading an overlap table, which is currently not part of the "standard" analysis, but I want to get it incorporated.

Does that help clarify things?

**Comment by psavery** [comment]
@joelvbernier Yeah, that sounds good. Sorry Joel, we have a [`run_fit_grains()`](https://github.com/HEXRD/hexrdgui/blob/8c006bf33432c084cd5cf6de7b5d50927a590e9c/hexrd/ui/indexing/run.py#L171) function in our code that calls [`run_cluster()`](https://github.com/HEXRD/hexrdgui/blob/8c006bf33432c084cd5cf6de7b5d50927a590e9c/hexrd/ui/indexing/run.py#L197), so I assumed that was part of the grain fitting process.

I'll just need to get the user to select the appropriate options, then, and create the `grains_table` to pass to [`fit_grains()`](https://github.com/HEXRD/hexrdgui/blob/8c006bf33432c084cd5cf6de7b5d50927a590e9c/hexrd/ui/indexing/run.py#L217), then.
