### ISSUE TITLE
Add table to edit elastic moduli to the material panel

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#653]
- Will be used to convert stress to strain
- Add "Properties" tab to panel
- 6 x 6 matrix
- Look at https://github.com/HEXRD/hexrd/blob/master/hexrd/unitcell.py
- Tooltip to warn user to enter using Voigt notation

**Comment by psavery** [comment]
@saransh13 For the default values of the stiffness tensor, should we have some kind of reasonable defaults in the `materials.h5` file for each material? Or default to all zeros? Or something else?

**Comment by saransh13** [comment]
@psavery I think we can include some default values for each material. This will require addition on an additional data field in the file and digging up those values from a handbook. We could do a check if `stiffnessmatrix` data field is present for a group. If yes, then read from the table, if not then we can just fill zeros. Does that sound reasonable?

**Comment by psavery** [comment]
Sounds good to me!
