### ISSUE TITLE
Display density in Materials Tab

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#659]
Can we add a field that displays the density in the material tab. This value can be found in `Material.unitcell.density` property. The value is recomputed when spacegroup or lattice parameter is changed. 
PR 137 in hexrd does this update. ('don't know how to tag a PR in a different repo).

@note: density should also be updated when `Material.unitcell.atom_type`, `Material.unitcell.atom_ntype' or `Material.unitcell.atom_pos' is updated, but these are not properties yet. A fix will be pushed soon.

**Comment by psavery** [comment]
You can tag PRs in other repos like `owner/repo_name#num`. So, in this case, hexrd/hexrd#137.

If you have permissions to edit people's comments on a GitHub repo, you can also see their markdown "source" so you can see how they did it.

**Comment by psavery** [comment]
@saransh13 I think this could either go in the general tab or the properties tab. Although, there is definitely more room in the properties tab. Let me know if you have a preference.

General Tab
==========
![Screenshot from 2020-11-17 20-20-08](https://user-images.githubusercontent.com/9558430/99475398-13034c00-2914-11eb-8871-69878e0169fe.png)

Properties Tab
===========
![Screenshot from 2020-11-17 20-34-08](https://user-images.githubusercontent.com/9558430/99475493-47770800-2914-11eb-8958-559d82379136.png)

**Comment by saransh13** [comment]
Maybe next to the max 2theta/min d-spacing could be good spot. If there's not enough space, then we can definitely put in in the properties tab. What do you think @psavery @joelvbernier ?

**Comment by joelvbernier** [comment]
Can go in properties I think.  Were you think gm/cc for units?

**Comment by saransh13** [comment]
Yeah g/cc should be good. The density is calculated in these units.
