### ISSUE TITLE
Allow sort of fit grains table by t_vec_XXX columns

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#677]

**Comment by psavery** [comment]
We might just need to add these columns [here](https://github.com/HEXRD/hexrdgui/blob/8c006bf33432c084cd5cf6de7b5d50927a590e9c/hexrd/ui/indexing/fit_grains_results_dialog.py#L346-L352) and [here](https://github.com/HEXRD/hexrdgui/blob/8c006bf33432c084cd5cf6de7b5d50927a590e9c/hexrd/ui/indexing/fit_grains_results_dialog.py#L168-L175).
