### ISSUE TITLE
Add toggle option to use cylindrical reference frame

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#678]

**Comment by psavery** [comment]
@joelvbernier Can we get the math for this again?

**Comment by joelvbernier** [comment]
The tvec_c components are in order (**X**, **Y**, **Z**);  we will report out coordinates (&rho;, &phi;, **Y**).

- In our case, **Y** is the cylinder axis and will remain unchanged in the transform.
- the radius &rho; is calculated as `np.sqrt(x*x + z*z)`
- the azimuth &phi; is calculated as `np.arctan2(z, x)`
