### ISSUE TITLE
Allow user to select a point on the 3D plot and highlight the grain in the table

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#680]
We will need to check if matplotlib will let use do this.

**Comment by psavery** [comment]
To leave some notes here:

I am able to do most of this by first adding as a kwarg to `scatter3D()` `'picker'=True`, then
connecting to pick events via `canvas.mpl_connect('pick_event', self.point_picked)`.

When I get the pick event, there is an index associated with it, which appears like it is
supposed to match the index of the original data used to create the plot. However,
the index does not match for some reason. This could be a bug in matplotlib, I'm
not sure.
