### ISSUE TITLE
Look at adding the "tight axes" when saving plots

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrdgui#681]

**Comment by psavery** [comment]
Right now, all of the code that is ran when you press the "Save" button is in matplotlib. So we will also need to come up with a way to override the matplotlib function. Maybe by overriding the function in our [child class](https://github.com/HEXRD/hexrdgui/blob/8c006bf33432c084cd5cf6de7b5d50927a590e9c/hexrd/ui/navigation_toolbar.py#L6).
