### ISSUE TITLE
Detector selector not updating with change of instrument config values

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#702]
@bnmajor: I noticed that the detector keys in the Detector selector on the Multiframe Options panel in the Load Data widget do not get updated; neither in the case where detector keys are edited live in the GUI (e.g. adding detectors live or renaming existing ones in the Instrument Config form) nor in the case where a new (different) config is loaded.  I am not sure to the extent this badness propagates downstream in the workflow yet, but seems like it should be an easy fix.

**Comment by psavery** [comment]
@bnmajor There is a signal coming from `HexrdConfig` named `detectors_changed` that gets emitted when detectors are changed (added, removed, or renamed). I think you can connect to that.

**Comment by bnmajor** [comment]
@psavery Thanks! I connected to that signal, was a very simple fix. I thought I remembered adding that connection in in the past but either I'm mistaken or it got lost somewhere along the way...

Either way it seems to work as expected now. Added, removed, or renamed detectors are updated in the menu, and the list of options is updated for new configs @joelvbernier
