### ISSUE TITLE
Add structure factor column to materials table 

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#703]
This would be a useful feature, particularly if we could also sort the reflections based on the values.  The values in question are a property on the PlaneData object: `PlaneData.structFact`

**Comment by psavery** [comment]
Okay. Adding the column shouldn't be too much work. Being able to sort based on it might be just a little more, since I think it is currently assuming internally that the order of rows doesn't change.

**Comment by psavery** [comment]
@saransh13 What are the units of the structure factor? And, what would be a good column header? `F`?

**Comment by joelvbernier** [comment]
No units, and “|F|^2”

**Comment by saransh13** [comment]
I'm wondering if we should normalize structure factors to 0-100? The absolute numbers don't matter anyways.
So the numbers to display would be `100*sf/sf.max()`
