### ISSUE TITLE
Save analysis option for saving everything in one HDF5 file

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#705]
Adding a save analysis button to save everything (detector configuration, associated image files, image processing parameters, polar view parameters, materials etc.) in single HDF5 file. This makes it easier to save the state of the analysis at a particular time and allows the user to continue from where they stopped last time. We can also do this periodically to make sure that analysis is saved and no work is lost in case the program crashes etc.

This was a highly requested feature from users.

**Comment by joelvbernier** [comment]
Agreed.  There are a few other pieces that we need to be able to expose to the user before we get here (_e.g._ the calibration point lists).  We need to formalize what this will encompass.

**Comment by psavery** [comment]
So, a lot of the state of the program is stored inside the [HexrdConfig class](https://github.com/HEXRD/hexrdgui/blob/778134d397bd0a3562204ddf432ab7eab9cf15de/hexrd/ui/hexrd_config.py#L40).

In fact, a lot of state is stored in [this config dict](https://github.com/HEXRD/hexrdgui/blob/778134d397bd0a3562204ddf432ab7eab9cf15de/hexrd/ui/hexrd_config.py#L133). The materials, instrument/detector config, image config, indexing config, etc. are stored inside that one dict. There are a few things stored outside of it, such as [the imageseries](https://github.com/HEXRD/hexrdgui/blob/778134d397bd0a3562204ddf432ab7eab9cf15de/hexrd/ui/hexrd_config.py#L140) and [overlays](https://github.com/HEXRD/hexrdgui/blob/778134d397bd0a3562204ddf432ab7eab9cf15de/hexrd/ui/hexrd_config.py#L155).

These are just some notes for when we implement it.

**Comment by psavery** [comment]
@joelvbernier do you think we can close this issue now? We have a state file. It is missing some things like HEDM, but that is a separate issue (#1100).

**Comment by psavery** [comment]
I believe we have this now in the form of state files! Feel free to re-open if not...
