### ISSUE TITLE
Detector boundaries in PXRDIP import are rotated 180°

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#707]
@bnmajor -- I just went and added the notched corners to the PXRDIP detector boundaries, and I noticed that the import tool is drawing them in the raw view rotated 180°.  The cropping is transformin things properly, it is just that the outlines are being drawn rotated +90°, when they should be drawn in the raw view rotated -90°.

We have a PXRDIP demo session for a group at 1pm; any chance we can get this fixed before then?

![pxrdip_boundary_in_raw](https://user-images.githubusercontent.com/1154130/104497011-9779f000-558e-11eb-8f2d-2b48280c626a.PNG)

**Comment by bnmajor** [comment]
@joelvbernier I'm sorry, I was in a meeting when this came in - I've pushed the fix in #709 and can get that merged in if it looks good to you
