### ISSUE TITLE
Site editor in structure tab not accepting coord modifications

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#711]
Changes in fractional coordinates are not accepted.  I loaded a material archive and attempted to modify atom coordinates. They get overwritten by the as-loaded values when you toggle back and forth between another site.   See screen cap below.  
![Screen Recording 2021-01-19 at 08 31 41 83 PM](https://user-images.githubusercontent.com/1154130/105127402-b21ffd80-5a95-11eb-8183-437822b9cbaf.gif)

**Comment by joelvbernier** [comment]
Edit: same behavior if you try to make a new material; you are stuck with the coords of the most recent active material and cannot change them.  Also, there is some very strange mouse behavior going on; notice I _am not_ holding Ctrl or Shift, and left mouse is selecting multiple sites.
![Screen Recording 2021-01-19 at 08 29 49 52 PM](https://user-images.githubusercontent.com/1154130/105128117-3aeb6900-5a97-11eb-9283-086734aa68e2.gif)

**Comment by psavery** [comment]
@joelvbernier I think this might be happening because of #513. Out of the default materials, ruby and forsterite are the two that have a "U" that is a symmetric tensor rather than a single value, and we hadn't yet built in a way to deal with a U that has a symmetric tensor. If you make a new material, it copies over the old material, so it may also have a symmetric tensor U.

Can you give this a try with any of the other materials, other than ruby and forsterite, to see if modifying the fractional coordinates works?

**Comment by joelvbernier** [comment]
@psavery: I played with Si (which uses isotropic B) and get the same weirdness.  Not sure why the mouse left click is behaving like Ctrl+click if I add sites and try to switch between them.  I also, edits to any site (if I add more than the one) edit all the sites.

@saransh13, can you help Patrick with this?  Neither the 0.8 nor the current master GUI has a functional structures tab.

**Comment by saransh13** [comment]
@psavery let me know how I can help. I can't reproduce this on OSX.

**Comment by joelvbernier** [comment]
Confirmed the same behavior on Linux, using the ruby as an example.

**Comment by joelvbernier** [comment]
Am I wrong in stating that our current interface has a fundamental problem w.r.t. inputting U tensor values?  We only have a scalar spin box...

**Comment by psavery** [comment]
Yeah, it looks like trying to view a site that had a tensor U put the structure editing tab in a bad state, and caused a lot of bugs. #712 prevents us from getting into this bad state. However, we should still add a tensor editor soon (tracked in #513).
