### ISSUE TITLE
Load Data options reverting to defaults upon reloading imageseries

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#713]
Noticed this bug working with Darren today: if you load and imageseries with a set of processing options (aggregation, transform, dark), then load a new imageseries (for the same instrument), the options are reverting to the default values but the selectors are not changing.  For example, if I loaded an imageseries with max aggregation, loading a new file set will load without aggregation even though the selector still reads max aggregation.  Same with the dark; if I've previously set it to None, then it performs Median despite the fact the selector still shows None. The only way to get it to perform the options the selectors indicate is to toggle the "apply to all detectors" checkbox and re-select the desired options.

The desired behavior is for the current selections to be "sticky" so that you can load different datasets for the same instrument without having to reset all the selectors.

**Comment by cjh1** [comment]
@bnmajor Is going to take a look at this.

**Comment by bnmajor** [comment]
@joelvbernier Would you be able to give me some more details (which config and images maybe) around the case you were testing when you saw this behavior? I've tried with a few different configuration files and imageseries and haven't been able to reproduce these issues.

Each time I tried to reproduce:
- `Apply Selections to All Detectors` was selected (but never toggled on/off after the initial selection)
- Aggregation and/or dark mode are set (and then not changed)
- Images are selected
- Files are read in

Once the images were loaded:
- Select new images
- Read the files

Images appear to be correctly aggregated and have the correct dark mode applied.

**Comment by joelvbernier** [comment]
Screen cap won't work because it takes too long, but I'll give you an example
