### ISSUE TITLE
exclusions error in GUI based map generation

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#734]
I have an example where I selected a non-sequential list of hkl:
![image](https://user-images.githubusercontent.com/1154130/106712917-84b37380-65ae-11eb-8318-7a1690924fa0.png)

This is supposed to set the exclusions on the `PlaneData` object; the indices for making the maps would are simply sequential on the masked list [0, 1, 2, 3, 4].  It looks like unmasked indices are being headed to `generate_eta_ome_maps`
```
Traceback (most recent call last):
  File "c:\users\berni\onedrive\documents\github\hexrdgui\hexrd\ui\async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\berni\onedrive\documents\github\hexrdgui\hexrd\ui\indexing\run.py", line 99, in run_eta_ome_maps
    self.ome_maps = generate_eta_ome_maps(config, save=False)
  File "c:\users\berni\onedrive\documents\github\hexrd\hexrd\findorientations.py", line 506, in generate_eta_ome_maps
    [str(available_hkls[i]) for i in active_hkls]
  File "c:\users\berni\onedrive\documents\github\hexrd\hexrd\findorientations.py", line 506, in <listcomp>
    [str(available_hkls[i]) for i in active_hkls]
IndexError: index 5 is out of bounds for axis 0 with size 5
```

**Comment by psavery** [comment]
It looks like in hexrd, sometimes the `active_hkls` indices refer to indices with exclusions and tThMax already applied (`plane_data.hkls`, [example](https://github.com/HEXRD/hexrd/blob/f1549eeb128f552484cb03823697a02ee550cced/hexrd/findorientations.py#L501-L509)), and sometimes they refer to indices without exclusions and tThMax applied (`plane_data.hklDataList`, [example](https://github.com/HEXRD/hexrd/blob/f1549eeb128f552484cb03823697a02ee550cced/hexrd/findorientations.py#L589)).

We are doing the former. For now, I can pass in `hkls` to [generate_eta_ome_maps](https://github.com/HEXRD/hexrd/blob/f1549eeb128f552484cb03823697a02ee550cced/hexrd/findorientations.py#L489) as a fix. But which should `active_hkls` refer to? Indices with exclusions and tThMax applied, or without exclusions and tThMax applied?
