### ISSUE TITLE
Need interface to specify map indices for seeded search 

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#735]
In the HEDM config YAML, the indices under `find_orientation:seed_search_hkl_seeds` allows specification of a subset of maps to use for the seeded search.  We typically only use the first 2 or 3 maps, not all.  There is currently no attribute for setting this list in the GUI -- is it running `generate_orientation_fibers` on all the maps?

**Comment by psavery** [comment]
@joelvbernier Yes it is currently using all the maps. I will add an option to specify this.
