### ISSUE TITLE
New WPPF warning

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#741]
Now when I select WPPF, I get a warning in a dialog; not sure why.  This is occurring just in bringing up the WPPF widget, _not_ in executing the fit.  Initialization error @saransh13?
![Screen+Recording+2021-02-03+at+01 10 44 86+PM](https://user-images.githubusercontent.com/1154130/106810689-2b852780-6622-11eb-8625-5414d471bef9.gif)

**Comment by psavery** [comment]
@saransh13 FYI, when the dialog is first initialized, it creates a LeBail object so that the dialog can see the material options that the LeBail object adds (such as `gold_a`), and add them to the table also. It only initializes the `LeBail` class, it doesn't call functions on it.

I'm guessing that error is coming from the `LeBail` initialization?

**Comment by saransh13** [comment]
@psavery I think we can skip the LeBail initialization and initialize the extra parameters from the list of `Material` class objects itself. Theres also some modifications to be made for reading in the parameters for the `Rietveld` method. The `Rietveld` method has a slightly different list of parameters compared to the `LeBail` class. Need some help with that though.

**Comment by psavery** [comment]
@saransh13 Okay. [Here](https://github.com/HEXRD/hexrdgui/blob/master/hexrd/ui/resources/calibration/wppf_params.yml) is a yaml file that contains the list of defaults for the LeBail table. We will probably make another yaml file for Rietveld, and when the user switches methods, load the defaults from the respective yaml file and populate the table.

**Comment by saransh13** [comment]
@psavery I have a WPPF-update branch which updates the default parameter list and adds the rietveld.yml file containing the default parameters for that class.

**Comment by psavery** [comment]
Sure! Let me know when you have the method to generate the extra parameters from a list of Material objects.

**Comment by saransh13** [comment]
ok the function `add_material_parameters` [here](https://github.com/HEXRD/hexrdgui/blob/WPPF-update/hexrd/ui/calibration/wppf_options_dialog.py) should work. Warning that I haven't actually tested it. But if there are any syntax error, it should be minor.

**Comment by saransh13** [comment]
ok the function `add_material_parameters`line 424 [here](https://github.com/HEXRD/hexrdgui/blob/WPPF-update/hexrd/ui/calibration/wppf_options_dialog.py#L424) should work. Just a warning that I haven't actually tested it. But if there are any syntax error, it should be minor.

**Comment by saransh13** [comment]
ok the function `add_material_parameters`line 424 [here](https://github.com/HEXRD/hexrdgui/blob/WPPF-update/hexrd/ui/calibration/wppf_options_dialog.py) should work. Just a warning that I haven't actually tested it. But if there are any syntax error, it should be minor.

**Comment by joelvbernier** [comment]
Test it.

**Comment by psavery** [comment]
This issue gets fixed by #794.

> i think we also need to save the classes after the refinement finishes and create a button for resetting the model (initializing a new one). The `Rietveld` model is performed as a series of refinement with different refinement flags turned on or off so we don't have to initialize it every time.

I'm gonna make a new issue for this change.
