### ISSUE TITLE
Polar view SNIP fixes

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#750]
- [x] Make 'Show SNIP' behavior match applying the SNIP (fixed by #988)
- [ ] Export SNIP background when exporting the polar image
- [ ] Export polar image without masks applied, and export the masks separately

Currently, the 'Show SNIP' behavior doesn't match the 'Apply SNIP?' behavior when 'Apply SNIP?' is unchecked. 'Apply SNIP?' will apply the FAST_SNIP_1D with zeros instead of NaNs. Also, the snip algorithm is ran before the user-defined masks are applied for `Apply SNIP?`, but the snip algorithm is ran after the user-defined masks are applied for `Show SNIP` without `Apply SNIP?`.

We should make the behaviors match.

**Comment by joelvbernier** [comment]
Regarding the user-defined masks; exclude those from the SNIP calculations.  The user-defined masks are often used to remove artifacts introduced at the edges by the SNIP convolution.  Also, FAST_SNIP_1D cannot handle NaNs, which necessitates the fill with zeros.

**Comment by psavery** [comment]
We might need to keep a deep copy around of the un-modified polar image so that the `Show SNIP` can access it. If you do this, feel free to put it in the [PolarView](https://github.com/HEXRD/hexrdgui/blob/36831d1fc8360ee26dae12b6cd8199b0356817f2/hexrd/ui/calibration/polarview.py#L28) class and set it in the `PolarPlot class somewhere around [here](https://github.com/HEXRD/hexrdgui/blob/36831d1fc8360ee26dae12b6cd8199b0356817f2/hexrd/ui/calibration/polar_plot.py#L44). Then, it can be accessed [here](https://github.com/HEXRD/hexrdgui/blob/36831d1fc8360ee26dae12b6cd8199b0356817f2/hexrd/ui/image_canvas.py#L790) for the `Show SNIP`.

I am also happy to work on this if you would like. Just let me know who should work on it.
