### ISSUE TITLE
Save/load image data when closing/opening the application

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#751]

**Comment by joelvbernier** [comment]
current imageseries objects -- or at least I think everything is stored as imageseries, even single frames, correct @psavery?

**Comment by psavery** [comment]
Yes, I took a quick look. Most things are `ProcessedImageSeries` objects. If we save them and load them back in, they will probably be something else, like `FrameCacheImageSeriesAdapter`. Hopefully that will be okay?

It looks like if we aggregate images, they are saved as `np.ndarray`. So that will be straightforward to save/load. And, when we aggregate images, the unaggregated images are also kept around. I think we can save/load those as well.

**Comment by joelvbernier** [comment]
Perhaps raise the option to save the full unaggregated imageseries in a "fat" save?

**Comment by psavery** [comment]
@joelvbernier I think this issue is more about just regular close/open of the program rather than a state file. #1122 is the state file one.

**Comment by cjh1** [comment]
State serialization gets us close enough.
