### ISSUE TITLE
Warning when mouse first moves over masked intensity

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#752]
This warning gets produced the first time a user moves their mouse over a masked intensity:
```python
/home/patrick/virtualenvs/hexrd/src/hexrdgui/hexrd/ui/main_window.py:888: FutureWarning: Format strings passed to MaskedConstant are ignored, but in future may error or produce different behavior
  labels.append('value = {:8.3f}'.format(info['intensity']))
```

It looks like it is caused by trying to format a masked value. For instance, I get the same warning
if I do this:
```python
>>> import numpy as np
>>> array = np.array([1, 2, 3, 4], dtype=np.float32)
>>> masked = np.ma.masked_array(array, mask=True)
>>> f'{masked[0]:0.2f}'
<stdin>:1: FutureWarning: Format strings passed to MaskedConstant are ignored, but in future may error or produce different behavior
'--'
```

**Comment by joelvbernier** [comment]
Yeah, I saw that.  It looks like it is getting ‘—‘.  I believe we can actually use the fix_invalid method to have it report the fill_value instead

**Comment by psavery** [comment]
Okay. It looks like this is a masked array created by matplotlib. Our NaNs are coming out masked because matplotlib is using `np.ma.masked_invalid()` to set the data. They have the fill value set at the default (`1e+20` for floats).

Currently, for these masked values, the intensity in the status bar is showing `--` (which is what comes out if you `print()` a masked value).

For our NaNs in the image, what do we want them displayed as in the status bar? One of these maybe?

1. `--`
2. `NaN`
3. 0

I think we can also just check if the intensity value is `np.ma.core.MaskedConstant`, and if it is, display one of the 3 above instead of trying to format it. That would avoid the formatting warning.
