### ISSUE TITLE
Batch imageseries export

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#758]
Some users have asked for the following updates/checks to the current imageseries export action under "File⇒Save⇒ImageSeries"
- [x] Rename menu item "Images"
- [x] The ability to batch save the imageseries for all detectors using a user-speifed file stem, to which the detector name will be appended (join with '_')
- [x] The option to save the current image (_e.g._ a single frame) or a multiframe imageseries that ignores any aggregation.  The latter case is mainly for the HEDM workflow, as a user might want to load an imageseries with aggregation to get a global view, but then save the associated `OmegaImageSeries` object with the proper processing options (sans aggregation) and omega metadata attached for external analysis.
I realized that this may require a new widget...

**Comment by bnmajor** [comment]
#773 adds a new dialog to allow saving all detector images at once:

![save_all_images](https://user-images.githubusercontent.com/51238406/109209259-51ad6b80-7779-11eb-9704-618f56307956.png)


At the moment the user is expected to enter a file stem for both saving all detectors at once and saving a single detector. The detector name is appended to the stem and the file(s) saved. This behavior can be changed if saving a single detector should behave the way it used to (open a file dialog and make a selection that way).

**Comment by joelvbernier** [comment]
Reopening this issue due to the following bugs:

1. If I try to load a single image (through the widget) after successfully loading a big series of files, it looks like the omega wedges are not getting reset, which leads to the following:
```
Traceback (most recent call last):
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_load_manager.py", line 199, in process_ims
    self.add_omega_metadata(HexrdConfig().imageseries_dict)
  File "c:\users\berni\documents\github\hexrdgui\hexrd\ui\image_load_manager.py", line 343, in add_omega_metadata
    ims_dict[key].metadata['omega'] = omw.omegas
  File "C:\Users\berni\miniconda3\envs\hexrdgui\lib\site-packages\hexrd\imageseries\omega.py", line 145, in omegas
    raise OmegaSeriesError(msg)
hexrd.imageseries.omega.OmegaSeriesError: 'number of frames (1) does not match number of wedge frames (240)'
```
2. I have an example with two empty frames, and if I enter the omega metadata properly in the Load Data widget, I get an `OmegaImageSeriesError` when I attempt to generate eta-ome maps (which requires those data); observe
![Screen Shot 2021-03-03 at 22 47 07](https://user-images.githubusercontent.com/1154130/109922579-6bb3e600-7c72-11eb-94ff-5e42acfa768d.png)
```
Traceback (most recent call last):
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/indexing/run.py", line 85, in ome_maps_selected
    config = create_indexing_config()
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/indexing/create_config.py", line 51, in create_indexing_config
    ImageLoadManager().add_omega_metadata(load_omegas_dict)
  File "/Users/joel/Documents/GitHub/hexrdgui/hexrd/ui/image_load_manager.py", line 343, in add_omega_metadata
    ims_dict[key].metadata['omega'] = omw.omegas
  File "/Users/joel/Documents/GitHub/hexrd/hexrd/imageseries/omega.py", line 145, in omegas
    raise OmegaSeriesError(msg)
hexrd.imageseries.omega.OmegaSeriesError: 'number of frames (480) does not match number of wedge frames (484)'
```
It _should_ be using the omega start, omega stop, and nsteps to generate the omega wedges, but it is somehow using the total number of frames in the file (ignoring the 2 empty frames I've specified).
3. the Stack import seems to be similarly misbehaving, ignoring the specification of empty frames.  It seems like we have to revisit how the `image-files` options are handled.
![Screen Shot 2021-03-03 at 23 17 00](https://user-images.githubusercontent.com/1154130/109925511-b6376180-7c76-11eb-85d6-b41a38bbfd23.png)
![Screen Shot 2021-03-03 at 23 08 30](https://user-images.githubusercontent.com/1154130/109924613-64420c00-7c75-11eb-98e4-47ffdc7cda5c.png)
4. While I am having trouble recreating it, I was seemingly getting an error when importing omega wedges that sum to < 360°; while it is true that the wedges cannot sum to > 360°, we often have scan ranges that sum to less.

There is an example stack that should help your testing on the shared drive under "sample_images":

- RUBY_4537.ge, 242 total frames, 2 empty (at the start), range is -60°, 0° in 240 steps (0.25° delta)
- RUBY_4538.ge, 242 total frames, 2 empty (at the start), range is 0°, 60° in 240 steps (0.25° delta)

The yaml spec to read them is:
```
image-files:
  directory: ../raw_data
  files: "RUBY_4537.ge
RUBY_4538.ge"

options:
  empty-frames: 2
  max-frames: 0

meta:
  panel: ge
```

**Comment by cjh1** [comment]
@joelvbernier I think you may have reopened the wrong issue? Any 1. is fixed by #775, @bnmajor is looking at 2. and 3., we are unable to recreate 4., let us know if you have any more luck recreating it.

**Comment by joelvbernier** [comment]
Ah yes, wrong issue -- not sure how that happened.  It was getting late.  However, 1 is still a bug that I am seeing in master as well.  Regarding 4 @bnmajor, omega wedges that add up to < 360 are ok?

**Comment by bnmajor** [comment]
This was re-opened on accident - the comments/requests in here have been copied to the appropriate issue. Closing.
