### ISSUE TITLE
Change omega input in HEDM Load Data widget

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#760]
Since we ran into the issue with inputting δω for number like 360/1441, I think it would be easiest to change the input fields to [start ω, stop ω, nsteps] and use `imageseries.omega.OmegaWedges` to unify the omega metadata generation in the code.  This is related to #732.  Example usage:
```
omwedges = omega.OmegaWedges(nsteps)
omwedges.addwedge(0, 360, nsteps)

ims.metadata['omega'] = omwedges.omegas
```
We'll leave the omega spec in the existing table as the simple single wedge case... for now.  More complex omega specification (_i.e._ multiple non-contiguous wedges) will be handled using @bnmajor's new import widget.

**Comment by bnmajor** [comment]
@psavery I'll take care of this

**Comment by bnmajor** [comment]
This was changed in #732. Closing.
