### ISSUE TITLE
Material instantiation error

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#767]
When adding a new material in the GUI, the symmetry-appropriate lattice parameter values are not being enforced.  It appears that when a new material is added, it is taking lattice parameters and structure values from the most recently selected material.  For example, if I select sapphire (trigonal) and make a new cubic (fcc) material, I get the following:
![image](https://user-images.githubusercontent.com/1154130/109069906-b1871200-76a6-11eb-94d4-5591ed5307fd.png)
Note that this leads to erroneous reflection indices in the materials table, which implies that the material object is actually getting the infeasible lattice parameters (note that for cubic they should be [a a a 90 90 90] for cubic).  **_Even after editing the free lattice parameter, the reflection table is still incorrect_**.  You have to de/reselect the space group to have it properly generate the reflection table.

There are clearly a few things going on with respect to properly updating the material class, but I propose that we implement a simpler set of default values for the lattice parameters and structure for adding a new material.  
- [ ] make the default lattice parameter(s) can be 5Å.
- [ ] the angular defaults come directly from the space group lattice type,  with the exception of monoclinic and triclinic.  in those cases, we can use 90 degrees for the free angles.
- [ ] make the default structure a single site with a Carbon atom at (0, 0, 0).

@saransh13: can you work with @psavery to make sure the material class is getting instantiated properly?

**Comment by joelvbernier** [comment]
Related:  the density calculation in the properties tab is not getting updated when changing atom types.

**Comment by psavery** [comment]
@saransh13 @joelvbernier What if we do one of the following?

1. Get the default `Material()` created by hexrd to use these options, and just use that when a new material is added. We'd have to modify the defaults [here](https://github.com/HEXRD/hexrd/blob/de82c86204316d2c5a618eab5048b4c0c095285e/hexrd/material.py#L84-L116) to do that. Looks like it is currently using 3.61 angstroms, and creating a single Nickel atom.

2. Create a `default_material.h5` file either in hexrd or hexrdgui, and have the defaults for our material inside there. When the user adds a new material, load the material from that file and use it.

**Comment by joelvbernier** [comment]
I vote for 1!

**Comment by psavery** [comment]
@joelvbernier Okay. Should we change [any of the defaults](https://github.com/HEXRD/hexrd/blob/de82c86204316d2c5a618eab5048b4c0c095285e/hexrd/material.py#L84-L116)? It's currently:
- One Ni atom
- Fm-3m (225) space group
- 3.61 Å lattice parameters
etc.

Once they are good to go, I'll get hexrdgui to start defaulting to that.

**Comment by saransh13** [comment]
Those look good to me. @joelvbernier?

**Comment by psavery** [comment]
#802, which resolves this issue, is setting us up to use the defaults for the material now when a new material gets added.

I also added a quick fix to #802 for updating the lattice parameters as well, but I think the better fix
will come from fixing hexrd/hexrd#205.

**Comment by joelvbernier** [comment]
ah, you already made the assoc to https://github.com/HEXRD/hexrd/issues/205 @psavery :-)

**Comment by joelvbernier** [comment]
Defaults are fine, but we can do a little better; the change is not strictly necessary upon changing the sgnum, but rather is necessary only when the change in sgnum leads to a change in lattice type.  There are 7 lattice types (aka crystal systems):

- cubic: [a, a, a, 90°, 90°, 90°]
- hexagonal: [a, a, c, 90°, 90°, 120°]
- tetragonal: [a, a, c, 90°, 90°, 90°]
- trigonal: [a, a, c, 90°, 90°, 120°]
- orthorhombic: [a, b, c, 90°, 90°, 90°] 
- monoclinic: [a, b, c, 90°, β, 90°]  ***_NOTE: which angle is free depends on the setting!_**
- triclinic: [a, b, c, α, β, γ]

I suggest we write a simple function to catch when the change in sgnum changes the lattice type that fills the free lattice parameters with values that preserve the existing cell volume (not hard), and clobbers angles as necessary.  Free angles can adopt whatever value they had previously for monoclinic and triclinic cases.  The will provide the most useful behavior I think.

**Comment by joelvbernier** [comment]
I am fairly certain that @saransh13 already has the associations between sgnum (plus setting choice where applicable) and both the lattice type and list of free lattice parameters (right @saransh13)?

**Comment by psavery** [comment]
I removed the quick fix from #802 because hexrd/hexrd#205 was fixed.
