### ISSUE TITLE
Add "About" widget

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#768]
Can we add a Tomviz-style about widget?
![Screen Shot 2021-02-24 at 15 50 57](https://user-images.githubusercontent.com/1154130/109082162-45ada500-76b8-11eb-8579-dce290dbef47.png)

**Comment by cjh1** [comment]
Yes, we  can do that. What would you like to see as the text under HEXRDGUI, do you want to include anything about funding etc?

**Comment by joelvbernier** [comment]
I'll come up with some proper auspices statement.

**Comment by cjh1** [comment]
ping @joelvbernier
