### ISSUE TITLE
Add callback to remove duplicate atoms in material structure panel

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#769]
@saransh13 material class has the ability to use the space group to detect and remove duplicate atoms in the unit cell -- this is important to get the density and structure factors correct.  It is also easy to accidentally add a duplicate site by hand, especially if you are unknowingly using an unsymmetrized structure.

So... we need a "Remove duplicate sites" button to call this functionality, which with update the site list for the material.  AFAIK it will need a tolerance (single scalar in Å) as a threshold to determine duplicate positions (@saransh13?).

**Comment by psavery** [comment]
Sounds good.

**Comment by saransh13** [comment]
PR https://github.com/HEXRD/hexrd/pull/196 added this functionality in heard. I discovered a small bug in there which will be fixed in an upcoming PR.

**Comment by joelvbernier** [comment]
@cjh1 -- function exists; need a button in the materials --> structure tab.  @saransh13 can provide the fucntion API.
