### ISSUE TITLE
Material structure tab overhaul

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#779]
Some changes for the material structure tab:

- [ ] Remove site selection table. Only add/remove atoms. Display all atoms in the atoms table.
- [ ] Add remove duplicate atoms button (see hexrd/hexrd#196; tracked in #769)
- [ ] Have +/- buttons for adding/removing atoms be "New" and "Delete"
- [x] Add an "apply" button that is grayed out when no changes have been made, and only apply material structure tab changes when the user presses the "apply" button. Don't make changes live.
- [ ] Default to no atoms
- [ ] Allow anisotropic editing of U (tracked in #513)

**Comment by cjh1** [comment]
Last checkbox will be taken care of #769
