### ISSUE TITLE
Support editing omega wedges

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#797]
Once a user has selected files through the load panel, especially through the image stack dialog, they may realize that one or more omegas are actually incorrect. We need to support the ability to edit the omega values in the load panel table and update the omegas accordingly without re-loading the images.

**Comment by bnmajor** [comment]
@joelvbernier I think the simplest way to do this would be to provide an `Update` option in the load panel, maybe under the table like this:
![update_images](https://user-images.githubusercontent.com/51238406/110529563-67128600-80e7-11eb-99eb-16ac4c86d143.png)
Let me know if that seems okay and I will add that option in

**Comment by joelvbernier** [comment]
Will the button be grayed out (or some other cue) to show that it has been applied?

**Comment by bnmajor** [comment]
Yes. My thinking was that the button would not be enabled until:
1. The images have been read in
2. The omega values are actually edited

Applying the update would disable the option again until the omegas have been edited once more.
