### ISSUE TITLE
Automatically add polar masks for 2D panel buffers

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#805]
For the polar view, check if each detector has a 2D array for its panel buffer, and if it does, then create a mask from it for the polar view automatically.

**Comment by joelvbernier** [comment]
Per our Slack thread, probably want to make this togglable since it may adversely affect the snip background removal.

**Comment by psavery** [comment]
NaNs are now automatically added to the panel buffer regions in the plot because hexrd/hexrd#208 was merged.

**Comment by psavery** [comment]
Closing, since they are automatically added...
