### ISSUE TITLE
Save simulated lineouts

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#811]
Once WPPF finishes running, the user wants to save the simulated lineouts for pubications etc. Add an option to save the simulated pattern once the run finishes. The data is located in `two_theta, intensity = LeBail.spectrum_sim.data` or `two_theta, intensity = Rietveld.spectrum_sim.data` depending on which option was selected in WPPF. HDF5 could be a good format to write out this data.

The function should also write all the parameters of the class in the file as well.

**Comment by joelvbernier** [comment]
Ooops -- @psavery is there another PR to link to this related to WPPF?
