### ISSUE TITLE
Changes to WPPF Dialog

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#820]
Rather than having an ok/cancel button, have these buttons instead:

- [ ] Run - it runs WPPF, keeping the dialog open, and updating the parameters with their new values
- [ ] Compute - calculates the spectrum given the values of the parameters, to see if we are close to the answer or not

These changes especially make sense in light of #795 and #811

From my discussion with @saransh13

**Comment by saransh13** [comment]
@psavery Can you please hold off any work on this for this week? I'm adding more options to choose additional peak shapes (in addition to the default one) to use for fitting. The user will have the option to choose the peak shapes depending on the input. Each of these shapes comes with its own set of default parameters which will need to be added to the WPPF dialog. Once I have everything testing and merged, we can start work on this again. I think should be only a couple of days.
