### ISSUE TITLE
Auto-picked points need branch cut remapping in polar view

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#849]
Just noticed this @psavery -- I had the eta limits set from (-90, 270) instead of the default (-180, 180), so points with eta values > 180 weren't getting plotted (looked like missed points, but they are there in the raw view).  Simple fix for this; we need to call the `mapAngle` function to, well, re-map the eta to match the ranges selected in the polar view.  Safest bet would be to remap the etas to the period (eta_min, eta_min + 180)

```
from hexrd.transforms.xfcapi import mapAngle

remapped_etas = mapAngle(source_etas, (eta_min, eta_min + 180.), units='degrees')
```

**Comment by psavery** [comment]
Sounds good, we will probably apply that [here](https://github.com/HEXRD/hexrdgui/blob/73750594b1a902717f8ed8b979b78aca0c049206/hexrd/ui/image_canvas.py#L863-L865).
