### ISSUE TITLE
Uses ImageJ-style colormap warping for the "Reset Range" button

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#858]
In general, ImageJ's "auto" button under Image --> Adjust --> Brightness/Contrast works pretty well; better than what we currently have wired to "reset range" in the colormap editor.  Maybe we should wholesale copy the design of their neat little widget that has sliders, the line representing the colormap, and the image histogram:
![image](https://user-images.githubusercontent.com/1154130/112415482-1acb6680-8ce1-11eb-9656-efb16e9c0995.png)
I think we can find their algorithm unless you have some better tricks from Tomviz (or other projects).  Open to suggestions.-!

**Comment by psavery** [comment]
We actually added a brightness and contrast editor similar to ImageJ's (including the auto button) [in tomviz a couple of months ago](https://github.com/OpenChemistry/tomviz/pull/2148).

**Comment by saransh13** [comment]
@psavery the tomviz contrast editor looks dope. I'm in favor of having something similar.
