### ISSUE TITLE
Provide tables for elemental X-ray energy lookup 

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#894]
Often the beam energy in an instrument results from a characteristic emission process.  For example, in the laser-driven shots we field on NIF and Omega, the X-rays are generated by ionizing an elemental foil, which [give characteristic He-&alpha; emission](https://xdb.lbl.gov/Section1/Sec_1-8.pdf).  Lab sources give [characteristic K-&alpha; emission](https://xdb.lbl.gov/Section1/Table_1-2.pdf) according to the anode material, and often the K-edge of a metal foil is used to tune/monitor monochromated synchrotron X-rays.

I am adding a database of the relevant tables to `hexrd/resources` in HDF5 format.

**Comment by joelvbernier** [comment]
The table has the following format:
![image](https://user-images.githubusercontent.com/1154130/115450722-23746700-a1d1-11eb-8369-cba93c2f61e5.png)

**Comment by joelvbernier** [comment]
@psavery -- what do you think, a menu item for optionally setting the instrument wavelength?  Or a button that fires up a widget in the instrument form view?

**Comment by joelvbernier** [comment]
Depends on  https://github.com/HEXRD/hexrd/pull/256

**Comment by joelvbernier** [comment]
@psavery -- the required hexrd dep was already merged for this one, so we would just need a new widget to select X-ray energy from [this HDF5 file](https://github.com/HEXRD/hexrd/blob/master/hexrd/resources/characteristic_xray_energies.h5) (including the possibility to average two entries).

**Comment by psavery** [comment]
@joelvbernier Is this LLNL or HEDM, or either?

**Comment by saransh13** [comment]
This should be LLNL.
