### ISSUE TITLE
Reflecting transform in load panel

### ISSUE THREAD

**Issue by bnmajor** [HEXRD/hexrdgui#902]
There is still an issue in the load panel when transforms are selected for images. If there are multiple images selected for a detector, the transforms chosen when confirming image/detector association are not reflected in the load panel.

The problem right now is that in the load panel the selected transform is applied to all images for that detector. In the load dialog however, the user is able to set the transform per image.

@joelvbernier How would we like to handle this? We could:

1. Assume that the user will be applying the same transform to all images for a detector and simply reflect the selection of the first image for each detector in the load panel.
2. Force the user to have the same transform for all images associated with a detector. In the load dialog changing one transform would change all that are associated with that detector.
3. Change the transform option in the load panel to read something like `multiple transforms` if multiple images are loaded per detector. It would essentially be temporarily changing the `None` text in this case. It would not be a selectable option in the menu and would be reset to `None` as soon as the images are loaded. Changing the transform in the load panel would keep the same behavior: the selection is a applied to all images.

**Comment by joelvbernier** [comment]
number 2 is the proper behavior; the transforms are detector-specific, and all images for a detector will be transformed the same way in a given session.
