### ISSUE TITLE
Overlay manager

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#92]
Can we promote the panel for the ring overlays to a separate manager ("overlay manager") that will provide the ability to add overlays from multiple materials?  Looking forward, there will be 2 additional overlay types I can envision using:

- single crystal Laue patterns; and 
- single crystal rotation series.

in addition to the polycrysal ("powder") rings.  The single crystal overlay types will require a material _plus_ a calibration crystal spec.  They will be point markers instead of lines.  Laue patterns are 2-d for single images like the powder patterns with a set of (x, y) detector coordinates specified for each image, while the rotation series overlays are 3-d with (x, y, omega) coordinates, but could be displayed on a omega-projected imageseries (_e.g._ max over all frames)

It would be ideal to be able to build an overlay set from combinations of these three components, which would likely require hooks to line/marker spec for the user to differentiate them.

**Comment by psavery** [comment]
@joelvbernier Hi Joel. For some clarification here, do we want to keep the materials options inside the panel, or move it somewhere else?

I was thinking that if we keep it in the panel, we could perhaps add another table above the hkl table (see below), and the new table would contain the list of materials. The user could add, modify, or delete materials. The hkl table and space group info would be populated with whichever material is currently selected. What do you think about this?

![image](https://user-images.githubusercontent.com/9558430/72812968-81ae4500-3c30-11ea-86f5-18a6df833971.png)

**Comment by psavery** [comment]
I think another potentially simpler option that I might go with is to just add a checkbox at the bottom that says `Show All Materials`, and when it is checked, it will show overlays of all the materials in hexrd. The user will be able to edit the styles of each material individually. And, in the future, we will add options for the different materials to have a type (options for types would be something like `powder`, `Laue`, and `rotation series`).

**Comment by joelvbernier** [comment]
The current master is a big step in the right direction.  After using it, one simple enhancement  would be to add a button to "hide all" instead of having to thumb through the material list to toggle each "visible" checkbox.  The next step is to add the hooks for different types of overlays.  Currently we only have powder rings, but I would also like to plot Laue patterns; this requires both a material selection, then the 12 additional crystal parameters.  Code snippet to follow...

**Comment by psavery** [comment]
@joelvbernier Okay. I kept around the "Calibration Crystal Editor" in a pop-up dialog (it used to be a part of the instrument config). It's currently under "Edit"->"Calibration Crystal", but it doesn't actually do anything. I think we can hopefully re-use this dialog.

![image](https://user-images.githubusercontent.com/9558430/74147752-e296c080-4bd1-11ea-9d91-8178b7218009.png)

**Comment by joelvbernier** [comment]
Patrick, I think instead of inverse stretch, we can have the user import stretch values into the upper triangle of a 3x3 matrix-layout (symmetric matrix, so the 3 lower triangle values are forced to be equal to their counterparts in the upper triangle), and compute the scaled inverse internally, rather than make the use input inverse stretch values.

| 0 | 5 | 4 |
|:-:|:-:|:-:|
| . | 1 | 3 |
| . | . | 2 |
