### ISSUE TITLE
Add ability to export indexing/fit grains config after run to use in batch CLI runs

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrdgui#946]
After the user finishes an HEDM workflow, provide an option to export the config as a yaml file to use in batch CLI runs.

I'm not sure if we will need to be able to export the individual indexing and fit grains steps, or the whole workflow. I'm also not sure about the best place to put it - maybe as a button in the fit grains results dialog? (if this is the case, the button should be disabled if accessed via the "File"->"Open"->"Grain Fitting Results" menu item, since that does not run through the workflow and will probably not have the right options set).

[Here](https://github.com/HEXRD/examples/blob/77671d621f42d3852d44eab24e36f78ba47a3a24/NIST_ruby/multiruby_dexelas/include/mruby_config_composite.yml) is an example of one of the CLI yaml files. As can be seen [here](https://github.com/HEXRD/hexrdgui/blob/2b92ca14b3cc954ceff7fc83a887795c9cbfa18e/hexrd/ui/resources/indexing/default_indexing_config.yml), our internal `HexrdConfig().indexing_config` dictionary is almost the same. However, it is missing a few things:

1. The `material` section. This is set internally by the GUI based upon the material that the user has already loaded into the GUI.
2. The `image_series` section. This is also set internally in the GUI based upon the image series the user has already loaded.
3. The `instrument` key. This is also set based upon the instrument config internally in the GUI.
4. The `find_orientations.orientation_maps.active_hkls` key. In the GUI, we are having the user select hkls via the reflections table, which modifies the hkl exclusions. We then use all of hkls they did not exclude, which is done [here](https://github.com/HEXRD/hexrdgui/blob/2b92ca14b3cc954ceff7fc83a887795c9cbfa18e/hexrd/ui/indexing/create_config.py#L29). Since the exclusions are also used later to determine which hkls to use for fit grains, we will probably not do this kind of thing for the exported config.

For the `material` section, `min_sfac_ratio` is also currently not used by the GUI. The user instead views the reflections table, sorts by structure factor, and then shift-clicks to select hkls above a certain structure factor.

Anyways, if we write out the `HexrdConfig().indexing_config` dictionary as a yaml file (ignoring all keys that start with an underscore), most of the needed settings will already be there. We just need to figure out if we also need to write out the `material`, `image_series`, and `instrument` sections, which will require us to also write out a materials file, image series files, and the instrument file, respectively.

Perhaps the trickiest part is number 4. We want the exclusions in the materials file to match what the user selected in the fit grains options dialog, so that when it gets to that step, the correct hkls are used. We then want to set `find_orientations.orientation_maps.active_hkls` to be indices, that take into account the exclusions, pointing to the hkls that the user selected for generating the eta omega maps. Maybe this also means that the hkls the user selected for generating eta omega maps must not be excluded in fit grains, for this to work properly...

For number 4, I suggest we save the hkl strings (i. e. `1 1 1`, `1 0 0`, etc.) that the user selected for generating the eta omega maps, probably in a list as an underscore variable, such as `find_orientations.orientation_maps._active_hkl_strings`. Then when we export the config, find the indices of the hkls (non-excluded) that match those strings, and set those indices to `find_orientations.orientation_maps.active_hkls`. If any of those hkls are excluded, I guess we can either raise an exception, or ask the user if they want to turn the exclusion for that one off (this will affect the fit grains results, although it may not affect it by much).

**Comment by bnmajor** [comment]
@joelvbernier Will we need to write out the `material`, `image_series`, and `instrument` sections/files for this config?

**Comment by psavery** [comment]
I think we have covered at least most of this (if not all). We can close and open up new issues for more changes in the future. Thank you Brianna!

Fixed by #970
