### ISSUE TITLE
HEDM: Ability to visualize indexing results with specific parameters (Threshold, filtered radius, clustering radius, etc.) 

### ISSUE THREAD

**Issue by minety** [HEXRD/hexrdgui#949]
![image](https://user-images.githubusercontent.com/19909710/120766560-5906b280-c4e8-11eb-90d7-df194cdd5092.png)

![image](https://user-images.githubusercontent.com/19909710/120767066-d6cabe00-c4e8-11eb-8a29-b4584f57bd4c.png)

Is it possible to visualize the indexing results like the above image? **### (From FABLE, frame by frame visualization.)**

Thanks,
Tian

**Comment by minety** [comment]
This would be very helpful for tweaking different parameters (indexing strategy), especially for deformed/small grains.

**Comment by joelvbernier** [comment]
We are working on the Bragg peak browser in the GUI @minety -- I'll keep you posted!

Note that the Eta-Omega map widget lets you see the results of the peak search for the indexing already.

**Comment by minety** [comment]
@joelvbernier 
Thanks!

**Comment by joelvbernier** [comment]
@minety -- this feature is live in master now as of PR #1180
