### ISSUE TITLE
Apply lorentz polarization correction to images

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrdgui#950]
This option will scale the pixels in the images based on the lorentz polarization factors. The computation of the polarization factor will be in the instrument class. The same interface as the "Apply Solid Angle Correction" can be used in the GUI. 

It might make sense to have a sub-option inside "Edit" menu option called "Corrections" where both these options could sit as well. Any future correction factors (such as sample view) can also be put in there.

**Comment by psavery** [comment]
@saransh13 Sounds good.

I think I need to clean up some of the code in hexrdgui that does the corrections as well, to make it more standardized...

**Comment by joelvbernier** [comment]
Agreed -- we can have a submenu for intensity corrections.

**Comment by psavery** [comment]
@saransh13 Let me know when this is added to hexrd.

**Comment by saransh13** [comment]
@psavery https://github.com/HEXRD/hexrd/pull/286 implements the functionality in hexrd. Note that the factors are not properties since it requires the user input of two numbers f_horizontal and f_vertical (they should add up to 1). These are the fraction of x-ray polarized in the horizontal and vertical directions.

**Comment by psavery** [comment]
@saransh13 Sounds good to me!
