### ISSUE TITLE
Add ability to specify 2𝜃 range for WPPF independent of polar view range

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrdgui#985]
It is desireable to be able to specify (more specifically, to restrict) the 2𝜃 range that WPPF will perform the fit over instead of fixing it to the extent of the polarview image.  This will allow for the exclusion of problematic boundary effects when the extent of the polar view exceeds the detector extent(s) (see below).

Should be straightforward to do...

![image](https://user-images.githubusercontent.com/1154130/125701335-5f7464bd-77e8-4cf8-b8c9-8f85bf699e4e.png)

**Comment by psavery** [comment]
@saransh13 Is there currently a way to restrict the WPPF two-theta range in hexrd? Maybe one place to implement it would be [in this property?](https://github.com/HEXRD/hexrd/blob/5e1385d163180a323d897d4e150ee8e3e4bfa4c2/hexrd/wppf/WPPF.py#L781-L786).

**Comment by joelvbernier** [comment]
bumping up the priority on this one @saransh13 -- should be easy to implement, methinks.

**Comment by saransh13** [comment]
So WPPF takes in a numpy array as input. If the input data is just cropped
while passing, WPPF should take care of the rest.
